### ISSUE TITLE
 Uncaught TelegramBot\Api\InvalidJsonException

### ISSUE THREAD

**Issue by Mariya89** [TelegramBot/Api#101]
Здравствуйте! На php 7.0 строка 
$bot->run();
выдает ошибку
Fatal error: Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in /_______vendor/telegram-bot/api/src/BotApi.php:283 Stack trace: #0 -----/vendor/telegram-bot/api/src/Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true) #1 /---------------/index.php(41): TelegramBot\Api\Client->run() #2 {main} thrown in -------/vendor/telegram-bot/api/src/BotApi.php on line 283
Подскажите, пожалуйста, что можно сделать?

**Comment by masterx2** [comment]
+

**Comment by YaroslavMolchan** [comment]
@Mariya89 сама ошибка говорит о том что не отловленное  исключение, то есть в коде нет `try catch` для `InvalidJsonException`, оберните в `try catch` или же можно отключить показ ошибок в ini файле или просто в коде:
`ini_set('display_errors', 1);`
