### ISSUE TITLE
getChatMembersCount method dose not exists! 

### ISSUE THREAD

**Issue by pooria-jahedi** [TelegramBot/Api#102]
hey 😊
how count chat members group ?
how can i, add my custom methods like this ?

**Comment by pooria-jahedi** [comment]
@YaroslavMolchan

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi add this method in version 2.3.6, update package and enjoy :)

**Comment by pooria-jahedi** [comment]
Thank you sir @YaroslavMolchan

**Comment by pooria-jahedi** [comment]
@YaroslavMolchan How can i get Message id that robot send in group ?

**Comment by YaroslavMolchan** [comment]
Same question -  https://github.com/TelegramBot/Api/issues/103
