### ISSUE TITLE
Not work get messege of user

### ISSUE THREAD

**Issue by dasew** [TelegramBot/Api#106]
Hi!

I am used this is code:
`$bot->on(function($Update) use ($bot){
	$message = $Update->getMessage();
	$mtext = $message->getText();
	$cid = $message->getChat()->getId();
	
	if(mb_stripos($mtext,"hi") !== false){
		$bot->sendMessage($message->getChat()->getId(), "hello!");
	}
}, function($message) use ($name){
	return true; // когда тут true - команда проходит
});`

To get arbitrary text from the user. But bot not work(my bot keep silence), and i am use command /help - the answer loops.

PHP error:
`[Wed Nov 22 08:58:10.164850 2017] [cgi:error] [pid 30422] [client 149.154.167.208:40370] AH01215: #2 {main}
[Wed Nov 22 08:58:10.164907 2017] [cgi:error] [pid 30422] [client 149.154.167.208:40370] AH01215:   thrown in /var/www/fonkpmfj/data/www/developer-lab.ru/vendor/telegram-bot/api/src/Client.php on line 157
[Wed Nov 22 08:58:37.331748 2017] [cgi:error] [pid 31289] [client 104.236.195.72:41058] AH01215: PHP Fatal error:  Uncaught exception 'TelegramBot\\Api\\BadMethodCallException' with message 'Method inlineQuery not exists' in /var/www/fonkpmfj/data/www/developer-lab.ru/vendor/telegram-bot/api/src/Client.php:157
[Wed Nov 22 08:58:37.331796 2017] [cgi:error] [pid 31289] [client 104.236.195.72:41058] AH01215: Stack trace:
[Wed Nov 22 08:58:37.331866 2017] [cgi:error] [pid 31289] [client 104.236.195.72:41058] AH01215: #0 /var/www/fonkpmfj/data/www/developer-lab.ru/index.php(160): TelegramBot\\Api\\Client->__call('inlineQuery', Array)
[Wed Nov 22 08:58:37.331935 2017] [cgi:error] [pid 31289] [client 104.236.195.72:41058] AH01215: #1 /var/www/fonkpmfj/data/www/developer-lab.ru/index.php(160): TelegramBot\\Api\\Client->inlineQuery(Object(Closure))
[Wed Nov 22 08:58:37.331944 2017] [cgi:error] [pid 31289] [client 104.236.195.72:41058] AH01215: #2 {main}`

What is my mistake?

**Comment by YaroslavMolchan** [comment]
Maybe it was a problem?

> Uncaught exception 'TelegramBot\\Api\\BadMethodCallException' with message 'Method inlineQuery not exists'
