### ISSUE TITLE
How to delete inline buttons near message?

### ISSUE THREAD

**Issue by dimalizunov95** [TelegramBot/Api#107]
Hi everyone. Trying to make bot using this SDK and can't find how to edit inline buttons near message. I think that's around editing message but can't find how to do it in a right way. 
I make inline buttons this way:
`$keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['callback_data' => '/EUR', 'text' => 'EUR'],
                    ['callback_data' => '/USD', 'text' => 'USD']
                ]
            ]
        );

        $bot->sendMessage($message->getChat()->getId(), "msg", false, null, null, $keyboard);`
So when user pick one of these i want to show another buttons.
`$bot->on(function($update) use ($bot, $callback_loc, $find_command){
    $callback = $update->getCallbackQuery();
    $message = $callback->getMessage();
    $chatId = $message->getChat()->getId();
    $data = $callback->getData();

   
    if($data == "/EUR" || $data == "/USD"){
        // ???
    }

}, function($update){
    $callback = $update->getCallbackQuery();
    if (is_null($callback) || !strlen($callback->getData()))
        return false;
    return true;
});`

**Comment by YaroslavMolchan** [comment]
Check this issue: https://github.com/TelegramBot/Api/issues/105

**Comment by dimalizunov95** [comment]
@YaroslavMolchan ookay seems like a nice way. Could you tell me how to get message ID of the message that had InlineKeyboard and was clicked?
