### ISSUE TITLE
Store data from inlineButton?

### ISSUE THREAD

**Issue by dimalizunov95** [TelegramBot/Api#108]
Hello.
I want to make a simple bot-currencu-converter.
Bot asks you currency 'from' and then asks 'to'.
`// Displaying message with inlineKeyboard
$bot->on(function($Update) use ($bot){

    $message = $Update->getMessage();
    $mtext = $message->getText();
    $cid = $message->getChat()->getId();

    if($mtext == "Change currency"){

        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['callback_data' => '/EUR', 'text' => 'EUR'],
                    ['callback_data' => '/USD', 'text' => 'USD']
                ]
            ]
        );

        $bot->sendMessage($message->getChat()->getId(), "From which currency?", false, null, null, $keyboard);

    }
}, function($message) use ($name){
    return true; // когда тут true - команда проходит
});`

`// Changing previous maessage if clicked inlineButton
$bot->on(function($update) use ($bot, $callback_loc, $find_command){
    $callback = $update->getCallbackQuery();
    $message = $callback->getMessage();
    $chatId = $message->getChat()->getId();
    $data = $callback->getData();

    
    if($data == "/EUR" || $data == "/USD"){
        $bot->answerCallbackQuery( $callback->getId());

        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['callback_data' => '/EUR', 'text' => 'RUR'],
                    ['callback_data' => '/USD', 'text' => 'UAH']
                ]
            ]
        );

        $bot->editMessageText(
            $message->getChat()->getId(),
            $message->getMessageId(),
            'To which currency?',
            null,
            false,
            $keyboard
        );

    }

}, function($update){
    $callback = $update->getCallbackQuery();
    if (is_null($callback) || !strlen($callback->getData()))
        return false;
    return true;
});`

How do i store the first currency?
Should i use database to store the first answer with message_id? Or is there a better way for this.

**Comment by YaroslavMolchan** [comment]
I think better way it's database, than you can make some statistic or something like this, or the simple way it's store in `callback_data` json with `from` and `to` keys, but you need remember about length limits.

**Comment by dimalizunov95** [comment]
@YaroslavMolchan what did you mean to store callback_data? how do i do that in my code?
cuz up to my code i do it in 2 different queries. 
For e.x. user picks 'from currency' i change my message. And then user picks 'after currency' and it's another query. so previous answer here is lost. Or am i getting it wrong?

**Comment by BoShurik** [comment]
@dimalizunov95 just save data from first query. E.g. in database as @YaroslavMolchan said

**Comment by dimalizunov95** [comment]
@BoShurik is it a kind of good practice? Because in case if there were like 5 questions one-after-one should i use Db for each of them?

**Comment by YaroslavMolchan** [comment]
@dimalizunov95 why not?
> what did you mean to store callback_data?

When user type "From" you can get query data and store it in "To" data here:
`if($data == "/EUR" || $data == "/USD"){`
But database will be better to understand I think.

**Comment by BoShurik** [comment]
@dimalizunov95 personally I use `doctrine/cache` or `symfony/cache` to store this kind of data
