### ISSUE TITLE
Getting callback query many times

### ISSUE THREAD

**Issue by dimalizunov95** [TelegramBot/Api#109]
I created test command which displays 2 inline buttons
`$bot->command('test', function ($message) use ($bot) {
    $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
        [
            [
                ['callback_data' => '/test1', 'text' => 'test1'],
                ['callback_data' => '/test2', 'text' => 'test2']
            ]
        ]
    );

    $bot->sendMessage($message->getChat()->getId(), "Choose?", false, null, null, $keyboard);
});`

`$bot->on(function($update) use ($bot, $callback_loc, $find_command){
    $callback = $update->getCallbackQuery();
    $message = $callback->getMessage();
    $chatId = $message->getChat()->getId();
    $data = $callback->getData();

    if($data == '/test1') {
        $bot->sendMessage($message->getChat()->getId(), 'test1');
        $bot->answerCallbackQuery($callback->getId());
    }

    if($data == '/test2') {
        $bot->sendMessage($message->getChat()->getId(), 'test2');
        $bot->answerCallbackQuery($callback->getId());
    }

}, function($update){
    $callback = $update->getCallbackQuery();
    if (is_null($callback) || !strlen($callback->getData()))
        return false;
    return true;
});`

When i press on of these buttons it keep sending me messages
https://imgur.com/urna2tX
But i made only 1 click. What could be the problem?

**Comment by YaroslavMolchan** [comment]
Looks like bad response for keyboard callback

**Comment by ijusss** [comment]
Same problem. Searching for solving.

**Comment by YaroslavMolchan** [comment]
Maybe problem in this code:
```
function($update){
$callback = $update->getCallbackQuery();
if (is_null($callback) || !strlen($callback->getData()))
return false;
return true;
});
```
I don't know what the problem, I also use InlineKeyboardMarkup and it's work fine. Did you check access logs? Maybe webhook send several times?

**Comment by ijusss** [comment]
Access logs:
```
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:17 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 394208 16666:13333
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:26 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 404186 16666:13333
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:32 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 436729 19999:6666
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:39 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 395635 19999:6666
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:42 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 390825 19999:9999
site.ru 149.154.167.230 - - [14/Mar/2018:19:30:56 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 862647 26666:0
site.ru 149.154.167.230 - - [14/Mar/2018:19:31:14 +0300] "POST /turbot/bot/ HTTP/1.1" 200 140 "-" "-" 407422 26666:6666
```

Do you see something wrong?

**Comment by YaroslavMolchan** [comment]
@ijusss this all requests come when you click once?

**Comment by ijusss** [comment]
Yes, 3-4 per min. All the same CallbackQuery data. Like in circle.

**Comment by YaroslavMolchan** [comment]
@ijusss no, need to check logs when you press button

**Comment by ijusss** [comment]
Its over after updating files to last ver. Still don't know why is was.

**Comment by YaroslavMolchan** [comment]
@ijusss I think problem with your code or webswerver config, its work fine for me

**Comment by atlasag** [comment]
Just solved it. 
I have 2  $bot->on   handlers.  
Contition in one of them (for callback buttons) is exaclty as mentioned above.

Another one (for text and reply buttons) had always "return true;".      So, they inteferenced somehow...
Changed to:
```
	}, function($update) use ($bot) {
		$msg = $update->getMessage();
		if (is_null($msg) || !strlen($msg->getText())) {
           return false;
        } 
		return true;
	});
```
