### ISSUE TITLE
Undefined index: last_name

### ISSUE THREAD

**Issue by halenharper** [TelegramBot/Api#11]
Hi, I am using Laravel 5 for my app.
Message successfully send, but after send I see error: 
ErrorException in BaseType.php line 46:
Undefined index: last_name

1. in BaseType.php line 46
2. at HandleExceptions->handleError('8', 'Undefined index: last_name', '/Users/fedarpiashko/partsmarket24-demo/vendor/telegram-bot/api/src/BaseType.php', '46', array('data' => array('id' => '127273129', 'first_name' => 'pmt5_bot', 'username' => 'pmt5_bot'), 'key' => 'last_name', 'item' => true, 'method' => 'setLastName')) in BaseType.php line 46

**Comment by iGusev** [comment]
Tell more about the situation when an error occurs

**Comment by halenharper** [comment]
my Controller:
```
<?php namespace App\Http\Controllers\Admin_new_spares;

use \TelegramBot\Api\BotApi as TG;

class NewSparesController extends Controller {

    public function update()
    {
        $telegram_noty = new TG(env('TELEGRAM_BOT_TOKEN'));
        $telegram_noty->sendMessage('user_id', 'message_text');
        return redirect()->route('admin_new_spares.new_spares.index');
    }
}
```
Message was send, but after I see Error.
If i comment line 46 in BaseType.php - I do not have massage

**Comment by iGusev** [comment]
Do you use the latest version?

**Comment by halenharper** [comment]
Oh, I am sorry.
My bad. I used v.1.0.
After update to v2.2.1 - all OK!
Thank you.
