### ISSUE TITLE
API 3.5

### ISSUE THREAD

**Issue by mehdikhody** [TelegramBot/Api#110]
to use telegram new updates use this.

**[InputMedia](https://github.com/botstan/API#inputmedia)**
```
https://github.com/botstan/API#inputmedia
```

**Comment by BoShurik** [comment]
Not really useful as it requires yii2 which requires redundant dependencies such as jquery

**Comment by YaroslavMolchan** [comment]
Try to add features from 3.5-3.6 on this week.
