### ISSUE TITLE
when sending a message $ bot-> sendMessage ("@Test", "Test"); produces such an error

### ISSUE THREAD

**Issue by sveevs** [TelegramBot/Api#112]
Fatal error: Uncaught exception 'TelegramBot\Api\HttpException' with message 'Bad Request' in /var/www/html/***/telegram-bot/api/src/BotApi.php:261 Stack trace: #0 /var/www/html/***/telegram-bot/api/src/BotApi.php(241): TelegramBot\Api\BotApi::curlValidate(Resource id #8) #1 /var/www/html/***/vendor/telegram-bot/api/src/BotApi.php(210): TelegramBot\Api\BotApi->executeCurl(Array) #2 /var/www/html/****/telegram-bot/api/src/BotApi.php(317): TelegramBot\Api\BotApi->call('sendMessage', Array) #3 [internal function]: TelegramBot\Api\BotApi->sendMessage('@test', '\xD0\xA2\xD0\xB5\xD1\x81\xD1\x82') #4 /var/www/html/***/telegram-bot/api/src/Client.php(196): call_user_func_array(Array, Array) #5 /var/www/html/***/index.php(23): TelegramBot\Api\Client->__call('sendMessage', Array) #6 /var/www/html/***/index.php(23): TelegramBot\Api\Client->sendMessage('@test', ' in /var/www/html/test/telegram-bot/api/src/BotApi.php on line 261

**Comment by YaroslavMolchan** [comment]
Read official docs, you can't send message to any user just type his username.
