### ISSUE TITLE
Don't have PHPStorm tips

### ISSUE THREAD

**Issue by bgpastukh** [TelegramBot/Api#116]
![image](https://user-images.githubusercontent.com/23012652/34309480-d1e15ddc-e75a-11e7-8126-d709292d560d.png)

Why i don't have tips from IDE when i'm using TelegramBot\Api\Client?

**Comment by BoShurik** [comment]
Because https://github.com/TelegramBot/Api/blob/master/src/Client.php#L400

**Comment by bgpastukh** [comment]
can i do some tricks to display tips?

**Comment by BoShurik** [comment]
```php
/** @var \TelegramBot\Api\BotApi|\TelegramBot\Api\Client $bot */
$bot = new \TelegramBot\Api\Client();
```

**Comment by bgpastukh** [comment]
great
