### ISSUE TITLE
can't get the fileID for the Photo

### ISSUE THREAD

**Issue by best-username** [TelegramBot/Api#119]
Hi!
I need to get the fileID for the Photo, i trying this code
```
if($photo = $message->getPhoto()) {
	$file_id = $photo->getFileId();
	$bot->sendMessage($message->getChat()->getId(), "id: $file_id ");
}:
```
But as a result, I do not get anything :(
My task needs to receive a file, store it and send it in the future

**Comment by YaroslavMolchan** [comment]
Method `$message->getPhoto()` return object [ArrayOfPhotoSize](https://github.com/TelegramBot/Api/blob/master/src/Types/ArrayOfPhotoSize.php).

If you need to send `file_id` you need do something like this:
$photos = $message->getPhoto();
```
foreach($photos as $photo) {
     $file_id = $photo->getFileId();
     $bot->sendMessage($message->getChat()->getId(), "id: $file_id ");
}
```

**Comment by best-username** [comment]
Thank you :)
