### ISSUE TITLE
Bot was kicked from the group chat

### ISSUE THREAD

**Issue by dimalizunov95** [TelegramBot/Api#122]
I store all chats in DB. When i make changes to my main keyboard i send it to all chats.

`$cids = $database->queryToSelect(
                    "SELECT chat_id FROM all_chats"
                );

                $keyboard = new ReplyKeyboardMarkup(
                    [
                        [
                            ["text" => "Button1"],
                            ["text" => "Button11"],
                        ],
                        [
                            ["text" => "Button111"]
                        ],
                        [
                            ["text" => "Button2"]
                        ]
                    ],
                    false, true
                );

                $sleep_count = 0;
                foreach ($cids as $cid) {
                    if ($sleep_count %5 == 0) {
                        sleep(2);
                    }
                    $cid = $cid['chat_id'];
                    $bot->sendMessage($cid, 'Keyboard:', false, null, null, $keyboard, true);
                    $sleep_count++;
                }`

But if bot was removed from a chat this loop stops processing. I understand that i can't send messages to chats where bot was removed from but how can i avoid stopping of the loop?

**Comment by BoShurik** [comment]
http://php.net/manual/en/language.exceptions.php

**Comment by dimalizunov95** [comment]
thanks a lot.
