### ISSUE TITLE
how create pagination  for  inline keyboard ?

### ISSUE THREAD

**Issue by pooria-jahedi** [TelegramBot/Api#123]
hi sir 
how can i paginate  my buttons ?

**Comment by pooria-jahedi** [comment]
Please help

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi  what does it mean "paginate my buttons"?

**Comment by pooria-jahedi** [comment]
![screenshot_2018-01-29-19-26-17](https://user-images.githubusercontent.com/6542099/35519821-8cafa05a-052a-11e8-83e7-69b64a33d9cb.png)
Something like this!

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi read official docs, this is just wrapper for api.
