### ISSUE TITLE
Как отправить картинку с текстом одним постом

### ISSUE THREAD

**Issue by jenokizm** [TelegramBot/Api#125]
Собственно сабж. При этом картинки хранятся блобами в бд. Подскажите пожалуйста
пример
https://texterra.ru/upload/img/2017-03-03/2017-03-03-texterra-24.jpg

**Comment by YaroslavMolchan** [comment]
@jenokizm в методе `sendPhoto` есть аттрибут `caption`, только у него лимит в 200 символов
