### ISSUE TITLE
Fatal error: Uncaught TelegramBot\Api\InvalidJsonException

### ISSUE THREAD

**Issue by KotovDmitry** [TelegramBot/Api#127]
Добрый день.

Прошу подсказать по ошибке: **Fatal error:** Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in /var/www/bothandler.ru/vendor/telegram-bot/api/src/BotApi.php:284 Stack trace: #0 /var/www/bothandler.ru/vendor/telegram-bot/api/src/Client.php(135): TelegramBot\Api\BotApi::jsonValidate('', true) #1 /var/www/bothandler.ru/bothandler.php(46): TelegramBot\Api\Client->run() #2 {main} thrown in /var/www/bothandler.ru/vendor/telegram-bot/api/src/BotApi.php on line 284

Версия PHP 7.1.2, расширения все установлены, в том числе json. Из-за этой ошибки, не возможно запустить бота.

Прошу помощи разобраться. Всю голову уже сломал.

Спасибо.

**Comment by KotovDmitry** [comment]
Спасибо всем. А особенно разработчику. Прям помогли душевно. Быстро так отписались. Указали в чем ошибка. Прям супер всё.
[сарказм]

**Comment by ResetButton** [comment]
Такая же проблема, пример из доков взял.

**Comment by BoShurik** [comment]
https://github.com/TelegramBot/Api#client - этот?

**Comment by YaroslavMolchan** [comment]
@ResetButton странно, но у меня боты все работают

**Comment by BoShurik** [comment]
Этот код для WebHook, его должен дергать телеграм, а не пользователь. Логично, что если его дернет пользователь, то json будет пустым

**Comment by ResetButton** [comment]
Вот такую заглушку предложили для удобства отладки.

```
 if(!empty($bot->getRawBody())){
 $bot->run();
 }
```

**Comment by BoShurik** [comment]
@ResetButton Вряд ли у вас получится отладить что-то, если бот не запустится :) Посмотрите в сторону https://github.com/Seldaek/monolog

**Comment by ResetButton** [comment]
Вы чуть выше совершенно правильно указали почему такую ошибку выдает.

Бот то отработает такой скрипт, а вот просто запустить php файл чтоб проверить корректность синтаксиса нельзя.  Поэтому заглушка в принципе работу свою выполняет на несложных скриптах.

**Comment by YaroslavMolchan** [comment]
@ResetButton ide же за синтаксис вам подсказывать должен, ещё через консоль можно файл проверить

**Comment by ninzzo** [comment]
ну и к чему пришли в итоге? вопрос открыт

Как мне создать команду для бота используя эту библиотеку и кривые примеры из нее?!

**Comment by BoShurik** [comment]
@ninzzo Ответ на вопрос: https://github.com/TelegramBot/Api/issues/127#issuecomment-366207429

**Comment by vbpiar** [comment]
Не работает на php >=7.0 ,если кто знает как исправить буду благодарен.
Ставил разные версии на 5 работает а на 7 не хочет.  Явных ошибок не выдает при этом.

**Comment by yrii-b** [comment]
Решена проблема на php>=7.0 ?  плагин бота даже не активируется с Этими ошибками в Вордпресс.

"Fatal error: Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in /..r/vendor/telegram-bot/api/src/BotApi.php:304 Stack trace: #0 /.../vendor/telegram-bot/api/src/Client.php(141): TelegramBot\Api\BotApi::jsonValidate() #1 /.../process/index.php(157): TelegramBot\Api\Client->run() #2 /.../includes/class-tbotsearcher.php(124): require_once('/home/virtwww/w...') #3 /.../class-tbotsearcher.php(77): Plugin_Name->load_dependencies() #4 /.../tbotsearcher.php(78): Plugin_Name->__construct() #5 /.../tbotsearcher.php(82): run_plugin_name() #6 /...../vendor/telegram-bot/api/src/BotApi.php on line 304"

**Comment by yrii-b** [comment]
> Решена проблема на php>=7.0 ? плагин бота даже не активируется с Этими ошибками в Вордпресс.
> 
> "Fatal error: Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in /..r/vendor/telegram-bot/api/src/BotApi.php:304 Stack trace: #0 /.../vendor/telegram-bot/api/src/Client.php(141): TelegramBot\Api\BotApi::jsonValidate() #1 /.../process/index.php(157): TelegramBot\Api\Client->run() #2 /.../includes/class-tbotsearcher.php(124): require_once('/home/virtwww/w...') #3 /.../class-tbotsearcher.php(77): Plugin_Name->load_dependencies() #4 /.../tbotsearcher.php(78): Plugin_Name->__construct() #5 /.../tbotsearcher.php(82): run_plugin_name() #6 /...../vendor/telegram-bot/api/src/BotApi.php on line 304"

Пока решил проблему. закомментировав следующие строки в файле  vendor/telegram-bot/api/src/BotApi.php

"
public static function jsonValidate($jsonString, $asArray)
    {
        $json = json_decode($jsonString, $asArray);

       // if (json_last_error() != JSON_ERROR_NONE) {
      //      throw new InvalidJsonException(json_last_error_msg(), json_last_error());
       // }

        return $json;
    }

"

**Comment by ssujokeu** [comment]
php 7.1.28
та же проблема
