### ISSUE TITLE
Botan.io

### ISSUE THREAD

**Issue by dimalizunov95** [TelegramBot/Api#129]
Botan is not working fully for my. In index.php file i passed botan token to the bot and it saves all info about command as it should according to documentation.
But i can't make it work so it would save for example everything about Reply buttons. I get answer from the bot so bot isn't broken. And token isn't wrong cos it works for commands.

`$bot->on(function ($Update) use ($bot, $database) {

            $message = $Update->getMessage();
            $bot->track($message, 'ReplyButtons');
            ...

}, function ($message) {
            return true;
});`

what did i do wrong here?

**Comment by YaroslavMolchan** [comment]
@dimalizunov95 I don't work with it, but I know that nobody support Botan now, and it can not working now.
