### ISSUE TITLE
Как поприветствовать нового пользователя вступившего в группу?

### ISSUE THREAD

**Issue by dorgenus** [TelegramBot/Api#130]
Ответом. Вот так: https://snag.gy/XWMguy.jpg

**Comment by YaroslavMolchan** [comment]
@dorgenus я думаю это больше вопрос к самому api telegram, а не этой библиотеке

**Comment by dorgenus** [comment]
Я имею ввиду при помощи вашего кода непосредственно как это можно реализовать? Мне нравятся ваши исходники, не хотелось бы из-за этой функции переходить на что-то другое.

**Comment by dorgenus** [comment]
@YaroslavMolchan

**Comment by YaroslavMolchan** [comment]
@dorgenus вы не поняли, вы сначала должны понять как это реализовать в самом telegram api, потом уже спрашивать реализацию у нас, я не разработчик api, я не знаю можно ли это реализовать вообще
