### ISSUE TITLE
Not working editMessageReplyMarkup, editMessageCaption

### ISSUE THREAD

**Issue by ijusss** [TelegramBot/Api#131]
1. Функции не работают (не меняются ни описание ни кнопки), работает только editText (меняет и текст и кнопки)
2. В BotApi.php на всех трех edit'ах стоит "$this->call('editMessageText', ...", интуитивно предполагаю, что должны стоять editMessageReplyMarkup, editMessageCaption соответственно, согласно Bot Api. 

Если это действительно ошибка, прошу исправить. Пока даже с корректировкой исходного кода не получилось использовать функции.

**Comment by ijusss** [comment]
Получилось запустить функции. Действительно, ошибка в исходном коде в файле BotApi.php. 
В  `$this->call('editMessageText'` надо заменить 

> editMessageText

 на 

> editMessageReplyMarkup

 или 

> editMessageCaption

 соответственно.

**Comment by YaroslavMolchan** [comment]
@ijusss видимо у вас не последняя версия, сейчас именно так и есть:
https://github.com/TelegramBot/Api/blob/master/src/BotApi.php#L1033
https://github.com/TelegramBot/Api/blob/master/src/BotApi.php#L1058

**Comment by ijusss** [comment]
Окай, обновлю. Спасибо.
