### ISSUE TITLE
ReplyKeyboardRemove isn't working

### ISSUE THREAD

**Issue by pushitall** [TelegramBot/Api#132]
Trying to remove ReplyKeyboardMarkup using ReplyKeyboardRemove object:
```
$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardRemove(true, false);
$bot->sendMessage($cid, "text", null, false, null, $keyboard, false);
```
User just recieving "text" and custom keyboard isn't removing.

**Comment by pushitall** [comment]
@YaroslavMolchan can you check it, please?

**Comment by YaroslavMolchan** [comment]
@pushitall try to use `ReplyKeyboardRemove` without params, I test it without params and custom keboard removed.

**Comment by Andrew-Sirius** [comment]
![image](https://user-images.githubusercontent.com/6388333/39411228-d9546802-4c0e-11e8-8a0f-3fb6cf2fa4b8.png)

Всё ещё не работает. Я решил проблему заменой имени свойства класса `protected $remove_keyboard;` на `protected $removeKeyboard;`

**Comment by YaroslavMolchan** [comment]
@Andrew-Sirius спасибо, исправил в новой версии.
