### ISSUE TITLE
how use in laravel

### ISSUE THREAD

**Issue by pooria-jahedi** [TelegramBot/Api#133]
Hi sir @YaroslavMolchan
How can i use this package for laravel and set webhook ?

**Comment by YaroslavMolchan** [comment]
The same as for others frameworks, and need to remove csrf for route with telegram webhook

**Comment by pooria-jahedi** [comment]
this is my controller 
![image](https://user-images.githubusercontent.com/6542099/37553373-1cc23af6-29dc-11e8-82de-71be7cd47ed9.png)
and this is my route :

**Comment by pooria-jahedi** [comment]
Is this true ?

**Comment by YaroslavMolchan** [comment]
Need to add api/telegram to except for csrf

**Comment by pooria-jahedi** [comment]
`use \TelegramBot\Api\BotApi`
is this true ?

**Comment by pooria-jahedi** [comment]
i added this rout to exception.
and {TelegramBot\Api\Client}  return this object.
`
object(TelegramBot\Api\Client)#319 (2) {
--
  | ["api":protected]=>
  | object(TelegramBot\Api\BotApi)#322 (5) {
  | ["curl":protected]=>
  | resource(340) of type (curl)
  | ["token":protected]=>
  | string(45) "577588205:AAEX9eAIv2VHxw1ZkxSDOwD4FSzQRN5i5Wo"
  | ["tracker":protected]=>
  | NULL
  | ["trackedEvents":protected]=>
  | array(0) {
  | }
  | ["returnArray":protected]=>
  | bool(true)
  | }
  | ["events":protected]=>
  | object(TelegramBot\Api\Events\EventCollection)#325 (2) {
  | ["events":protected]=>
  | NULL
  | ["tracker":protected]=>
  | NULL
  | }
  | }

`
bot not return $this->bot;

**Comment by pooria-jahedi** [comment]
@YaroslavMolchan  please help me.

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi I don't understand your code, what is it - `$bot = $this->bot`?
Just get code from readme and it will work.
