### ISSUE TITLE
sendMediaGroup: how to send local pictures?

### ISSUE THREAD

**Issue by TheSleepySlee** [TelegramBot/Api#139]
Hi,

I am trying to send multiple local pictures using the sendMediaGroup feature.

`
$media = new \TelegramBot\Api\Types\InputMedia\ArrayOfInputMedia();
$media->addItem(new TelegramBot\Api\Types\InputMedia\InputMediaPhoto("picture.jpg"));
`

This works fine when I give an URL for a picture on the web. However I am not able to send local picture.
I have tried multiple syntax: with the attach:///path/to/file but none work.

Type of errors I am getting:
`PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Bad Request: URL host is empty in /home/user/vendor/telegram-bot/api/src/BotApi.php:268
`
or
`PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Bad Request: wrong file identifier/HTTP URL specified in /home/user/vendor/telegram-bot/api/src/BotApi.php:268
`

Is this feature supported? If yes, any help would be appreciated.
thanks

**Comment by YaroslavMolchan** [comment]
What the problem read the docs?
https://core.telegram.org/bots/api#sending-files

**Comment by TheSleepySlee** [comment]
You mean this doc:
https://core.telegram.org/bots/api#sendmediagroup
which sends to this doc: https://core.telegram.org/bots/api#inputmedia

This is exactly what I tried, by using the "attach://<file_attach_name>" syntax.
But there is something I probably don't understand, and even by trying to google it.
If you could give a hint on how to use this, I would really appreciate your precious time. Thanks.

**Comment by YaroslavMolchan** [comment]
I don't use it in this way, only by URL.
