### ISSUE TITLE
Uncaught TelegramBot\\Api\\HttpException: Continue

### ISSUE THREAD

**Issue by hb220** [TelegramBot/Api#141]
In the last couple of days, I get messages in the log from time to time:

```
Uncaught TelegramBot\\Api\\HttpException: Continue in vendor\\telegram-bot\\api\\src\\BotApi.php:269\nStack trace:\n#0 vendor\\telegram-bot\\api\\src\\BotApi.php(246): TelegramBot\\Api\\BotApi::curlValidate(Resource id #45, false)\n#1 vendor\\telegram-bot\\api\\src\\BotApi.php(215): TelegramBot\\Api\\BotApi->executeCurl(Array)\n#2 vendor\\telegram-bot\\api\\src\\BotApi.php(325): TelegramBot\\Api\\BotApi->call('sendMessage', Array)\n#3 [internal function]: TelegramBot\\Api\\BotApi->sendMessage('-1000101', '\\xF0\\x9F\\x94\\x84 <code>\\xD0\\x98\\xD0\\xB3...', 'HTML')\n#4 vendor\\telegram-bot\\api\\src\\Client.php(405): call_user_func_array(Array, Array)\n#5 hb-pprofile.php(559): TelegramBot\\Api\\Client->__call('sendMessage', Array)\n#6 hb-pprofile.php(414): TeleSend('\\xF0\\x9F\\x94\\x84 <code>\\xD0\\x98\\xD0\\xB3...')\n#7 {main}\n  thrown in vendor\\telegram-bot\\api\\src\\BotApi.php on line 269
Uncaught TelegramBot\\Api\\HttpException: Continue in vendor\\telegram-bot\\api\\src\\BotApi.php:269\nStack trace:\n#0 vendor\\telegram-bot\\api\\src\\BotApi.php(246): TelegramBot\\Api\\BotApi::curlValidate(Resource id #45, false)\n#1 vendor\\telegram-bot\\api\\src\\BotApi.php(215): TelegramBot\\Api\\BotApi->executeCurl(Array)\n#2 vendor\\telegram-bot\\api\\src\\BotApi.php(325): TelegramBot\\Api\\BotApi->call('sendMessage', Array)\n#3 [internal function]: TelegramBot\\Api\\BotApi->sendMessage('-1000101', '\\xF0\\x9F\\x94\\x84 <code>\\xD0\\x98\\xD0\\xB3...', 'HTML')\n#4 vendor\\telegram-bot\\api\\src\\Client.php(405): call_user_func_array(Array, Array)\n#5 hb-pprofile.php(559): TelegramBot\\Api\\Client->__call('sendMessage', Array)\n#6 hb-pprofile.php(414): TeleSend('\\xF0\\x9F\\x94\\x84 <code>\\xD0\\x98\\xD0\\xB3...')\n#7 {main}\n  thrown in vendor\\telegram-bot\\api\\src\\BotApi.php on line 269
```
I did not change anything in my code, only recently did I update with 'composer update'. 

Visually nothing broke, I get the necessary messages from the bot. And while I can not track which messages and why the error occurs.

But still, can someone know the global reason for the 'Continue' error message? What is this about?

**Comment by hb220** [comment]
A problem is still here.

As I think, I resolve this issue via "hack", disabling "expect-continue" mechanism:
$bot->setCurlOption(CURLOPT_HTTPHEADER, array('Expect:'));

But I think, this is not correct. I don't know, what is source of this error message and why the error can appear several times, which in the logic of my program leads to an attempt to send the message again, as a result, duplicate messages appear in the chat. But then still sending the same data goes without this return code.

**Comment by Cyrills** [comment]
I got the same problem.
Any news?

**Comment by jenokizm** [comment]
Hi! I have the latest version telegram-bot/api 2.3.13 but from today started to get the same error

> Continue

I did not change the code and the bot worked for more than a month now, and now it’s broken. apparently the hoster updated the server software. What to do with it?

**Comment by pavbro** [comment]
Got this error two today. 4 years to this problem and nobody knows the reason? Nice )
