### ISSUE TITLE
Add ability to use proxy

### ISSUE THREAD

**Issue by lopatinas** [TelegramBot/Api#143]
Is it possible to implement feature to enable proxy server for bot requests to Telegram API?
Telegram already blocked in some countries and may be blocked in Russia soon.
I've created pull request to add this feature:
https://github.com/TelegramBot/Api/pull/144

**Comment by lopatinas** [comment]
Pull request merged.

You can use setProxy() method passing proxy string like:
socks5://user:password@address:port

**Comment by sergeypavlenko** [comment]
Hi, @lopatinas 

Thanks for new feature. But, for me proxy not work without next curl parameter:

`CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5,`

Even, if I send to method "setProxy" string with proxy type "socks5". Maybe, need add to new method parameter for default proxy type ?

And, why you created new variable with "private" type ? Not "protected" ?

Thanks for answer.

**Comment by lopatinas** [comment]
Hi, @sergeypavlenko!
It looks strange because I use this feature on production site with telegram bot and it works fine.

Which version of PHP and cURL do you use? Maybe that is the reason.
I have PHP 7.2.4 and cURL 7.47.0 on prod.

I didn't see reason why this property should be protected instead of private, because CURLOPT_PROXY is enough to setup proxy, but it may be fixed if we will find why it is not working for you and cannot be fixed on your side.

**Comment by sergeypavlenko** [comment]
Thanks for answer @lopatinas !

PHP version: 5.6.30-0+deb8u1
Curl: 7.38.0

Yes, I know - need update php to 7. But, we can't do it on project now. On this versions programs I have problem.
