### ISSUE TITLE
Пример добавления прокси?

### ISSUE THREAD

**Issue by DenysNosov** [TelegramBot/Api#147]
Ребята, привет!

В последнем релизе добавили проксю.
Покажите пример подключения, а не могу чет разобраться )))
Было бы круто, если бы в описание тоже добавили, думаю вопросы подобного рода зачастят )))

Спасибо!

**Comment by joomla-ua** [comment]
Спасибо!

Кстати через компосер обновил код, пошли ошибки, но в телегу упала фотка.

В новом issue вечером выложу ошибку.

Спасибо за подсказку.

**Comment by Cramac** [comment]
А есть поддержка работы с несколькими прокси?

**Comment by BoShurik** [comment]
@Cramac нет, но можно сделать так https://stackoverflow.com/a/7128236
