### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by dvzzz** [TelegramBot/Api#15]
Делаю так:
```
$bot = new \TelegramBot\Api\BotApi($token);

$bot->sendMessage($chatId, $messageText);
```

Сообщение отправляется, но получаю ошибку:
```
500 Internal Server Error - InvalidArgumentException
in vendor/telegram-bot/api/src/BaseType.php at line 42
```

Версия 2.2.3

**Comment by iGusev** [comment]
Спасибо! Исправлено в новой версии.

**Comment by dvzzz** [comment]
Ошибка осталась

**Comment by iGusev** [comment]
Сейчас в API существует 4 типа чатов:
* `private`
* `group`
* `supergroup`
* `channel`

Согласно документации метода `sendMessage` :
>Parameters - chat_id
> Type - Integer or String
> Required - Yes
>Description - Unique identifier for the target chat or username of the target channel (in the format @channelusername)

Т.е. использование `chat_id` в формате `@channelusername` допустимо только при работе с каналами, при отправке в любые другие типы чатов необходимо использовать целочисленный id.

**Comment by iGusev** [comment]
Я думал, что проблема именно в невозможности отправить сообщения в канал и пофиксил ее вышестоящим коммитом. В будущем будет добавлена более правильная обработка ответов API в случае ошибок
