### ISSUE TITLE
Работа с функцией on

### ISSUE THREAD

**Issue by v-kot** [TelegramBot/Api#151]
Приветствую.  Имеется следующий код
```
   $bot->on(
        function($update) use ($bot){    
            $message = $update->getMessage();
            $mtext = $message->getText();
            $cid = $message->getChat()->getId();
            if(mb_stripos($mtext,"test") !== false){
                $bot->sendMessage($message->getChat()->getId(), "success");
            }
        }, function($message) use ($name){
            return true; 
        }
    );
```
первая часть которого не выполняется ни при каких условиях,  такое чувство что в ту ветвь даже не заходит. Притом добавление команд типа start, help отрабатывает без проблем. В документации не нашел примеров по данной функции. Просьба пояснить, в чем проблема и добавить пример в документацию

**Comment by Airomad** [comment]
И как? Работает? Потому что у меня так же не работает

**Comment by v-kot** [comment]
нет, с update вообще не работает, на него вообще не реагирует. Поэтому пришлось делать таким способом ` $bot->on(function($message) use ($bot){
                $code = $message->getText();
                if($code && mb_stripos($code, '/') === false) {
                    $code = preg_replace('~[^0-9]+~', '', $code);
                    if (mb_strlen($code) != 8) {
                        $bot->sendMessage($message->getChat()->getId(), "Неверный номер!");
                    } elseif (!$this->check_user($code)) {
                        $bot->sendMessage($message->getChat()->getId(), "Пользователя с данным номером не существует!");
                    } else {
                        $id = $message->getFrom()->getId();
                        $this->set_telegram_id($id, $code);
                        $bot->sendMessage($message->getChat()->getId(), "Вы успешно подписались на рассылку!");
                    }
                }
            }, function($message) use ($name){
                return true;
            });`
То есть грубо говоря берем все сообщения, и проверяем, если есть слеш, то это команда, ее не обрабатывает, иначе делаем то что нужно
