### ISSUE TITLE
Перестал работать webhook

### ISSUE THREAD

**Issue by nikitos18** [TelegramBot/Api#152]
Привет всем.
Использую данную либу на разных серваках, после блокировки стал юзать прокси - все было ок. Но сейчас при любых действиях с ботом не происходит обращение к php файлу установленному через setWebHook.
Может у кого была подобная проблема?

P.S. WebHook точно установлен.)

**Comment by hb220** [comment]
Да, есть такая проблема. Роскомпозор блокирует входящее соединение от серверов телеграм. Я решил редиректом со своего VPS.

**Comment by nikitos18** [comment]
Можно поподробнее? Куда редирект?

**Comment by hb220** [comment]
Ну, я на своём VPS-сервере, находящемся за пределами РФ, перенаправляю один порт на сервер, где работает мой бот. Webhook ставлю на тот VPS-сервер.
Да, пришлось для этого сделать ещё один субдомен и SSL для него (иначе только использовать самоподписанные сертификаты).

Вообще, проще всего вынести сервер бота за пределы блокировки.

**Comment by nikitos18** [comment]
Да, это понятно, видимо так и придется делать.

**Comment by nikitos18** [comment]
А посоветуйте VPS за пределами РФ, думал о digital ocean, но его подсети вроде тоже забанили.
