### ISSUE TITLE
Как можно получить сообщение без команды?

### ISSUE THREAD

**Issue by FrozDark** [TelegramBot/Api#153]
В примерах указаны только как прослушивать определённую команду. А как можно получить всю информацию о сообщении? Например, мне нужно получить локацию от пользователя, как её достать?

**Comment by slaawwa** [comment]
@FrozDark, kakto tak:
```
$bot->on(function($update) use ($bot){ 

    $message = $update->getMessage();
    $text = $message->getText();
    $chat_id = $message->getChat()->getId();
    
    $bot->sendMessage($chat_id, "Yor text: $text");
}
```

**Comment by FrozDark** [comment]
@slaawwa 
Не помогло

Я достаю так, если вдруг кому понадобиться
```
$data = json_decode($bot->getRawBody(), true);
$update = Update::fromResponse($data);
$message = $update->getMessage();
$chatId = $message->getChat()->getId();
```

**Comment by Airomad** [comment]
А ф-ция хендлер как выглядит?

**Comment by slaawwa** [comment]
@Airomad, https://github.com/TelegramBot/Api/issues/153#issuecomment-386877981
on() - вызывается но только в чате с ботом

**Comment by ijusss** [comment]
А как реагировать на сообщения вне чата с ботом?

**Comment by ProgramMaster** [comment]
локация привязана к пользователю а не к сообщению
```php
$user_lang = $message->getFrom()->getLanguageCode();
```

**Comment by BoShurik** [comment]
@ProgramMaster локация != локаль

```php
$location = $message->getLocation();
```
