### ISSUE TITLE
Unknown SSL protocol error in connection to api.telegram.org:443

### ISSUE THREAD

**Issue by andrey-helldar** [TelegramBot/Api#154]
Пинг до телеграмма есть, вручную с компа данные в канал уходят, но при использовании пакета выходит ошибка:

```
local.ERROR: Unknown SSL protocol error in connection to api.telegram.org:443
{"exception":"[object] (TelegramBot\\Api\\HttpException(code: 35):
Unknown SSL protocol error in connection to api.telegram.org:443
at /home/vagrant/code/example.com/vendor/telegram-bot/api/src/BotApi.php:260)
```

В методе, вызывающем ошибку, используется `curl`. Почему не заменить этот "деревянный" способ на нормальный [guzzlehttp/guzzle](https://github.com/guzzle/guzzle), с которым таких проблем нет?

**Comment by andrey-helldar** [comment]
Вопрос снят. Провайдер то блокирует запрос, то нет.

**Comment by andrey-helldar** [comment]
Вновь открою проблему, так как, все-таки, пакет `guzzlehttp/guzzle` умеет без проблем [работать через прокси](http://docs.guzzlephp.org/en/stable/request-options.html#proxy). Что, в свою очередь, очень полезно.

**Comment by andrey-helldar** [comment]
По поводу прокси только что нашел информацию в иссуе #147 
Но по пакету вопрос остается открытым.

**Comment by YaroslavMolchan** [comment]
По моему curl тоже просто работает с proxy.

**Comment by cept73** [comment]
Такая же ошибка, кто-нибудь решил?

**Comment by andrey-helldar** [comment]
Да, решил в мае 2018-го - воткнул tor-button от проекта Tor.
Но в сентябре 2019-го они закрыли проект в связи с отсутствием необходимости.
В итоге просто покупаю vps на digital ocean за 5 баксов в месяц и телега успешно цепляется, т.к. между ними и телегой нет ркн)
