### ISSUE TITLE
Сделайте нормальные доки... Хоть какие.

### ISSUE THREAD

**Issue by ivanstnsk** [TelegramBot/Api#155]
Как например, прослушать просто сообщение? Расковыряв код вижу
```
    /**
     * Use this method to add an event.
     * If second closure will return true (or if you are passed null instead of closure), first one will be executed.
     *
     * @param \Closure $event
     * @param \Closure|null $checker
     *
     * @return \TelegramBot\Api\Client
     */
    public function on(Closure $event, Closure $checker = null)
    {
        $this->events->add($event, $checker);

        return $this;
    }
```
ОКей, юзаем:
```
        $bot->on(function($update) use ($bot){ 

            $message = $update->getMessage();
            $text = $message->getText();
            $chat_id = $message->getChat()->getId();
            
            $bot->sendMessage($chat_id, "asdfsdfasdf");
        });
```
В итоге бот молчит. На команды реагирует

**Comment by Airomad** [comment]
Окей, я понял. У вас ошибка или в логике или в комменте.
If second closure will return true (**or if you are passed null instead of closure**), first one will be executed.

Если null передан, то переданное замыкание **не будет вызвано**.  Добавил для теста второе замыкание `function ($any) { return true; }`
Итог - заработало

**Comment by Airomad** [comment]
Добавьте пожалуйста в README пример, а то вижу вопрос уже всплывал неоднократно

**Comment by Airomad** [comment]
Спасибо. Но все равно не хватает хотя бы вики по ф-циям. Примеры в ридми скудные. Может вам помочь с этим?

**Comment by danillas** [comment]
Поддерживаю Airomad насчет документации. Очень не хватает примеров.

**Comment by BoShurik** [comment]
Например? Каких примеров не хватает?

**Comment by danillas** [comment]
Например, по Payments. У меня sendInvoice отказывается работать, что-не так делаю.) Нашел у вас примеры на сайте - там код частями, не совсем понятно что, куда, после кого. Пробую разобраться своими силами, пока без результатов.

**Comment by BoShurik** [comment]
1. Форкаешь репозиторий
2. Пушишь изменения в свой репозитории в отдельную ветку
3. Заходишь на свой репозиторий через сайт и там автоматически появляется кнопка "сделать PR"

**Comment by idem84** [comment]
Тоже поддерживаю, сделайте документацию!

**Comment by homeandriy** [comment]
> Окей, я понял. У вас ошибка или в логике или в комменте.
> If second closure will return true (**or if you are passed null instead of closure**), first one will be executed.
> 
> Если null передан, то переданное замыкание **не будет вызвано**. Добавил для теста второе замыкание `function ($any) { return true; }`
> Итог - заработало

Так что неправильно? можно как то нормально объяснить? что нужно дописать куда? или это все сделано для того что б усложнить код?

**Comment by tridento** [comment]
есть мнение что для подготовки документации уйдёт столько же времени, сколько на подготовку самого кода библиотеки :) в комментариях к коду всё довольно подробно расписано, а с документацией, тем более с примерами, дело такое — их никогда не бывает достаточно, всегда кому-то что-то непонятно и требуется разъяснять еще и еще

**Comment by andryshok** [comment]
Как вы не понимаете.... - в ней уйма методов, в примерах 4 штуки описано, библиотеку приходится разбирать буквально по исходникам...., в итоге часто в голове возникает вопрос - а чем хуже нативе реквест с курлом...., банальщину забрать телефонный номер по нажатию кнопки и то сделать невозможно не перелопатя все исходники

**Comment by tridento** [comment]
не понимаем, тупенькие-с, вашевысокоблагородь! вы уж не серчайте. а только посмотрите, барин, к телеграму-то документацию, к API его, прости-хоспади. и ежли вы уж с одним методом-то, барин, разобрались, так остальные-то работают так же, и даж называются точно как и в самом телеграме. и уж смекалку, барин, использовать пора, коли за код взялись, а то ж засмеют в дворянском собрании, скажут, вот, дескать, помещик Андрюшок крепостным-то своим велел выяснить, как номер телефона получить, а граф Гусев их хворостиной со двора погнал, идите, говорит, и пока мозги не включите, не приходите даже, орёт, аж покраснел весь. а вот у Гуглевского из Тамбовской губернии один крепостной в ссылке был, и из первой же ссылки грамоту привёз:

$request = json_decode(file_get_contents('php://input'),true);
$PhoneNumber = $request['message']['contact']['phone_number'];

говорит, и искать даже особо не пришлось. так-то, ваше высокоблаародие.

**Comment by andryshok** [comment]
Я и смотрю что тупенькие..., как же вы ее написали то если тот кусок кода неверный..., или не вы ее пишите.., а старший брат.....судя по ответу, но да ладно. Вопрос решился - но не так как ваши крепостные привезли. Вообще есть негласное правило - выложил что то в общее пользование, будь добр оформи как положено (прошу заметить не я один об этом указываю) но не ваш случай видимо, потому использовать для продакшена ваше изделие есть дело сомнительное потому что со дня на день оно будет - нот суппортед ввиду полного отсутсвия документации. И да - с людьми разговаривать научитесь - в жизни пригодится.

**Comment by tridento** [comment]
прощенья просим барин :))
