### ISSUE TITLE
Как через long pool юзать?

### ISSUE THREAD

**Issue by gogax** [TelegramBot/Api#156]

**Comment by BoShurik** [comment]
long pool = long polling?

**Comment by gogax** [comment]
Да

**Comment by gogax** [comment]
Мне бы пример, суть понятна. Что-то туплю просто

**Comment by BoShurik** [comment]
Пример как вызывать этот код из консоли?

**Comment by gogax** [comment]
Хочу на хостинге через long poll.

**Comment by gogax** [comment]
Хочу пример

**Comment by BoShurik** [comment]
updates.php
```php
// ...
$updates = $api->getUpdates();
$lastUpdateId = null;
foreach ($updates as $update) {
    $lastUpdateId = $update->getUpdateId();
    processUpdate($update);
}
if ($lastUpdateId) {
    $api->getUpdates($lastUpdateId + 1, 1);
}
```

```bash
watch updates.php
```

**Comment by gogax** [comment]
Опп, спасибо)
Только Call to undefined function processUpdate()

**Comment by BoShurik** [comment]
> Только Call to undefined function processUpdate()

Реализация processUpdate() и инициализация $api спрятана за `// ...`

**Comment by gogax** [comment]
Хмм, не понимаю, куда функцию process вставить

**Comment by BoShurik** [comment]
Чтобы воспользоваться встроенной системой команд, надо использовать метод `handle`

```
// ...
$updates = $api->getUpdates();
$api->handle($update);
$lastUpdate = end($update));
if ($lastUpdate) {
    $api->getUpdates($update->getUpdateId() + 1, 1);
}
```

**Comment by gogax** [comment]
Не поможешь? Буду очень благодарен)

**Comment by gogax** [comment]
Блин, ошибки все какие-то. Не понимаю что не так(

**Comment by gogax** [comment]
Ребят, есть у кого пример?
