### ISSUE TITLE
 Uncaught TelegramBot\Api\HttpException: Bad Request

### ISSUE THREAD

**Issue by apepenkov** [TelegramBot/Api#157]
help pls.

root@vps7987:~# php /var/www/apepenkov.cf/index.php
PHP Notice:  Undefined index: SERVER_NAME in /var/www/apepenkov.cf/index.php on line 20
PHP Notice:  Undefined index: REQUEST_URI in /var/www/apepenkov.cf/index.php on line 20
PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Bad Request: can't parse URL in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php:266
Stack trace:
#0 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(243): TelegramBot\Api\BotApi::curlValidate(Resource id #10, '{"ok":false,"er...')
#1 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(212): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(420): TelegramBot\Api\BotApi->call('setWebhook', Array)
#3 [internal function]: TelegramBot\Api\BotApi->setWebhook('https://')
#4 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array(Array, Array)
#5 /var/www/apepenkov.cf/index.php(21): TelegramBot\Api\Client->__call('setWebhook', Array)
#6 {main}
  thrown in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php on line 266

**Comment by apepenkov** [comment]
i know that part doesnt work because i opebed it in terminal? but bot doesn't work too.

**Comment by BoShurik** [comment]
> TelegramBot\Api\BotApi->setWebhook('https://')

`https://` - is not a valid webhook url

**Comment by apepenkov** [comment]
what I have to do?

**Comment by BoShurik** [comment]
Read the [documentation](https://core.telegram.org/bots/api#setwebhook)
