### ISSUE TITLE
call to undefined function

### ISSUE THREAD

**Issue by apepenkov** [TelegramBot/Api#158]
PHP Fatal error:  Uncaught Error: Call to undefined function TelegramBot\Api\curl_init() in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php:164
Stack trace:
#0 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(40): TelegramBot\Api\BotApi->__construct('606393979:AAHvV...')
#1 /var/www/apepenkov.cf/index.php(10): TelegramBot\Api\Client->__construct('606393979:AAHvV...')
#2 {main}
  thrown in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php on line 164

**Comment by BoShurik** [comment]
Looks like curl extension does not installed. Run this command and post the output here
```bash
php -i | grep cURL
```

**Comment by apepenkov** [comment]
nothing

**Comment by apepenkov** [comment]
but after installation nothing changed
