### ISSUE TITLE
Возникает ошибка!

### ISSUE THREAD

**Issue by gogax** [TelegramBot/Api#160]
54 строка $bot->on(function($update) use ($bot, $callback_loc, $find_command)﻿
Notice: Undefined variable: callback_loc in /home/c/cn20715/testingbot/public_html/bot.php on line 54

Notice: Undefined variable: find_command in /home/c/cn20715/testingbot/public_html/bot.php on line 54

**Comment by gogax** [comment]
На работу не влияет но всеже

**Comment by BoShurik** [comment]
`bot.php` - не файл библиотеки, ошибка на вашей стороне

**Comment by gogax** [comment]
Ой, да, нашел ошибку
