### ISSUE TITLE
Бот не отвечает на сообщения в группе

### ISSUE THREAD

**Issue by Nerossoul** [TelegramBot/Api#163]
Как научить бота отвечать на сообщения в группе. 

       $bot->on(
      function($Update) use ($bot)
      {
        $message = $Update->getMessage();
        $mtext = $message->getText();
        $cid = $message->getChat()->getId();
        $updateId = $Update->getUpdateId();$bot->sendMessage($message->getChat()->getId(), "text");

      if(mb_stripos($mtext,"hi") !== false){
      	$bot->sendMessage($message->getChat()->getId(), $updateId);
      } else {
        $bot->sendMessage($message->getChat()->getId(), "вы сказали: ".$mtext);
      }
    },
    function($message) use ($name)
    {
      return true; // когда тут true - команда проходит
    });`

вот эта функция прекрасно работает если мы пишем на прямую боту. то есть вся логика работает отлично. но если бота добавить в группу то он не реагирует на уже на эти команды. я так понимаю что когда бот находится в группе функция **on** не вызывается. чем тогда её заменить? или как поравить код чтоб все работало?

**Comment by ijusss** [comment]
Та же проблема с каналами. Как получить обновления с каналов и групп, в которые подключен бот?

**Comment by Nerossoul** [comment]
Нашел решение:

**Comment by Nerossoul** [comment]
Мне кажется это надо добавить в README целый день потратил на поиск решения.

**Comment by LazarenkoA** [comment]
> **Нашел решение:** надо в настройках бота у _**@Botfather**_ установить group privacy
> `Privacy mode (https://core.telegram.org/bots#privacy-mode) is disabled`
> иначе бот не получает ни чего кроме комант начинающихся со /
> устанавливаем group privacy в положение отключено и бот начинает читать все сообщения от всех пользователей на канале. :-)

но почему-то кроме сообщений от других ботов

**Comment by xynobo** [comment]
> но почему-то кроме сообщений от других ботов, т.е. если в групповой чат пришлет сообщение другой бот, оно не обрабатывается (

Согласно правилам телеграмма, боты не видят сообщения друг от друга, вообще.

**Comment by LazarenkoA** [comment]
> > но почему-то кроме сообщений от других ботов, т.е. если в групповой чат пришлет сообщение другой бот, оно не обрабатывается (
> 
> Согласно правилам телеграмма, боты не видят сообщения друг от друга, вообще.

блиин, а можно пруф?

**Comment by xynobo** [comment]
Сорри, сейчас не буду искать, сам когда-то с этим мучался. Но теперь знаю точно, боты от ботов не видят ни сообщений, ни команд, ничего

**Comment by altsora** [comment]
> > > но почему-то кроме сообщений от других ботов, т.е. если в групповой чат пришлет сообщение другой бот, оно не обрабатывается (
> > 
> > 
> > Согласно правилам телеграмма, боты не видят сообщения друг от друга, вообще.
> 
> блиин, а можно пруф?

https://tlgrm.ru/docs/bots/faq#pocemu-moj-bot-ne-vidit-soobsenij-ot-drugih-boto

**Comment by k0ichik** [comment]
> ###
> **[Nerossoul](/Nerossoul) ** commented [Jul 14, 2018](#issue-341226276) •

извите за возможно глупый вопрос но куда вписывать это?

**Comment by Ierichon** [comment]
> **Нашел решение:** надо в настройках бота у _**@Botfather**_ установить group privacy `Privacy mode (https://core.telegram.org/bots#privacy-mode) is disabled` иначе бот не получает ни чего кроме комант начинающихся со / устанавливаем group privacy в положение отключено и бот начинает читать все сообщения от всех пользователей на канале. :-)

В моём случае, в настройках приватности выставлен Disable и бот имеет доступ к сообщениям, ему присвоен статус Админа, но вот проблема - на заданные фразы в чате группы, например "Привет", он отвечает в личные сообщения, а не в сообщения группы. Кто сталкивался с таким и куда копать?

**Comment by BoShurik** [comment]
https://core.telegram.org/bots/api#message - надо использовать поле `chat`, а не поле `from` в `chatId`

**Comment by Ierichon** [comment]
> https://core.telegram.org/bots/api#message - надо использовать поле `chat`, а не поле `from` в `chatId`

Всё получилось, от души благодарю!

**Comment by Ierichon** [comment]
А подскажи пожалуйста, какой код надо написать для того, чтобы  при написании ипределенного слова в чате граппы бот присылал и щапускал видео с Ютуба?

**Comment by BoShurik** [comment]
В чем сложность? Проверяете `update.message.text` и если совпадает, то выполняете `sendMessage`.

**Comment by Turnick4ok** [comment]
> > **Нашел решение:** необходимо включить боту_**@Botfather**_установите конфиденциальность группы `Privacy mode (https://core.telegram.org/bots#privacy-mode) is disabled`, иначе бот не получит ничего, кроме команта, начинающего со/установить конфиденциальность группы в положении отключено, и бот начнет читать все сообщения от всех пользователей на канале. :-)
> 
> В моем случае в элементе приватности выставлено Disable и бот имеет доступ к сообщениям, ему присваивается статус Админа, но вот проблема - на заданные фразы в чате группы, например "Привет", он отвечает в личных сообщениях, а не в сообщениях группы. Кто сталкивался с таким и куда копать?




Вы разобрались? Вы можете мне помочь? Как вы решили?

**Comment by BoShurik** [comment]
Решение сразу за цитируемым сообщением -_-

**Comment by Turnick4ok** [comment]
> Решение сразу по цитируемому сообщению -_-

Блин не могу врубиться.

**Comment by Turnick4ok** [comment]
Примерно понял, а как использовать (как переключить) chat Id?

Пн, 30 окт. 2023 г. в 17:41, Alexander Borisov ***@***.***>:

**Comment by BoShurik** [comment]
Не понял вопроса. Как использовать одно значение, а не другое в параметре?

**Comment by Turnick4ok** [comment]
> Решение сразу по цитируемому сообщению -_-

А как или где перейти в [chat id], чтобы использовать “chat” вместо from?
