### ISSUE TITLE
Как получить ответ сервера телеграм на применение нами API методов?

### ISSUE THREAD

**Issue by Nerossoul** [TelegramBot/Api#164]
Например отправил я сообщение ботом и хочу получить ответ сервера телеграм о том, что сообщение ушло успешно и всю информацию о сообщении. как это можно сделать? В частности телеграм написано возвращает message_id на отправку сообщения как его получить этот ответ телеграма?

**Comment by Everhard** [comment]
Там, кажется, всё элементарно.  Должен возвращаться объект соответствующего типа. Например:
```
$response = $bot->sendMessage($chat_id, $message);
echo $response->getMessageId();
```
Возвращается объект класса `TelegramBot\Api\Types\Message`.
