### ISSUE TITLE
Вопрос о работе ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by gloriusglo** [TelegramBot/Api#165]
Всем привет!
Когда я указываю в параметрах кнопки request_contact, при отправке контакта пользователем он отправляется как ответ на предыдущее сообщение ([скрин](https://yadi.sk/i/XgLwDGg43ZmaxW)).
Без указания этого параметра - при нажатии на кнопку от пользователя отправляется просто сообщение.
Вопрос: при отправке контакта так и должно быть, что сообщение с контактами отправляется как ответ на предыдущее? Если нет - как это можно исправить?
```
$bot->on(function($update) use ($bot){
    $message = $update->getMessage();
    $mtext = $message->getText();
    $cid = $message->getChat()->getId();
    $user = $message->getChat()->getUsername();
    if($mtext == "me"){
        $answer = "Hi";
        $keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup([[["text" => "\xF0\x9F\x93\xB2 Добавить телефон"]]], false, true, false);
    }
    if(class_exists($message->getContact()) !== false){
        $tlf = $message->getContact()->getPhoneNumber();
        $answer = "<b>Ваш телефон добавлен к списку контактов!</b>";
    }
    $bot->sendMessage($message->getChat()->getId(), $answer, 'HTML', false, null, $keyboard);
}, function($update){
      $message = $update->getMessage();
      if (is_null($message))
          return false;
      return true;
});
if(!empty($bot->getRawBody())){
    $bot->run();
}
```

**Comment by TTATPuOT** [comment]
https://core.telegram.org/bots/api#keyboardbutton - да, никаких дополнительных методов влияния на кнопки, кроме "text", "request_contact" и "request_location" нет. Соответственно, всё работает правильно.
Но вот сам бот, например, может отправлять контакт без ответа на сообщения.
