### ISSUE TITLE
error

### ISSUE THREAD

**Issue by apepenkov** [TelegramBot/Api#167]
[Mon Aug 27 12:34:50.961102 2018] [:error] [pid 673] [client 149.154.167.213:33236] PHP Fatal error:  Uncaught TelegramBot\\Api\\HttpException: Not Found in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php:267\nStack trace:\n#0 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(244): TelegramBot\\Api\\BotApi::curlValidate(Resource id #3, '{"ok":false,"er...')\n#1 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(213): TelegramBot\\Api\\BotApi->executeCurl(Array)\n#2 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(322): TelegramBot\\Api\\BotApi->call('sendMessage', Array)\n#3 [internal function]: TelegramBot\\Api\\BotApi->sendMessage(326190204, '\\xD0\\x94\\xD0\\xBE\\xD0\\xB1\\xD1\\x80\\xD0\\xBE \\xD0\\xBF\\xD0\\xBE...')\n#4 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array(Array, Array)\n#5 /var/www/apepenkov.cf/index.php(12): TelegramBot\\Api\\Client->__call('sendMessage', Array)\n#6 [internal function]: {closure}(Object(TelegramBot\\Api\\Types\\Message))\n#7 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(172): ReflectionFunction->invokeArgs(Array)\n in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php on line 267

help pls. same code as my works fine on my second server. bot was working yesterday

**Comment by tridento** [comment]
а что, не запретились ли часом сами собой директивы curl в php.ini?

**Comment by apepenkov** [comment]
хм. не знаю, вряд ли. а как проверить

**Comment by tridento** [comment]
в /etc/php/7.0/apache2/php.ini посмотреть строку disable_functions

**Comment by apepenkov** [comment]
pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,

**Comment by tridento** [comment]
а что показывает раздел curl в phpinfo()?

**Comment by apepenkov** [comment]
cURL support | enabled
-- | --
cURL Information | 7.47.0
Age | 3
Features
AsynchDNS | Yes
CharConv | No
Debug | No
GSS-Negotiate | No
IDN | Yes
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | Yes
SPNEGO | Yes
SSL | Yes
SSPI | No
TLS-SRP | Yes
HTTP2 | No
GSSAPI | Yes
KERBEROS5 | Yes
UNIX_SOCKETS | Yes
PSL | No
Protocols | dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host | x86_64-pc-linux-gnu
SSL Version | OpenSSL/1.0.2g
ZLib Version | 1.2.8

**Comment by tridento** [comment]
а выдаёт ли такой же Uncaught exception если запустить простейший вариант бота типа: 
require "../vendor/autoload.php"; use \TelegramBot\Api;
$bot->command('start', function ($message) use ($bot) { $bot->sendMessage($message->getChat()->getId(), 'проверка',null,TRUE,null,null); }); $bot->run();

**Comment by apepenkov** [comment]
сейчас проверю
[Mon Aug 27 13:13:17.386088 2018] [:error] [pid 648] [client 149.154.167.213:60223] PHP Fatal error:  Uncaught TelegramBot\\Api\\HttpException: Not Found in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php:267\nStack trace:\n#0 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(244): TelegramBot\\Api\\BotApi::curlValidate(Resource id #3, '{"ok":false,"er...')\n#1 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(213): TelegramBot\\Api\\BotApi->executeCurl(Array)\n#2 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php(322): TelegramBot\\Api\\BotApi->call('sendMessage', Array)\n#3 [internal function]: TelegramBot\\Api\\BotApi->sendMessage(326190204, '\\xD0\\x94\\xD0\\xBE\\xD0\\xB1\\xD1\\x80\\xD0\\xBE \\xD0\\xBF\\xD0\\xBE...')\n#4 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array(Array, Array)\n#5 /var/www/apepenkov.cf/index.php(12): TelegramBot\\Api\\Client->__call('sendMessage', Array)\n#6 [internal function]: {closure}(Object(TelegramBot\\Api\\Types\\Message))\n#7 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(172): ReflectionFunction->invokeArgs(Array)\n in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php on line 267

**Comment by tridento** [comment]
мне кажется, что ошибка связана с дисфункцией curl, попробуйте использовать curl_errno()

**Comment by apepenkov** [comment]
я переустановил полностью серв, раньше у меня была уже такая ошибка это помогло. сейчас нет, та же ошибка
DELIMITER $$
CREATE DEFINER=`mysqluser`@`localhost` PROCEDURE `newAction`(IN `p_chatId` BIGINT, IN `p_userId` INT, IN `p_userName` VARCHAR(200), IN `p_action` VARCHAR(50))
begin 
  
insert into userStat(chatId, userId, action, userName) values (p_chatId, p_userId, p_action, p_userName);
  
    select count(*) as cnt
    from userStat u 
    where u.chatId = p_chatId 
      and u.userId = p_userId 
      and u.action = p_action 
      and createTime > NOW() -INTERVAL 1 HOUR;

end$$
DELIMITER ;

**Comment by apepenkov** [comment]
ubuntu 16.04

**Comment by tridento** [comment]
sudo apt-get install php7.0-curl? :) ну или там в зависимости от версии php пакет называется

**Comment by tridento** [comment]
а вообще давайте исходник в студию. будем поглядеть

**Comment by apepenkov** [comment]
да есть это 
я ж не такой тупенький

**Comment by apepenkov** [comment]
<?php header('Content-Type: text/html; charset=utf-8');
exit();
$cfg = include("botcfg.php");

require_once("vendor/autoload.php");

$bot = new \TelegramBot\Api\Client($cfg->token);


$bot->command('start', function ($message) use ($bot) {
    $answer = 'Добро пожаловать!';
    $bot->sendMessage($message->getChat()->getId(), $answer);
});


function saveMedia($chatId, $messageId) {
    $cfg = include("botcfg.php");
    $conn = new mysqli($cfg->mysqlServername, $cfg->mysqlUsername, $cfg->mysqlPassword, $cfg->mysqlDbname);
    $result = false;
    try {

        $guid = uniqid();
        $sql = "INSERT INTO userPhoto (userPhotoId, chatId, messageId, fixed) select '".$guid."', ".$chatId.", ".$messageId.", false where not exists (select 1 from userPhoto where messageId = ".$messageId.")";

        $cnt = 0;
        while ($cnt<4) {
            $result = $conn->query($sql);
            if ($result == true) {
                $cnt = 4;
            } else {
                $cnt = $cnt +1;
            }

        }
    } catch (Exception $e) {
        $result = false;
    }
    return $result;
}

$bot->on(function($Update) use ($bot){
    $cfg = include("botcfg.php");
    $action = 'undefined';
    $message = $Update->getMessage();
    $channelPost  = $Update->getChannelPost();
    if (is_null($message)) {
        $message = $channelPost;
    }

    if (is_null($message)) {

        exit(1);
    };
    $chatId = $message->getChat()->getId();

    if (is_null($chatId)) {
        $bot->sendMessage($cfg->traceChatId, 'null chatId');
        exit(2);
    };

    $mtext = $message->getText();

    if (strstr($mtext, "/chatinfo")) {
        if (is_null($channelPost)) {
            $admins = $bot->getChatAdministrators($chatId);
            foreach ($admins as $thisAdm) {
                if ($thisAdm->getUser()->getId() == $message->getFrom()->getId()) {

                    $bot->sendMessage( (abs($cfg->traceChatId) > 0) ? $cfg->traceChatId : $chatId, "ChatId= " . strval($chatId) . ", yourId= " . strval($message->getFrom()->getId()));
                }
            }
            unset($thisAdm);
        }
        else {
            $bot->sendMessage($cfg->traceChatId, "ChannelId= " . strval($chatId));
        }

    }


    if ($chatId == $cfg->listenChatId) {
        $msg = $bot->forwardMessage($cfg->mainChatId, $cfg->listenChatId, $message->getMessageId(), true);
        if ($cfg->autoPin == true) {
            $bot->pinChatMessage($cfg->mainChatId, $msg->getMessageId(), $cfg->pinNotifications);
        }

        exit();
    };


    $conn = new mysqli($cfg->mysqlServername, $cfg->mysqlUsername, $cfg->mysqlPassword, $cfg->mysqlDbname);

    //Check connection
    if ($conn->connect_error) {
        $bot->sendMessage($cfg->traceChatId, $conn->connect_error);
    } else {
    };

    if (($message->getNewChatMember() ) and ($cfg->welcomeText !== "")) {
        $action = 'getNewChatMember';
        try {
            $sql = "select count(*) as cnt from userStat where chatId = ". strval($chatId) ." and userId = ". strval($message->getNewChatMember()->getId()). " and action = 'getNewChatMember'";
            $result = $conn->query($sql);
            $row = $result->fetch_assoc();
            if ($row["cnt"] < 1) {
                $username = ($message->getNewChatMember()->getFirstName()) OR ($message->getNewChatMember()->getUsername()) OR "безымянный человек";
                $bot->sendMessage($chatId, str_replace('*', '\*', str_replace('_', '\_', str_replace('username', $username, $cfg->welcomeText))), 'Markdown');
            }
        } catch (Exception $e) {
            $bot->sendMessage($cfg->traceChatId, $e);
        }
        $sql = "call newAction (" . strval($message->getChat()->getId()) . ", " . strval($message->getNewChatMember()->getId()) . ", '" . $message->getNewChatMember()->getUsername() . "', '" . $action . "')";
        $conn->query($sql);
    }
    // обработка фото
    elseif ($message->getPhoto() ) {
        $action = 'getPhoto';
        saveMedia($chatId, $message->getMessageId());
    }

    // обработка видео
    elseif ($message->getVideo() ) {
        $action = 'getVideo';
        saveMedia($chatId, $message->getMessageId());
    }

    // обработка стикера
    elseif ($message->getSticker() ) {
        $action = 'getSticker';
    }

    // обработка гиф
    elseif (($message->getDocument()) AND  ($message->getDocument()->getMimeType() == "video/mp4")) {
        $action = 'getGif';
        saveMedia($chatId, $message->getMessageId());
    }

    //обработка голоса
    elseif ($message->getVoice() ) {
        $action = 'getVoice';
        $bot->sendMessage($chatId, 'Голосовые сообщения запрещены', null, false, $message->getMessageId());
        sleep($cfg->voiceDelSleep);
        try {
            $bot->deleteMessage($chatId, $message->getMessageId());
        } catch (Exception $e) {
        }
    } elseif (! is_null($mtext) ) {

// фикс медиа
        if (stristr($mtext, "/fix")
            AND (!is_null($message->getReplyToMessage()))
            AND (    ($message->getReplyToMessage()->getPhoto())
                or ($message->getReplyToMessage()->getVideo())
                or (($message->getReplyToMessage()->getDocument()) AND ($message->getReplyToMessage()->getDocument()->getMimeType() == "video/mp4")))
        ) {
            try {
                $botMsg = null;
                if ($message->getFrom()->getId() == $message->getReplyToMessage()->getFrom()->getId()) {
                    $sql = "update userPhoto set fixed = true where chatId = " . $chatId . " and messageId = " . strval($message->getReplyToMessage()->getMessageId());
                    $conn->query($sql);
                    $botMsg = $bot->sendMessage($chatId, "фиксирую...");
                    try {
                        $bot->sendmessage($cfg->traceChatId, "зафиксировано:" . strval($message->getReplyToMessage()->getMessageId()));
                        $bot->forwardMessage($cfg->traceChatId, $chatId, $message->getReplyToMessage()->getMessageId());
                    } catch (Exception $e) {
                        $bot->sendMessage($cfg->traceChatId, "catched ".$e->getMessage());
                    }
                } else {
                    $botMsg = $bot->sendMessage($chatId, "не твое - не трожь!");
                }

                sleep(2);
                try {
                    $bot->deleteMessage($chatId, $message->getMessageId());
                } catch (Exception $e) {

                }
                try {
                    $bot->deleteMessage($chatId, $botMsg->getMessageId());
                } catch (Exception $e) {
                }

            } catch (Exception $e) {
                $bot->sendMessage($cfg->traceChatId, "catched fix " . $e->getMessage());
            }
            exit();
        }
        elseif (    ((strcasecmp($mtext, "fix") ==0)
                or  (stristr($mtext, "/fix"))
                or ($mtext == 'Фикс') or ($mtext == 'фикс') )
            AND (is_null($message->getReplyToMessage()))) {
            $msg2 = $bot->sendMessage($chatId, 'Сначала выделяем фото, потом жмём команду /fix', null, false, $message->getMessageId());
            sleep(5);
            $bot->deleteMessage($chatId, $message->getMessageId());
            $MSGID = ($msg2->getMessageId());
            $bot->deleteMessage($chatId, $MSGID);
        }



//вызов админа
        elseif( (strstr($mtext, "/admin")) and ($chatId  == $cfg->mainChatId)) {
            $admin_str = '';
            try {
                $admins = $bot->getChatAdministrators($chatId);
                foreach ($admins as $thisAdm) {
                    if ($thisAdm->getUser()->isBot() !== true)
                        $admin_str = $admin_str . "@" . $thisAdm->getUser()->getUsername(). " ";
                }
                unset($thisAdm);
            } catch (Exception $e) {
                $bot->sendMessage($cfg->traceChatId,  "/admin error catched ".$e->getMessage());

            }
            if (is_null($message->getReplyToMessage())) {
                $bot->sendMessage($chatId, $admin_str);
            } else {
                $bot->sendMessage($chatId, $admin_str, null, false, $message->getReplyToMessage()->getMessageId());
                try {
                    $bot->forwardMessage($cfg->traceChatId, $chatId, $message->getReplyToMessage()->getMessageId());
                    $bot->sendmessage($cfg->traceChatId, "Админ!");
                } catch (Exception $e) {
                    $bot->sendMessage($cfg->traceChatId, "catched ".$e->getMessage());
                }
            };

            exit();
        }




    };

    //автобан на ГИФ
    if (($action !== 'undefined') and ($chatId == $cfg->mainChatId) and ($action !== 'getNewChatMember')){
        try {
            //ввод в бд(userstat) действий
            $sql = "call newAction (" . strval($message->getChat()->getId()) . ", " . strval($message->getFrom()->getId()) . ", '" . $message->getFrom()->getUsername() . "', '" . $action . "')";

            $result = $conn->query($sql);
            if (($result->num_rows > 0) and ($action == "getGif")) {
                $row = $result->fetch_assoc();
                if ($row["cnt"] > $cfg->restrictLimit) {

                    $bot->restrictChatMember($chatId, $message->getFrom()->getId(), time() + $cfg->restrictTime, true, true, false, true);
                }
            }
        } catch (Exception $e) {
            $bot->sendMessage($cfg->traceChatId, $e);
        }

    };

},
    function($message){
        return true; // когда тут true - бот работает
    }
);

if(!empty($bot->getRawBody())){
    $bot->run();
}
?>

**Comment by apepenkov** [comment]
`<?php header('Content-Type: text/html; charset=utf-8');
exit();
$cfg = include("botcfg.php");

require_once("vendor/autoload.php");

$bot = new \TelegramBot\Api\Client($cfg->token);


$bot->command('start', function ($message) use ($bot) {
    $answer = 'Добро пожаловать!';
    $bot->sendMessage($message->getChat()->getId(), $answer);
});


function saveMedia($chatId, $messageId) {
    $cfg = include("botcfg.php");
    $conn = new mysqli($cfg->mysqlServername, $cfg->mysqlUsername, $cfg->mysqlPassword, $cfg->mysqlDbname);
    $result = false;
    try {

        $guid = uniqid();
        $sql = "INSERT INTO userPhoto (userPhotoId, chatId, messageId, fixed) select '".$guid."', ".$chatId.", ".$messageId.", false where not exists (select 1 from userPhoto where messageId = ".$messageId.")";

        $cnt = 0;
        while ($cnt<4) {
            $result = $conn->query($sql);
            if ($result == true) {
                $cnt = 4;
            } else {
                $cnt = $cnt +1;
            }

        }
    } catch (Exception $e) {
        $result = false;
    }
    return $result;
}

$bot->on(function($Update) use ($bot){
    $cfg = include("botcfg.php");
    $action = 'undefined';
    $message = $Update->getMessage();
    $channelPost  = $Update->getChannelPost();
    if (is_null($message)) {
        $message = $channelPost;
    }

    if (is_null($message)) {

        exit(1);
    };
    $chatId = $message->getChat()->getId();

    if (is_null($chatId)) {
        $bot->sendMessage($cfg->traceChatId, 'null chatId');
        exit(2);
    };

    $mtext = $message->getText();

    if (strstr($mtext, "/chatinfo")) {
        if (is_null($channelPost)) {
            $admins = $bot->getChatAdministrators($chatId);
            foreach ($admins as $thisAdm) {
                if ($thisAdm->getUser()->getId() == $message->getFrom()->getId()) {

                    $bot->sendMessage( (abs($cfg->traceChatId) > 0) ? $cfg->traceChatId : $chatId, "ChatId= " . strval($chatId) . ", yourId= " . strval($message->getFrom()->getId()));
                }
            }
            unset($thisAdm);
        }
        else {
            $bot->sendMessage($cfg->traceChatId, "ChannelId= " . strval($chatId));
        }

    }


    if ($chatId == $cfg->listenChatId) {
        $msg = $bot->forwardMessage($cfg->mainChatId, $cfg->listenChatId, $message->getMessageId(), true);
        if ($cfg->autoPin == true) {
            $bot->pinChatMessage($cfg->mainChatId, $msg->getMessageId(), $cfg->pinNotifications);
        }

        exit();
    };


    $conn = new mysqli($cfg->mysqlServername, $cfg->mysqlUsername, $cfg->mysqlPassword, $cfg->mysqlDbname);

    //Check connection
    if ($conn->connect_error) {
        $bot->sendMessage($cfg->traceChatId, $conn->connect_error);
    } else {
    };

    if (($message->getNewChatMember() ) and ($cfg->welcomeText !== "")) {
        $action = 'getNewChatMember';
        try {
            $sql = "select count(*) as cnt from userStat where chatId = ". strval($chatId) ." and userId = ". strval($message->getNewChatMember()->getId()). " and action = 'getNewChatMember'";
            $result = $conn->query($sql);
            $row = $result->fetch_assoc();
            if ($row["cnt"] < 1) {
                $username = ($message->getNewChatMember()->getFirstName()) OR ($message->getNewChatMember()->getUsername()) OR "безымянный человек";
                $bot->sendMessage($chatId, str_replace('*', '\*', str_replace('_', '\_', str_replace('username', $username, $cfg->welcomeText))), 'Markdown');
            }
        } catch (Exception $e) {
            $bot->sendMessage($cfg->traceChatId, $e);
        }
        $sql = "call newAction (" . strval($message->getChat()->getId()) . ", " . strval($message->getNewChatMember()->getId()) . ", '" . $message->getNewChatMember()->getUsername() . "', '" . $action . "')";
        $conn->query($sql);
    }
    // обработка фото
    elseif ($message->getPhoto() ) {
        $action = 'getPhoto';
        saveMedia($chatId, $message->getMessageId());
    }

    // обработка видео
    elseif ($message->getVideo() ) {
        $action = 'getVideo';
        saveMedia($chatId, $message->getMessageId());
    }

    // обработка стикера
    elseif ($message->getSticker() ) {
        $action = 'getSticker';
    }

    // обработка гиф
    elseif (($message->getDocument()) AND  ($message->getDocument()->getMimeType() == "video/mp4")) {
        $action = 'getGif';
        saveMedia($chatId, $message->getMessageId());
    }

    //обработка голоса
    elseif ($message->getVoice() ) {
        $action = 'getVoice';
        $bot->sendMessage($chatId, 'Голосовые сообщения запрещены', null, false, $message->getMessageId());
        sleep($cfg->voiceDelSleep);
        try {
            $bot->deleteMessage($chatId, $message->getMessageId());
        } catch (Exception $e) {
        }
    } elseif (! is_null($mtext) ) {

// фикс медиа
        if (stristr($mtext, "/fix")
            AND (!is_null($message->getReplyToMessage()))
            AND (    ($message->getReplyToMessage()->getPhoto())
                or ($message->getReplyToMessage()->getVideo())
                or (($message->getReplyToMessage()->getDocument()) AND ($message->getReplyToMessage()->getDocument()->getMimeType() == "video/mp4")))
        ) {
            try {
                $botMsg = null;
                if ($message->getFrom()->getId() == $message->getReplyToMessage()->getFrom()->getId()) {
                    $sql = "update userPhoto set fixed = true where chatId = " . $chatId . " and messageId = " . strval($message->getReplyToMessage()->getMessageId());
                    $conn->query($sql);
                    $botMsg = $bot->sendMessage($chatId, "фиксирую...");
                    try {
                        $bot->sendmessage($cfg->traceChatId, "зафиксировано:" . strval($message->getReplyToMessage()->getMessageId()));
                        $bot->forwardMessage($cfg->traceChatId, $chatId, $message->getReplyToMessage()->getMessageId());
                    } catch (Exception $e) {
                        $bot->sendMessage($cfg->traceChatId, "catched ".$e->getMessage());
                    }
                } else {
                    $botMsg = $bot->sendMessage($chatId, "не твое - не трожь!");
                }

                sleep(2);
                try {
                    $bot->deleteMessage($chatId, $message->getMessageId());
                } catch (Exception $e) {

                }
                try {
                    $bot->deleteMessage($chatId, $botMsg->getMessageId());
                } catch (Exception $e) {
                }

            } catch (Exception $e) {
                $bot->sendMessage($cfg->traceChatId, "catched fix " . $e->getMessage());
            }
            exit();
        }
        elseif (    ((strcasecmp($mtext, "fix") ==0)
                or  (stristr($mtext, "/fix"))
                or ($mtext == 'Фикс') or ($mtext == 'фикс') )
            AND (is_null($message->getReplyToMessage()))) {
            $msg2 = $bot->sendMessage($chatId, 'Сначала выделяем фото, потом жмём команду /fix', null, false, $message->getMessageId());
            sleep(5);
            $bot->deleteMessage($chatId, $message->getMessageId());
            $MSGID = ($msg2->getMessageId());
            $bot->deleteMessage($chatId, $MSGID);
        }



//вызов админа
        elseif( (strstr($mtext, "/admin")) and ($chatId  == $cfg->mainChatId)) {
            $admin_str = '';
            try {
                $admins = $bot->getChatAdministrators($chatId);
                foreach ($admins as $thisAdm) {
                    if ($thisAdm->getUser()->isBot() !== true)
                        $admin_str = $admin_str . "@" . $thisAdm->getUser()->getUsername(). " ";
                }
                unset($thisAdm);
            } catch (Exception $e) {
                $bot->sendMessage($cfg->traceChatId,  "/admin error catched ".$e->getMessage());

            }
            if (is_null($message->getReplyToMessage())) {
                $bot->sendMessage($chatId, $admin_str);
            } else {
                $bot->sendMessage($chatId, $admin_str, null, false, $message->getReplyToMessage()->getMessageId());
                try {
                    $bot->forwardMessage($cfg->traceChatId, $chatId, $message->getReplyToMessage()->getMessageId());
                    $bot->sendmessage($cfg->traceChatId, "Админ!");
                } catch (Exception $e) {
                    $bot->sendMessage($cfg->traceChatId, "catched ".$e->getMessage());
                }
            };

            exit();
        }




    };

    //автобан на ГИФ
    if (($action !== 'undefined') and ($chatId == $cfg->mainChatId) and ($action !== 'getNewChatMember')){
        try {
            //ввод в бд(userstat) действий
            $sql = "call newAction (" . strval($message->getChat()->getId()) . ", " . strval($message->getFrom()->getId()) . ", '" . $message->getFrom()->getUsername() . "', '" . $action . "')";

            $result = $conn->query($sql);
            if (($result->num_rows > 0) and ($action == "getGif")) {
                $row = $result->fetch_assoc();
                if ($row["cnt"] > $cfg->restrictLimit) {

                    $bot->restrictChatMember($chatId, $message->getFrom()->getId(), time() + $cfg->restrictTime, true, true, false, true);
                }
            }
        } catch (Exception $e) {
            $bot->sendMessage($cfg->traceChatId, $e);
        }

    };

},
    function($message){
        return true; // когда тут true - бот работает
    }
);

if(!empty($bot->getRawBody())){
    $bot->run();
}
?>
`

**Comment by apepenkov** [comment]
на exit в начале внимания не обращайте, просто бот находится в активном чате и не хочу чтобы он спамил

**Comment by apepenkov** [comment]
прошу прощекния, все оказалось просто. я все таки тупенький и перепутал токены ботов местами. спасибо что уделили время :D

**Comment by tridento** [comment]
блин, всё как всегда :))
