### ISSUE TITLE
Fatal error: Uncaught TelegramBot\Api\InvalidArgumentException in .......\telegram-bot\api\src\BaseType.php:39

### ISSUE THREAD

**Issue by Silksofthesoul** [TelegramBot/Api#170]
Zdorova Pasani!

$bot = new BotApi($token, false);
$bot->sendMessage("-myIntChatID", "test new".rand(0,9));

-- конструкция отрабатывает, в чатек, присылает сообщение, но выплевывает вот такую красоту в браузере при тестировании:

<b>Fatal error</b>:  Uncaught TelegramBot\Api\InvalidArgumentException in PATH\TO\AND\TO\vendor\vendor\telegram-bot\api\src\BaseType.php:39
Stack trace:
#0 PATH\TO\AND\TO\vendor\vendor\telegram-bot\api\src\BaseType.php(77): TelegramBot\Api\BaseType::validate(Array)
#1 PATH\TO\AND\TO\vendor\vendor\telegram-bot\api\src\BotApi.php(191): TelegramBot\Api\BaseType::fromResponse(Array)
#2 PATH\TO\app\backend\routers\common\index_get.php(23): TelegramBot\Api\BotApi-&gt;sendMessage('-myIntChatID', 'test new7')
#3 PATH\TO\AND\TO\Libraries\route\route.php(190): App\Library\Route::{closure}()
#4 PATH\TO\app\backend\bootstrap.php(24): App\Library\Route::start()
#5 PATH\TO\www\index.php(3): require_once('PATH\\TO\\...')
#6 {main}
  thrown in <b>PATH\TO\AND\TO\vendor\vendor\telegram-bot\api\src\BaseType.php</b> on line <b>39</b><br />

(ессесено вместо "-myIntChatID" -- стоят нормальные циферки)

**Comment by Silksofthesoul** [comment]
Блин! чувак!

При выполнении **composer require telegram-bot/api** -- прилетает первая версия девелоперской ветки!

Я вручную перенес код в папку с вендорами, и покрайней мере эта ошибка пропала!

**Comment by BoShurik** [comment]
Из России?

**Comment by tridento** [comment]
эка его забирает. видать, из питера

**Comment by Silksofthesoul** [comment]
Сори ребята. Второй день пытаюсь сделать бота на пхп и протестировать локально без https.

короче плюнул я на это дело. и сделал на ноде.

**Comment by tridento** [comment]
так это. разрабы вон пишут что только через хттпс работает. чего тут пытаться и тестировать, на этой обёртке любой бот лепится за час. так что зря ты :) но ежели на ноде можешь, то чего бы и на ноде не делать? :)

**Comment by Silksofthesoul** [comment]
@tridento ну так... рано или поздно это поедет все на дешевый пхпшный хостинг, где нода не работает. ...но видимо придется думать что то, где это хостить.

**Comment by tridento** [comment]
для наглядности закопипастю сюда тот кусок который кидается в тебя.

    public static function validate($data)
    {
        if (count(array_intersect_key(array_flip(static::$requiredParams), $data)) === count(static::$requiredParams)) {
            return true;
        }
        throw new InvalidArgumentException();
    }

следовательно шото ему не нравится в твоих параметрах. попробуй для начала пойти конформистским путём и попытайся сделать как у разраба:

<?php error_reporting(E_ALL); setlocale(LC_ALL, 'ru_RU', 'ru_RU.UTF-8', 'ru', 'russian');
set_time_limit(0);
require "../vendor/autoload.php";
//$token = 'SOME4THING';
$bot = new \TelegramBot\Api\Client($token);
try
{
    $bot->on
    (
        function($Update) use ($bot) {
            $message = $Update->getMessage();
            $input = $message->getText();
            $cid = $message->getChat()->getId();
            
$int_rand = rand(0, 9);
            $bot->sendMessage($cid, "test new" . $int_rand, null, TRUE, null, null);
        },
            function($message) use ($bot) {
                return true;
            } );
            $bot->run();
        }
catch (\TelegramBot\Api\Exception $e)
{
    $e->getMessage();
}
?>

плюс минус что там тебе надо. и посмотрим.

**Comment by Silksofthesoul** [comment]
@tridento большое спасибо! но нет. 
я все удалил и искренне считаю код не работающим. (хотя вероятно, кому нибудь это поможет!)

**Comment by tridento** [comment]
это правильно. если код не заработал, то кто ж может быть виноват кроме разраба ;)) уж точно никак не пользователь. но всё как-то очень уж легко и сразу ты сдался, хотя код заведомо работающий.

**Comment by Silksofthesoul** [comment]
@tridento ну я два дня помучился.... что значит сразу?! :-)

я трейсил эти параметры, ничего необычного не нашел.... А стоп стоп!
Погодите!
Все работает, этот кусок конкретно работает, но после того как я с репозитория слил файлы себе в vendors.

Все бы хорошо, но, при использовании кода из примера
```
try {
    $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN');
    // or initialize with botan.io tracker api key
    // $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN', 'YOUR_BOTAN_TRACKER_API_KEY');
    

    $bot->command('ping', function ($message) use ($bot) {
        $bot->sendMessage($message->getChat()->getId(), 'pong!');
    });
    
    $bot->run();

} catch (\TelegramBot\Api\Exception $e) {
    $e->getMessage();
}
```

(как то так выглядит. и подобный кусок и как в примере бота) -- лезут другие ошибки.

Последнее, что мне очень понравилась, это вылетающий ексепшн с не валидного json. я короче копаю дальше, дальше, дальше -- он пустой. пустой какой то джейсон.... я копаюсь в чьемто коде... это уже не чейто код, а модифицированный мной. ну нафиг! третья библиотека!

Не исключено, что код рабочий. вполне вероятно, что моя конфигурация сервера, не совместима с данным решением. но тут информации нет об этом. я вообще хз, как она работает. может быть работает на php events, а он заведомо не работает на винде. я хз. в общем.

На ноде за пять минут запустил все это дело. За ПЯТЬ, Карл!
Все что нужно node-telegram-bot-api

**Comment by tridento** [comment]
так это что кому привычно. я бы двое суток с нодой колупался, а на пхп привычно и всё быстро получается :) мне кажется что даже на плохом хостинге можно замутить поддержку ноды.

**Comment by Silksofthesoul** [comment]
@tridento есть варианты, но или не секурно, или дополнительные расходы. На дешевых хостингах, как правило нода работает на уровне компилятора фронтенд.

У меня тут появилась идея, нахрен через rospebbery pi это обрабатывать.

**Comment by BoShurik** [comment]
@Silksofthesoul а ты как код из примера запускаешь? Это код webhook-а, он самим телеграмом дергается

**Comment by Silksofthesoul** [comment]
стр. откра с ошибкой этой: 

Fatal error: Uncaught TelegramBot\Api\InvalidJsonException:
Syntax error in JJJJJ\app\backend\core\vendor\vendor\telegram-bot\api\src\BotApi.php:299
Stack trace: #0 JJJJJ\app\backend\core\vendor\vendor\telegram-bot\api\src\Client.php(137):
TelegramBot\Api\BotApi::jsonValidate('', true)
#1 JJJJJ\app\backend\routers\common\index_get.php(35):
TelegramBot\Api\Client->run()
#2 JJJJJ\\app\backend\core\Libraries\route\route.php(190): App\Library\Route::{closure}()
#3 JJJJJ\\app\backend\bootstrap.php(24): App\Library\Route::start()
#4 JJJJJ\\www\index.php(3): require_once('JJJJJ\\\...')
#5 {main} thrown in JJJJJ\\app\backend\core\vendor\vendor\telegram-bot\api\src\BotApi.php on line 299

**Comment by Silksofthesoul** [comment]
@BoShurik Я запускал пример из ридми и из примера по адресу: https://github.com/TelegramBot/DevAnswerBot/blob/master/index.php

**Comment by tridento** [comment]
все запросы к обработчику только через телеграм, соответственно и ответы только туда. тестирование через браузер невозможно :)

**Comment by Silksofthesoul** [comment]
@tridento конечно, конечно. просто он на запросы ен отвечает, лол)) а я так хотел протестировать отправку сообщений, мне собственно только это и нужно было. ....ну и постинг по времени) ...пока что.

**Comment by Silksofthesoul** [comment]
Ладно, спишем на мои кривые руки. Это вполне вероятно. В любом случае, спасибо за ваши старания.

**Comment by tridento** [comment]
@Silksofthesoul давай не будем списывать :) программа действий такова:
1. браузером или курлом делаешь https://api.telegram.org/botTOKENTOKEN/setWebhook?url=https://somedomain.com/index.php
2.установив обработчик, делаешь простейшее:
`require __DIR__ . "/vendor/autoload.php"; 
use \TelegramBot\Api;
    $bot->command ('start', function ($message) use ($bot) {
                $cid = $message->getChat()->getId();
                $bot->sendMessage($cid,"привет! для помощи — /help.",null,TRUE,null,null);
    }    );
$bot->run();`
3.в телеграме в боте пишешь /start
4.смотришь error.log :)

**Comment by Silksofthesoul** [comment]
@tridento я пересилил себя и сделал это!

```
<?php
require __DIR__ . "/vendor/autoload.php";
use \TelegramBot\Api;
use \TelegramBot\Api\Client;

$token = 'HELLOTOKEN';
$bot = new Client($token);

$bot->command('start', function ($message) use ($bot) {
  $cid = $message->getChat()->getId();
  $bot->sendMessage($cid,"привет! для помощи — /help.",null,TRUE,null,null);
});
$bot->run();
?>

```

Ошибки:
```
[11-Sep-2018 15:02:55 Europe/Moscow] PHP Fatal error:  Uncaught Error: Class 'Client' not found in JJJJJJJJ-bot\index.php:5
Stack trace:
#0 {main}
  thrown in JJJJJJJJ-bot\index.php on line 5
[11-Sep-2018 15:03:05 Europe/Moscow] PHP Fatal error:  Uncaught Error: Class 'TelegramBot\Client' not found in JJJJJJJJ-bot\index.php:7
Stack trace:
#0 {main}
  thrown in JJJJJJJJ-bot\index.php on line 7
[11-Sep-2018 15:03:19 Europe/Moscow] PHP Fatal error:  Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php:299
Stack trace:
#0 JJJJJJJJ-bot\vendor\telegram-bot\api\src\Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true)
#1 JJJJJJJJ-bot\index.php(13): TelegramBot\Api\Client->run()
#2 {main}
  thrown in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php on line 299
[11-Sep-2018 15:04:43 Europe/Moscow] PHP Fatal error:  Uncaught Error: Call to a member function command() on null in JJJJJJJJ-bot\index.php:9
Stack trace:
#0 {main}
  thrown in JJJJJJJJ-bot\index.php on line 9
[11-Sep-2018 15:04:47 Europe/Moscow] PHP Fatal error:  Uncaught Error: Call to a member function command() on null in JJJJJJJJ-bot\index.php:9
Stack trace:
#0 {main}
  thrown in JJJJJJJJ-bot\index.php on line 9
[11-Sep-2018 15:04:49 Europe/Moscow] PHP Fatal error:  Uncaught Error: Call to a member function command() on null in JJJJJJJJ-bot\index.php:9
Stack trace:
#0 {main}
  thrown in JJJJJJJJ-bot\index.php on line 9
[11-Sep-2018 15:05:26 Europe/Moscow] PHP Fatal error:  Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php:299
Stack trace:
#0 JJJJJJJJ-bot\vendor\telegram-bot\api\src\Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true)
#1 JJJJJJJJ-bot\index.php(13): TelegramBot\Api\Client->run()
#2 {main}
  thrown in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php on line 299
[11-Sep-2018 15:05:57 Europe/Moscow] PHP Fatal error:  Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php:299
Stack trace:
#0 JJJJJJJJ-bot\vendor\telegram-bot\api\src\Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true)
#1 JJJJJJJJ-bot\index.php(13): TelegramBot\Api\Client->run()
#2 {main}
  thrown in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php on line 299
[11-Sep-2018 15:06:03 Europe/Moscow] PHP Fatal error:  Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php:299
Stack trace:
#0 JJJJJJJJ-bot\vendor\telegram-bot\api\src\Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true)
#1 JJJJJJJJ-bot\index.php(13): TelegramBot\Api\Client->run()
#2 {main}
  thrown in JJJJJJJJ-bot\vendor\telegram-bot\api\src\BotApi.php on line 299
```

Пару замечаний: .... очевидно, сейчас используется версия не 1.0@dev, а актуальная ^2.3
Локального нодовского бота я потушил.
Домена с  https поблизости у меня нет. поэтому я в браузере выполнил следующий запрос: 
`https://api.telegram.org/botTOKENHELLO/setWebhook?url=https://somedomain.com/index.php`
(ессесено с своим токеном, но сомдомейн такой как мне предлагалось)
на что получил ответ:

```
{
"ok": true,
"result": true,
"description": "Webhook was set"
}
```
В телеграмме на /start -- реакции нет ни где.

**Comment by BoShurik** [comment]
Замени

```php
$bot->run();
```

на

```php
$updates = $bot->getUpdates();
$bot->handle($updates);
if ($lastUpdate = end($updates)) {
    $bot->getUpdates($lastUpdate->getUpdateId() + 1, 1);
}
```

И можно запускать из консоли:
```bash
watch php updates.php 
```

**Comment by Silksofthesoul** [comment]
omg! оно немного заработало!

```
C:\OSPanel\domains\jjjj-bot>watch php index.php

"watch" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
```
```
C:\OSPanel\domains\jjjj-bot>php watch index.php

Could not open input file: watch
```

`C:\OSPanel\domains\jjjj-bot>php index.php`

--- и пустота. Скрипт висит. Но если в это время ввести команду боту /start -- то скрипт прекратит работу. При повторном запуске, скрипт выплюнет сообщение в ЧАТ! (в моем случае это будет: привет! для помощи — /help.) ...И сразу же завершает работу.

Код текущей:
```
<?php
require __DIR__ . "/vendor/autoload.php";
use \TelegramBot\Api;
use \TelegramBot\Api\Client;

$token = 'jjjj';
$bot = new Client($token);

$bot->command('start', function ($message) use ($bot) {
  $cid = $message->getChat()->getId();
  $bot->sendMessage($cid,"привет! для помощи — /help.",null,TRUE,null,null);
});

$updates = $bot->getUpdates();

$bot->handle($updates);

if ($lastUpdate = end($updates)) {
    $bot->getUpdates($lastUpdate->getUpdateId() + 1, 1);
}

?>
```
Новых ошибок в error.log -- нет.

**Comment by Silksofthesoul** [comment]
структура проекта:

```
Вт 11.09.2018  14:56               109 composer.json
Вт 11.09.2018  14:56             2 394 composer.lock
Вт 11.09.2018  15:38               531 index.php
Вт 11.09.2018  14:56    <DIR>          vendor
```
composer.json:
```
{
    "name": "xxxxx.xxxxx/jjjj-bot",
    "require": {
        "telegram-bot/api": "^2.3"
    }
}
```

**Comment by BoShurik** [comment]
https://ru.wikipedia.org/wiki/Watch

**Comment by Silksofthesoul** [comment]
> **watch** — unix-утилита, которая запускает определённую прогр....
> **unix**
> **nix**
> **x**

https://static.360tv.ru/media/images/articles/crops/c1f5d3b8-d23a-4be9-a9b5-152a29339e3e/crop_921_518.jpg
😿

**Comment by tridento** [comment]
вообще к слову говоря в чем-то я с @Silksofthesoul очень даже солидарен. эта обертка пожалуй лучшая из тех что на php — и ни строчки документации, так, пара примеров для смеха.

**Comment by Silksofthesoul** [comment]
нус ...я пытался :-)
Закрываем тему.

**Comment by BoShurik** [comment]
@tridento а чего не хватает? У кода в секции `Client` добавить, что это код для `webhook` и нет смысла его запускать самому?

**Comment by tridento** [comment]
@BoShurik "откройте орешки, кушайте орешки". блин, ты прав :)

**Comment by Silksofthesoul** [comment]
@tridento нет не прав.

Для меня это к примеру новая совершенно область. и мне не очевидно, то что вы мне писали в ответах.

Быть может, я бы не создал этого issue если бы было описание методов, их возможности и ограничений. 

В других библиотеках я видел методы и пометки типа "эта хрень работает с webhook, а вот эта работает с бубном и рогами дохлого козла, но зато без webhook"

... и вообще, я как пользователь, обладаю крайней степенью тупизма, и рассеяного внимания.
...я трясущимися руками набираю запросы в гугле, мельком читая доки...
...вот такой я вот с детства... ...загадочный.

**Comment by tridento** [comment]
...как с ботом в телеграме...
...работать без вебхука...
...???...

**Comment by BoShurik** [comment]
@Silksofthesoul если не ты сделаешь PR, то кто?
@tridento https://core.telegram.org/bots/api#getting-updates

**Comment by tridento** [comment]
@BoShurik лонг поллинг ОООООООООООЧЕНЬ на любителя. честно говоря, я со своей нубской башни не вижу вообще никакого смысла его использовать и не понимаю, почему он существует (кроме как может быть для какой-то обратной совместимости с древними ботами or somethng)

**Comment by Silksofthesoul** [comment]
@BoShurik вот вот, я вот и надеялся изначально на это(ответ про удобство метода без webhook. В php хотел сделать как демон, но... но не под винду. в nix сделать можно с помощью какого нибудь https://daemon.io).

@BoShurik PR -- значит пиар?

@tridento без вебхука работает например nodejs bot. Причем пока довольно хорошо.

**Comment by BoShurik** [comment]
@Silksofthesoul PR - Pull Request

Эта библиотека почти один-в-один представляет апи telegram. Все методы, что есть тут https://core.telegram.org/bots/api#available-methods представлены и в этой библиотеке с теми же параметрами. Копировать официальную доку - смысла никакого

Информация по long polling тоже есть там: https://core.telegram.org/bots/api#getupdates

**Comment by Silksofthesoul** [comment]
@BoShurik вот так гораздо понятнее. Но я, ранее, не уловил это из readme (my english is bad, but vse taki est). 

Я короче пошел(побежал) с нодовскими причендалами копашится. ...Да и идея поднять его на rospberry -- меня сейчас больше вдохновляет.

Все равно спасибо, ребята, за эту дискуссию! Удачи в ваших проектах!
