### ISSUE TITLE
Как ограничивать пользователя? 

### ISSUE THREAD

**Issue by kafkiansky** [TelegramBot/Api#172]
Использовал ранее другую библиотеку, при которой метод restrictChatMember работал по той же логике, что в этом методе. В ваше библиотеке не работает. Можете подсказать? 

```
$bot->command('over', function ($message) use ($bot) {
        $bot->restrictChatMember($message->getChat()->getId(), $message->getMessage()->getReplyToMessage()->getFrom()->getId(), false, false, false, false);
});
```

И можно ли использовать перечисление ключей в массиве, как в примере ниже:
```

 $bot->restrictChatMember([
            'chat_id' => $message->getChat()->getId(),
            'until_date' => time() + 86400,
            'user_id' => $message->getMessage()->getReplyToMessage()->getFrom()->getId(),
            'can_send_messages' => false,
            'can_send_media_messages' => false,
            'can_send_other_messages' => false,
            'can_add_web_page_previews' => false
        ]);
```

**Comment by kafkiansky** [comment]
Извиняюсь, разобрался. Я вызываю объект сообщения, в то время как $message уже есть тот самый объект. Нужно всего лишь избавиться от вызова getMessage().
Но вопрос про ключи оставляю открытым. В одну строчку неудобно.

**Comment by TTATPuOT** [comment]
Всю жизнь использовал в одну строчку, всё в порядке.
Используйте переменные `$can_send_messages = false` и уже их вставляйте в метод, возможно, облегчит понимание кода. Ну или напишите собственный класс-обвёртку, если это принципиальный вопрос. Готового способа, на сколько я знаю, нет.
