### ISSUE TITLE
$bot->getUpdates(), как остановить?

### ISSUE THREAD

**Issue by mikbox74** [TelegramBot/Api#174]
Приветствую!
Пытаюсь разобраться, как это все работает, выполнил $bot->getUpdates(), и теперь бот безостановочно с интервалами секунд в 10 сам выполняет команду /start и шлет в чат приветствие. Как это прервать?

**Comment by YaroslavMolchan** [comment]
Лучше показать код, похоже на то что ответ сервера вы неправильный отправляете.
