### ISSUE TITLE
Реакция на неизвестную команду боту

### ISSUE THREAD

**Issue by greygler** [TelegramBot/Api#177]
Как правильно обработать неизвестную команду?
Например, я задал команды /start и /help, а на любую другую нужно, то бы бот ответил что-то типа "неизвестная команда".
Спасибо.

**Comment by TTATPuOT** [comment]
```php
$bot->on(function (\TelegramBot\Api\Types\Update $update) use ($bot){ //После бота ещё можно другие параметры передать в функцию

	$message = $update->getMessage(); //Сдесь мы получаем объект Message.
	if (!empty($message)){ //Проверяем, что это действительно сообщение. Если пусто - это может быть, например Callback Query.
		//Ну и здесь уже отрабатываете как хотите. Например:
		$bot->sendMessage($message->getChat()->getId(), 'Я не знаю такой команды');
	}

}, function (){
	return true;
});
```

**Comment by greygler** [comment]
Ок, спасибо.
И сразу вопрос. Если  это пришло Callback Query, как с него правильно вытянуть chatID, Data  и пр.?

**Comment by TTATPuOT** [comment]
Смотрите исходники по типам. Код хорошо документирован и там всё очень понятно.
Если хотите вытянуть из Callback Query ChatId - идёте в соответствующий тип: https://github.com/TelegramBot/Api/blob/master/src/Types/CallbackQuery.php
И ищите через Ctrl+F что-то типа "data" и находите метод `getData()`, которой возвращает строку. По ChatId - немного сложнее, сначала `getFrom()`, далее из типа https://github.com/TelegramBot/Api/blob/master/src/Types/User.php получаете id через `getId()`. Но лучше изначально из обновления получить Chat, а из него ID. А то не всегда люди в ЛС боту пишут, могут и в группах.

**Comment by greygler** [comment]
Благодарю за развернутый ответ!!!!!
