### ISSUE TITLE
In Message.php class missing fromResponse method

### ISSUE THREAD

**Issue by DenisAlliswell** [TelegramBot/Api#18]
Good day!

At first, thanks for what you are doing.
In Message.php class missing ```Message::fromResponse``` static method what is broking code.

Thanks once again!

**Comment by iGusev** [comment]
See [src/Types/Message.php](https://github.com/TelegramBot/Api/blob/master/src%2FTypes%2FMessage.php):
```php
class Message extends BaseType implements TypeInterface {
// code
}
```
`public static function fromResponse($data)` implemented in class `BaseType`. [Link](https://github.com/TelegramBot/Api/blob/master/src%2FBaseType.php#L78)

**Comment by iGusev** [comment]
You can check it in [tests](https://github.com/TelegramBot/Api/blob/master/tests%2FMessageTest.php#L772)
