### ISSUE TITLE
Как научить бота читать сообщения в канале?

### ISSUE THREAD

**Issue by Dreamka** [TelegramBot/Api#182]
На группу реагирует, а из канала ничего не принимает

**Comment by TTATPuOT** [comment]
Используйте метод [GetWebhookInfo](https://core.telegram.org/bots/api#getwebhookinfo) чтобы увидеть какие обновления может получать бот. Должен уметь получать "channel_post".
Подробнее: https://core.telegram.org/bots/api#update и https://core.telegram.org/bots/api#setwebhook
