### ISSUE TITLE
Не работает $bot->on

### ISSUE THREAD

**Issue by kildibekov** [TelegramBot/Api#183]
Никак не хочет работать код:
$bot->on(function (\TelegramBot\Api\Types\Update $update) use ($bot){
	$message = $update->getMessage();
	$bot->sendMessage($message->getChat()->getId(), 'отправляю всегда');
	if (!empty($message)){ 
		$bot->sendMessage($message->getChat()->getId(), 'ошибка команды');
	}
}, function (){
	return true;

В сем может быть проблема?

**Comment by tridento** [comment]
во всём, ты неправильно пишешь. попытайся начать вот так

<?php
require "../vendor/autoload.php";
use \TelegramBot\Api;

define ('BOT_API_TOKEN', ' TOKENTOKENTOKEN');
$bot = new \TelegramBot\Api\Client(BOT_API_TOKEN);

$bot->on(function($Update) use ($bot) {
	$message = $Update->getMessage();
	$input = $message->getText();
	$cid = $message->getChat()->getId();
	$request = json_decode(file_get_contents('php://input'),true);

	if ($input === "/start")) {
		$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(array(array(array ("text" => "кнопка",),array ("text" => "кнопка"))), true, true);
$bot->sendMessage($cid, 'старт!', null, TRUE, null, $keyboard);
}

function($message) use ($bot) {
	return true;
} $bot->run();
?>

**Comment by kildibekov** [comment]
вообще никакой реакции на Ваш код

**Comment by tridento** [comment]
свой токен поставил? вебхук установил?

**Comment by kildibekov** [comment]
конечно. просто отправка сообщений работает отлично.

**Comment by tridento** [comment]
еще кстати проверь где у тебя лежит autoload.php из этой строки
`require "../vendor/autoload.php";`

**Comment by tridento** [comment]
и еще лишние скобки в моём примере вычисть. с телефона сложно писать :)

**Comment by kildibekov** [comment]
Никакой реакции ((

require "vendor/autoload.php";
use \TelegramBot\Api;

define ('BOT_API_TOKEN', '632777914:AAHVZijdkK7kBCghOrvN1pQJlP2tkdI2WE8');
$bot = new \TelegramBot\Api\Client(BOT_API_TOKEN);

$bot->on(function($Update) use ($bot) {
	$message = $Update->getMessage();
	$input = $message->getText();
	$cid = $message->getChat()->getId();
	$request = json_decode(file_get_contents('php://input'),true);

	if ($input === "/start") {
		$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(array(array(array ("text" => "кнопка",),array ("text" => "кнопка"))), true, true);
$bot->sendMessage($cid, 'старт!', null, TRUE, null, $keyboard);
}
},
function($message) use ($bot) {
	return true;
}); 

$bot->run();

**Comment by tridento** [comment]
токен свой сотри :) покажи /var/log/apache2/error.log

**Comment by kildibekov** [comment]
на моем хостинге нет доступа к такому пути ((

**Comment by tridento** [comment]
ну где то же веб сервер должен хранить лог ошибок. надо найти

**Comment by kildibekov** [comment]
149.154.167.229 - - [13/Feb/2019:15:01:14 +0300] "POST /kildibekov/telegram_bot/bot.php HTTP/1.0" 200 198 "-" "-"
149.154.167.229 - - [13/Feb/2019:15:01:15 +0300] "POST /kildibekov/telegram_bot/bot.php HTTP/1.0" 200 198 "-" "-"
149.154.167.229 - - [13/Feb/2019:15:01:34 +0300] "POST /kildibekov/telegram_bot/bot.php HTTP/1.0" 200 198 "-" "-"
149.154.167.229 - - [13/Feb/2019:15:01:50 +0300] "POST /kildibekov/telegram_bot/bot.php HTTP/1.0" 200 198 "-" "-"
149.154.167.229 - - [13/Feb/2019:15:01:53 +0300] "POST /kildibekov/telegram_bot/bot.php HTTP/1.0" 200 198 "-" "-"

**Comment by kildibekov** [comment]
Вот так работает 
$bot->on(function($Update) use ($bot) {
$bot->sendMessage(181043, 'старт!');
},function($message) use ($bot) {return true;}); 

А вот так уже нет: 
$bot->on(function($Update) use ($bot) {
**$message = $Update->getMessage();**
$bot->sendMessage(181043, 'старт!');
},function($message) use ($bot) {return true;});

**Comment by kildibekov** [comment]
чувствую, что ошибка в какой то мелочи, но понять не могу (((

**Comment by tridento** [comment]
пока error.log апача не увидим, ничего сказать нельзя

**Comment by hello-omny** [comment]
Посмотрите код клиента:

```
/**
     * Use this method to add an event.
     * If second closure will return true (or if you are passed null instead of closure), first one will be executed.
     *
     * @param \Closure $event
     * @param \Closure|null $checker
     *
     * @return \TelegramBot\Api\Client
     */
    public function on(Closure $event, Closure $checker = null)
    {
        $this->events->add($event, $checker);

        return $this;
    }
```

Только, почему-то null для Чекера не проходит =/

```
$bot = new \TelegramBot\Api\Client(BOT_API_TOKEN);
$bot->on(
    function($Update) use ($bot) {
        /** @var Client $bot */

        $message = $Update->getMessage();
        $input = $message->getText();
        $cid = $message->getChat()->getId();

        $bot->sendMessage($cid, 'старт!');
    }, 
    function () {
        return true;
    }
);

$bot->run();  // не забываем запускать
```
