### ISSUE TITLE
class VideoNote (круглые видео)

### ISSUE THREAD

**Issue by LVM911** [TelegramBot/Api#184]
Нужно получить id загруженного боту круглого Видео (VideoNote) , в данном Api нет такого класса, я добавил новый файл VideoNote.php и дополнил файл Message.php 
[VideoNote.php_Message.php.zip](https://github.com/TelegramBot/Api/files/2872850/VideoNote.php_Message.php.zip)

Но все равно не работает, подскажите, что не так? 

Загружаю обычный виедо файл - все работает - я получаю id файла, а от с круглым видео не выходит никак.
Вот код.
`
$bot->on(function($update) use ($bot){	
	$message = $update->getMessage();
	$mtext = $message->getText();
	$chat_id = $message->getChat()->getId();
	$username = $message->getFrom()->getFirstName();	

	if($message) {
		$getInfo = $message->getVideoNote()->getFileId();
	
		$bot->sendMessage($message->getChat()->getId(), "Id загруженного файла - $getInfo ");
	}

}, function($message) use ($name){
	return true; /
});
`
Ниже прикрепляю два файла, в которых внес изменения, посмотрите, уже несколько дней ничего не выходит. Спасибо!

**Comment by LVM911** [comment]
Проблему решил, просьба обновите Api - вот файлы
[VideoNote.php_Message.php1.zip](https://github.com/TelegramBot/Api/files/2873156/VideoNote.php_Message.php1.zip)

**Comment by tridento** [comment]
а не мог бы ты еще и сюда выложить код? и кратко прокомментировать. я думаю, много кому будет интересно

**Comment by LVM911** [comment]
> а не мог бы ты еще и сюда выложить код? в смысле текстом. и кратко прокомментировать. я думаю, много кому будет интересно
Как получить file_id (фото, видео mp4, круглого видео videoNote ) когда мы загружаем в бота. Естественно, эти файлы будут уже на сервере телеграм и с легкостью можно будет их высылать пользователям не нагружая свой сервер.
Все должно происходить в функции (**$bot->on(function($update) use ($bot){)**: 
 Ниже код:
```
$bot->on(function($update) use ($bot){
$message = $update->getMessage(); // тут храниться много всего, что можно получить.
$mtext = $message->getText(); //текст введенный пользователем
$chat_id = $message->getChat()->getId(); //получить чат id пользователя
$username = $message->getFrom()->getFirstName(); //Получить имя пользователя

//Получить id круглого видео, которое отправлено пользователем или переслано на бота
	if($message) {
		$getInfo = $message->getVideoNote()->getFileId();
	
		$bot->sendMessage($message->getChat()->getId(), "Привет $username id круглого видео - $getInfo ");
	}
//Получить id простого видео mp4, которое отправлено пользователем или переслано на бота (загружал файл больше 300 МБ) 
/*
	if($message) {
		$getInfo = $message->getVideo()->getFileId();
	
		$bot->sendMessage($message->getChat()->getId(), "Привет $username id Видео mp4 - $getInfo ");
	}



//Получить id фото, которое отправлено пользователем или переслано на бота (бот выдает несколько вариантов id по качеству)
	$photos = $message->getPhoto();
	if(!empty($photos)) foreach($photos as $ph){
		$fileId = $ph->getFileId();
		$bot->sendMessage($message->getChat()->getId(), "фото Файл загружен $fileId");
	}
*/

}, function($message) use ($name){
return true; 
});

```

Все это будет работать если в библиотеку API подменить этих два файла: [VideoNote.php_Message.php1.zip](https://github.com/TelegramBot/Api/files/2873156/VideoNote.php_Message.php1.zip)
находятся они в папке: 
папка с ботом **/vendor/telegram-bot/API/src/Types/**
