### ISSUE TITLE
$parseMode в sendMessage()

### ISSUE THREAD

**Issue by tridento** [TelegramBot/Api#186]
почему значение по умолчанию null? было бы куда комфортнее с умолчальным 'markdown', или, возможно, было бы круто реализовать чтото вроде setDefaultParseMode и setDefaultKeyboard, тогда по ходу пьесы в sendMessage можно было бы почти всегда ограничиваться $chatId и $text...

**Comment by BOTKooper** [comment]
1) Так сделано потому, что в [api](https://core.telegram.org/bots/api#sendmessage) parse_mode указывается **только** в случае текста отличного от plaintext.
2) Не все сообщения **нужно** парсить одинаковыми способами (хотя ничего не мешает отправлять plaintext в качестве html/markdown). Не мучайте телегу, будьте благоразумны

**Comment by dima2duo** [comment]
> 1. Так сделано потому, что в [api](https://core.telegram.org/bots/api#sendmessage) parse_mode указывается **только** в случае текста отличного от plaintext.
> 2. Не все сообщения **нужно** парсить одинаковыми способами (хотя ничего не мешает отправлять plaintext в качестве html/markdown). Не мучайте телегу, будьте благоразумны

Подскажите, понадобилось перед текстом клавиатуры добавить форматированный текст
$bot->sendMessage($message->getChat()->getId(), '<b>Hello</b>', false, null,null,$keyboard);

parse_Mode на html поменял, везде, где было null, но так и не добился успеха. Где ещё прописать нужно или может совсем убрать текст перед клавиатурой, выводя отдельным $bot->sendMessage ?
