### ISSUE TITLE
sendMediaGroup caption

### ISSUE THREAD

**Issue by mhmd1983** [TelegramBot/Api#188]
Hello,
Can we have a caption parameter for sendMediaGroup ?

**Comment by nflm** [comment]
> Hello,
> Can we have a caption parameter for sendMediaGroup ?

Hi,
You can use the second parameter of [InputMediaPhoto](https://github.com/TelegramBot/Api/blob/master/src/Types/InputMedia/InputMediaPhoto.php#L20) and add caption only for the first element:

```
$media = new \TelegramBot\Api\Types\InputMedia\ArrayOfInputMedia();
$media->addItem(new TelegramBot\Api\Types\InputMedia\InputMediaPhoto('url1', 'caption'));
$media->addItem(new TelegramBot\Api\Types\InputMedia\InputMediaPhoto('url2'));
```

**Comment by mhmd1983** [comment]
Works great thanks @nflm

**Comment by tseby** [comment]
any hava examples?
In java in order to provide a caption to the first element you need to add a lot of unneeded parameters  
![Выделение_006](https://user-images.githubusercontent.com/95850699/193468604-ece996e0-8017-4b31-bd03-7138730ae8bb.png)

**Comment by andrewoficial** [comment]
> any java examples? In java in order to provide a caption to the first element you need to add a lot of unneeded parameters ![Выделение_006](https://user-images.githubusercontent.com/95850699/193468604-ece996e0-8017-4b31-bd03-7138730ae8bb.png)

You can add Caption only for first (zero) picture (element in array).

![изображение](https://github.com/TelegramBot/Api/assets/28807056/1378a692-e518-4222-9e35-972192c4b487)
