### ISSUE TITLE
Отправка сообщения

### ISSUE THREAD

**Issue by kristinamohnachyova** [TelegramBot/Api#191]
`if(isset($_GET["any_message"])){
	require_once("../vendor/autoload.php");

	$token = "111:аврен";
	$bot = new \TelegramBot\Api\Client($token);

	$bot->sendMessage(64365345, $_GET["any_message"]);

	$bot->run();
}`
Есть такой код. Когда открываю с браузера, то сообщение отправляется и выдаёт http 200 ok.
Когда подгружаю через file_get_contents, то возвращает 400 ошибку. 
Бот написан для уведомления пользователя о каком-либо событии.

**Comment by BoShurik** [comment]
`$bot->run();` - лишнее

**Comment by kristinamohnachyova** [comment]
> `$bot->run();` - лишнее

Всё равно возвращает 400 ошибку.

**Comment by kristinamohnachyova** [comment]
@BoShurik 
http://prntscr.com/munbaq

**Comment by BoShurik** [comment]
Проблема где-то в вашем коде, который вы нам не показали. У меня ваш код работает

**Comment by kristinamohnachyova** [comment]
И правда, была допущена ошибка в file_get_contents. Вместо urlencode отправляемых данных использовался urldecode. 
Прошу простить
