### ISSUE TITLE
How to send a self-destruction message?

### ISSUE THREAD

**Issue by Spixmaster** [TelegramBot/Api#192]
How is it possible that a bot sends a message which will only be visible for ~30 seconds?

**Comment by BoShurik** [comment]
You should do it by hand
```php
$message = $bot->sendMessage($chatId, $messageText);
```
e.g. send data to queue that deletes message after 30 seconds
```php
$bot->deleteMessage($chatId, $message->getMessageId());
```
But, as it's not a secret chat, message can be saved before deletion

**Comment by Spixmaster** [comment]
As function sendMessage is not void but return a message object one can save the message id and delete the message later.

**Comment by tridento** [comment]
afaik there are some limitations for message deletion. e.g. you cant delete messages older then 48 hours
