### ISSUE TITLE
How to send Unicode?

### ISSUE THREAD

**Issue by Spixmaster** [TelegramBot/Api#193]
How can I send unicode with the bot?

**Comment by BoShurik** [comment]
Can you elaborate? What's problem?

**Comment by Spixmaster** [comment]
```
wchar_t a[] = L"🎊";
bot.getApi().sendMessage(message->chat->id, '@' + message->from->username + " " + a + " Before doing anything in this group activate the bot (@" + bot.getApi().getMe()->username + ")!");
```
I have absolutely no idea. This is what is intended. How would this work?
I use a C++ API.

**Comment by BoShurik** [comment]
It's a php-wrapper for a telegram api. You definitely missed with repo :)

**Comment by Spixmaster** [comment]
@BoShurik yes, the code is c++ but the languages should not differ that much

**Comment by tridento** [comment]
you should try bytes, convert your unicode (with something like https://www.branah.com/unicode-converter) and give it a try

**Comment by BoShurik** [comment]
@Spixmaster but they are different ;) I think working with strings is one of the main deference (from casual POV). And problem here not in the API, but in the language. For example, you can't concatenate string with plus sign in C++ like in your example. If you build proper Unicode string - you API accept it.

**Comment by Spixmaster** [comment]
@tridento That is it. I thank you so much!
When wanting to print out "🎊" you need to write "\xf0\x9f\x8e\x8a" in your code. this site helps to convert: https://www.branah.com/unicode-converter.
Now, i finally understand a little bit what this utf-x means.
