### ISSUE TITLE
Удаление сообщения с Inline клавиатурой

### ISSUE THREAD

**Issue by MeonGans** [TelegramBot/Api#196]
Здравствуйте, есть Inline клавиатура, нужно после выбора одной из кнопок удалить последнее сообщение с клавиатурой. Чтоб получился эффект, что на том же месте сформировался ответ на нажатие кнопки. 
Как подобное организовать?

**Comment by BoShurik** [comment]
А есть пример того, что хотите получить? Че-т по описанию не понятно

**Comment by MeonGans** [comment]
> А есть пример того, что хотите получить? Че-т по описанию не понятно

К примеру бот @LyBot
Там пишешь что хочешь найти. Бот выводит список и две стрелки. По нажатию на стрелки появляется на месте предыдущего списка новый.

**Comment by BoShurik** [comment]
На сколько я вижу, это реализовано через редактирование сообщения, а не удаление

**Comment by MeonGans** [comment]
> На сколько я вижу, это реализовано через редактирование сообщения, а не удаление

Да, я поклацал и тоже только сейчас обратил внимание. 
Но как понять какой именно сообщение редактировать?

**Comment by BoShurik** [comment]
https://core.telegram.org/bots/api#callbackquery

**Comment by xynobo** [comment]
Как я понимаю редактируем кнопку с помощью editMessageReplyMarkup, но как это отправить здесь никак не пойму. Подскажите?

**Comment by xynobo** [comment]
Сам разобрался :) кому надо 

$bot->callbackQuery(function ($callbackQuery) use ($bot) {
            $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup([
                [
                    ['text' => 'тест', 'callback_data' => 'tesssst'],
                ],
            ]
        );
$bot->editMessageReplyMarkup($callbackQuery->getMessage()->getChat()->getId(), $$callbackQuery->getMessage()->getMessageId(), $keyboard);

**Comment by teinrus** [comment]
> Здравствуйте, есть Inline клавиатура, нужно после выбора одной из кнопок удалить последнее сообщение с клавиатурой. Чтоб получился эффект, что на том же месте сформировался ответ на нажатие кнопки. Как подобное организовать?

    bot.edit_message_reply_markup(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=None)
    bot.send_message(chat_id=call.message.chat.id, text="Вы нажали кнопку 2")

**Comment by puriknike-pro** [comment]
NameError: name 'call' is not defined. Did you mean: 'all'?
