### ISSUE TITLE
Как обратится по имени с помощью бота?

### ISSUE THREAD

**Issue by alexempat** [TelegramBot/Api#199]
В файлах есть конструкция в файле **[User.php](https://github.com/TelegramBot/Api/blob/master/src/Types/User.php)**  такого типа:

`    public function getFirstName()`
  `  {
        return $this->firstName;
    }`

Могу ли я как-то использовать этот **firstName** или схожую функцию, чтобы ответить человеку по имени, или строить условия ссылаясь на результат ? 

Что-то в таком духе:

`$bot->command('start', function ($message) use ($bot) {`
 `$firstName= $this->firstName; // Тут условно нужно определить имя`
` $answer = 'Привет, ' . $firstName ; // И добавить его к фразе "Привет"`
 `$bot->sendMessage($message->getChat()->getId(), $answer);`
`});`
`

**Comment by TTATPuOT** [comment]
Переменная $firstName вы классе User является protected и получить её за пределами класса это или от него производных нельзя (подробнее: https://www.php.net/manual/ru/language.oop5.visibility.php ). Для того, чтобы получить имя есть функция, которую вы и скопировали - getFirstName() -она вернёт имя как раз таки и она уже public.

Далее,
При выполнении команды, вы в функцию получаете объект сообщения $message.
От $message уже можно найти пользователя:
`$user = $message->getFrom();` - https://github.com/TelegramBot/Api/blob/master/src/Types/Message.php
Далее, из пользователя (это как раз тот тип, которым вы интересуетесь) вы уже можете получить имя, фамилию и другие данные. Например:
`$firstName = $user->getFirstName();` - в переменную $firstName поместится имя
Ну и далее, можно это уже вставить в сообщение:
`$answer = "Привет, $firstName!";`
Ну или менее читаемо можно сделать в одну строку:
`$answer = 'Привет, ' . $user->getFirstName() . '!';`

Ну а дальше уже отправляете этот $answer через `$bot->sendMessage();`.
