### ISSUE TITLE
InvalidArgumentException when receiving document

### ISSUE THREAD

**Issue by achimha** [TelegramBot/Api#2]
Receiving a document/file using the current git code, throws an exception. It's hard to get by because the message remains available on the server.

#0 /var/www/telegram-bot/BaseType.php(76): TelegramBot\Api\BaseType::validate(Array)
#1 /var/www/dev_autorouter/libs/telegram-bot/BaseType.php(49): TelegramBot\Api\BaseType::fromResponse(Array)
#2 /var/www/telegram-bot/BaseType.php(78): TelegramBot\Api\BaseType->map(Array)
#3 /var/www/telegram-bot/BaseType.php(49): TelegramBot\Api\BaseType::fromResponse(Array)
#4 /var/www/telegram-bot/BaseType.php(78): TelegramBot\Api\BaseType->map(Array)
#5 /var/www/telegram-bot/BotApi.php(227): TelegramBot\Api\BaseType::fromResponse(Array)
#6 /var/www/libs/telegram_bot.php(62): TelegramBot\Api\BotApi->getUpdates(10278, 100, 10000)
#7 {main}

**Comment by iGusev** [comment]
Thanks!
