### ISSUE TITLE
exception TelegramBot\Api\InvalidArgumentException in BaseType.php:42

### ISSUE THREAD

**Issue by elraro** [TelegramBot/Api#20]
`exception 'TelegramBot\Api\InvalidArgumentException' in /home/elraro/privado/bots/apod/vendor/telegram-bot/api/src/BaseType.php:42
Stack trace:
#0 /home/elraro/privado/bots/apod/vendor/telegram-bot/api/src/BaseType.php(80): TelegramBot\Api\BaseType::validate(Array)
#1 /home/elraro/privado/bots/apod/vendor/telegram-bot/api/src/BotApi.php(306): TelegramBot\Api\BaseType::fromResponse(Array)
#2 /home/elraro/privado/bots/apod/apod.php(35): TelegramBot\Api\BotApi->sendMessage('@AstronomicPict...', 'Galaxies in the...')`

my source of the bot:

`require_once "vendor/autoload.php";
$bot->sendMessage("@AstronomicPictureoftheDay", $title."\n\n".$explation."\n\n".$url);

try {
$bot = new \TelegramBot\Api\BotApi('MYTOKEN');

} catch (\TelegramBot\Api\Exception $e) {
        echo $e;
        echo $e->getMessage();
}`

AstronomicPictureoftheDay is a public channel.

**Comment by iGusev** [comment]
Which version do you use?

**Comment by elraro** [comment]
Im using last version via "composer require telegram-bot/api"

**Comment by iGusev** [comment]
@elraro I found this bug. Thanks for report!

**Comment by POPSuL** [comment]
I upgrade this library to dev-master version 
```
% composer show -i                  
telegram-bot/api dev-master db7311b PHP Wrapper for Telegram Bot API
```
And this bug is not resolved.

```
Uncaught exception TelegramBot\Api\InvalidArgumentException:  in /telegram.bot/vendor/telegram-bot/api/src/BaseType.php on line 42

#1 /telegram.bot/vendor/telegram-bot/api/src/BotApi.php(306): TelegramBot\Api\BaseType::fromResponse(Array)
#2 /telegram.bot/src/Bot/Bot.php(71): TelegramBot\Api\BotApi->sendMessage('@SakhalinInfo', 'Test')
#3 /telegram.bot/src/Bot/Bot.php(101): SakhCom\Bot\Bot->sendUpdates()
#4 /telegram.bot/bot.php(37): SakhCom\Bot\Bot->start()
#5 {main}
```

**Comment by POPSuL** [comment]
I think this error occurs because field "from" from response is "optional".
In docs (https://core.telegram.org/bots/api#message):
```
from	User	 (Optional). Sender, can be empty for messages sent to channels
```
But in https://github.com/TelegramBot/Api/blob/master/src/Types/Message.php#L15 that field is required

**Comment by dvzzz** [comment]
https://github.com/TelegramBot/Api/issues/15

**Comment by iGusev** [comment]
fixed
