### ISSUE TITLE
Яндекс appmetrica

### ISSUE THREAD

**Issue by viktor02** [TelegramBot/Api#202]
Есть ли какой-либо детальный гайд по настройке? Как понять, что все подключилось? Вроде бы все добавил, но в аналитике пусто.
Если аппметрика больше не поддерживается, что можно использовать кроме неё?

**Comment by tridento** [comment]
попробуйте другую платформу, например botanalytics.co или dashbot.io или botlytics.co. я могу ошибаться, но аппметрика же вроде для приложений из официальных магазинов?

**Comment by viktor02** [comment]
> попробуйте другую платформу, например botanalytics.co или dashbot.io или botlytics.co. я могу ошибаться, но аппметрика же вроде для приложений из официальных магазинов?

Судя по этой [статье](https://habr.com/ru/company/yandex/blog/264121/) botan - проект яндекс.аппметрики для телеграм ботов. Судя по всему, уже мертвый. Спасибо за ссылки, посмотрю.

**Comment by viktor02** [comment]
В итоге подключил botlytics за пару минут. Благодарю.
