### ISSUE TITLE
InlineKeyboardMarkup - только http(s)?

### ISSUE THREAD

**Issue by viktor02** [TelegramBot/Api#204]
Почему нельзя отправить другой протокол в ссылке?        
         $textin = 'magnet:?xt=urn:btih:'.$row[1]; // Не работает
         $textin = 'http://'.$row[1]; // Работает
        
        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['text' => 'link', 'url' => $textin]
                ]
            ]
        );

**Comment by tridento** [comment]
вопрос к разработчикам телеграма, тут всё ясно написано: https://core.telegram.org/bots/api#inlinekeyboardbutton
