### ISSUE TITLE
Отправка фото из локальной папки

### ISSUE THREAD

**Issue by viktor02** [TelegramBot/Api#205]
$bot->sendPhoto($chatId, new CURLFile($filePath,'image/png','myImage.png'));
Этот пример советовали в предыдущих темах. Однако у меня он не работает. Мой код:

    $bot->sendPhoto($admin, new CURLFile(__DIR__.'/img/', 'image/png', 'file.png'));

Что я делаю не так?

**Comment by tridento** [comment]
не показываете код целиком

**Comment by TTATPuOT** [comment]
Что за $admin?
Да и в целом, как инициализируете $bot?

**Comment by viktor02** [comment]
Смысла показывать весь код нет, зависимостей от остального кода для отправки фото там только имя файла, которое берется из бд. Без sendPhoto всё прекрасно работает.
$admin = мой телеграм id.    

```php
$bot->on(function ($Update) use ($bot) {
        $message = $Update->getMessage();
        $msg_text = $message->getText();
        // Мой telegram id
        $admin = 361xxxx81;

        // Подключение к базе данных
        try {
            // Код с pdo пропущен.
            $text = "Текст";
            while($row = $sth->fetch()){
                if (!isset($row['id'])) {

                    $text = "Увы, но такого имени я еще не знаю.";
                    $bot->sendMessage($admin, $text, "markdown");
                } else{

                $bot->sendMessage($admin, $text, "markdown");

                $imgname = $row['photo_name'].'.png';
                $bot->sendPhoto($admin, new CURLFile(__DIR__.'/img/', 'image/png', $imgname));

                $bot->sendLocation($admin, $row['lat'], $row['long']);
                }

            }

            // Если введена команда
            if($msg_text{0} == '/'){
                $text = "Неизвестная команда. Введите /help";
                $bot->sendMessage( $admin, $text, "markdown");
            }

        } catch (PDOException $e) {
            echo $sth->errorInfo();
        }
    }, function () {
        return true;
    });
$bot->run();
```

**Comment by BoShurik** [comment]
https://www.php.net/curlfile
Первым параметром идет имя файла, а не директории. В третьем параметре передается не имя файла, а то под каким именем вы его будете передавать

**Comment by viktor02** [comment]
> 
> 
> https://www.php.net/curlfile
> Первым параметром идет имя файла, а не директории. В третьем параметре передается не имя файла, а то под каким именем вы его будете передавать

Благодарю, теперь работает. Но я немного не понял, как можно передавать файл, если он находится в другой папке? Например,
/img/file.png
bot.php

**Comment by POPSuL** [comment]
Например, не использовать ``__DIR__``, и указывать абсолютный путь к файлу...
