### ISSUE TITLE
Inline keyboard callback problem

### ISSUE THREAD

**Issue by juanmafer** [TelegramBot/Api#207]
Hi,
I want to make a callback using a inline keyboard. But when I press the button, the result is empty.
I dump the result via manual message to my telegram id and this is the content:
"object(TelegramBot\Api\Types\CallbackQuery)"

What could be the problem?

`<?php
require_once "vendor/autoload.php";

try {
    $bot = new \TelegramBot\Api\Client(BOT_API_KEY_XXXXXXXXXXXXXX);
    $bot->callbackQuery(function ($message) use ($bot) {
        ob_start();
		var_dump($message);
        $result = ob_get_clean();
		file_get_contents("https://api.telegram.org/BOT_API_KEY_XXXXXXX/sendmessage?chat_id=MI_CHAT_ID_XXXX&text=".$result);
    });

    $bot->command('hello', function ($message) use ($bot) {
        $answer = 'Touch the button';
        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup([[['text' => 'ping','callback_data'=>'op1']]]);
        $bot->sendMessage($message->getChat()->getId(), $answer, null, false, null, $keyboard);
    });
    $bot->run();

} catch (\TelegramBot\Api\Exception $e) {
    $e->getMessage();
}`

THX!

**Comment by Ramil001** [comment]
I have the same problem
