### ISSUE TITLE
telegram-bot/api/src/BotApi.php Line: 299

### ISSUE THREAD

**Issue by AkioSarkiz** [TelegramBot/Api#210]
Кто-то сталкивался с такой ошибкой?

**Comment by BoShurik** [comment]
`$bot->run();` должен запускаться в webhook'е, тогда телеграм присылает json с данными. Вы, скорее всего запустили эту команду в консоле, либо перешла на webhook-скрипт из браузера. В этих случаях `file_get_contents('php://input')` ничего не возвращает и вы получаете `InvalidJsonException`
