### ISSUE TITLE
Отправка нескольких сообщений в $bot->on()

### ISSUE THREAD

**Issue by kirill-gorbatyuk** [TelegramBot/Api#212]
Возникла необходимость отправки нескольких сообщений в функции on(), так как сообщение превышает разрешенное количество символов. С одним $bot->sendMessage(); работает отлично, но вот с 2+ бесконечная отправка происходит. Заранее спасибо за помощь!
**Пример:**
```
$bot->on(function ($Update) use ($bot) {
     $message = $Update->getMessage();
     $chatId = $message->getChat()->getId();
     $bot->sendMessage($chatId, 'OK1', 'HTML');
     $bot->sendMessage($chatId, 'OK2', 'HTML');           
}, function ($message) use ($bot) {
          return true;
}); 
$bot->run();
```

**Comment by tridento** [comment]
разбейте сообщение на части и используйте цикл

**Comment by kirill-gorbatyuk** [comment]
была такая задумка. Проблема в том, что сохранив в массив сообщения, они видны только в пределах функции on() Даже если объявить массив вне функции и попытаться его передать в on() 
**что то вроде такого:**
```
$allMessages = array();
$bot->on(function ($Update) use ($bot, $allMessages) {
     $message = $Update->getMessage();
     $chatId = $message->getChat()->getId();
     array_push($allMessages, 'OK1');
     array_push($allMessages, 'OK2');
     $bot->sendMessage($chatId, 'OK1', 'HTML');
     $bot->sendMessage($chatId, 'OK2', 'HTML');           
}, function ($message) use ($bot) {
          return true;
}); 
// и тут отсылать 
$bot->on(function ($Update) use ($bot, $allMessages) {
    foreach($allMessages as $mes) {
        $message = $Update->getMessage();
        $chatId = $message->getChat()->getId();
        $bot->sendMessage($chatId, $mes, 'HTML');
    }          
}, function ($message) use ($bot) {
          return true;
}); 

$bot->run();
```
**так вот массив $allMessages пустой!**

**Comment by BoShurik** [comment]
По ссылке передавай

**Comment by tridento** [comment]
конечно, вы же его инициализируете каждый раз. это вопрос уже не по данному фреймворку, а по уровню владения языком и утилитами :) можно хранить информацию для обмена между кусками кода в REDIS или memcached, можно использовать богопротивный global, можно, наконец, освоить работу с объектами в PHP (да, такое возможно). ну и вообще гуглите по словам php scope и познаете дзен.

**Comment by kirill-gorbatyuk** [comment]
Спасибо за ответы. Я вообще на java пишу ... тут пришлось на php)) так что извиняйте. Можете для примера кусок кода бросить ... буду очень благодарен! 
Про global слышал ... но читал, что не желательно использовать... поэтому не прибегал к этому способу.
**Для полноты:**
```
public function actionTest() {
$allMessages = array();
$bot->on(function ($Update) use ($bot, $allMessages) {
     $message = $Update->getMessage();
     $chatId = $message->getChat()->getId();
     array_push($allMessages, 'OK1');
     array_push($allMessages, 'OK2');
     $bot->sendMessage($chatId, 'OK1', 'HTML');
     $bot->sendMessage($chatId, 'OK2', 'HTML');           
}, function ($message) use ($bot) {
          return true;
}); 
// и тут отсылать 
$bot->on(function ($Update) use ($bot, $allMessages) {
    foreach($allMessages as $mes) {
        $message = $Update->getMessage();
        $chatId = $message->getChat()->getId();
        $bot->sendMessage($chatId, $mes, 'HTML');
    }          
}, function ($message) use ($bot) {
          return true;
}); 

$bot->run();
}
```
Разве в пхп $allMessages не будет виден во второй функции on()?

**Comment by BoShurik** [comment]
На само деле очень странно, что с 2+ `sendMessage` идет бесконечная отправка. Я так делал и у меня проблем не было. Можешь показать весь код полностью?

**Comment by tridento** [comment]
кстати, да, какая разница, сколько там sendMessage, хоть сотня. бесконечная отправка означает, что не возвращается 200, проблема может быть и в коде, и в сервере, код в студию

**Comment by kirill-gorbatyuk** [comment]
```
public function actionTest()
{
        $bot = new Client('токен');
        
        $bot->on(function ($Update) use ($bot) {
            $message = $Update->getMessage();
            $messageText = $message->getText();
            $chatId = $message->getChat()->getId();

            if (mb_stripos($messageText, "запрос") !== false) {
                
                $disconnections = ['сообщение1','сообщение2','сообщение3', 'сообщение4'];
                foreach ($disconnections as $disconnection) {
                    $bot->sendMessage($chatId, $disconnection, 'HTML');
                }
            }
            
            $keyboard = new ReplyKeyboardMarkup([[["text" => "Кнопка1"],["text" => "Кнопка2"]]], true, true);
            $bot->sendMessage($chatId, 'OK!', 'HTML', null, null, $keyboard);
            
        }, function ($message) use ($bot) {
            return true;
        });

        $bot->run();
}
```

**Comment by BoShurik** [comment]
Как "бесконечная отправка" проявляет себя? Вы получаете одно и тоже сообщение несколько раз или что?

**Comment by kirill-gorbatyuk** [comment]
всего должно отправится 8 сообщений. отправляются 3 и потом снова те же 3 сообщения до бесконечности. 
Начал смотреть в сторону подсказки tridento по поводу 200 кода. Возможно на 4 сообщении ломается что-то и он пробует заново отослать.... сейчас проверю!

**Comment by BoShurik** [comment]
Попробуйте отослать простое сообщение, потому что HTML в телеграме не полный и какие-то теги отправить нельзя

**Comment by kirill-gorbatyuk** [comment]
Спасибо всем огромное за помощь. Не обратил сразу внимание, что он на определенном сообщении ломается и думал, что одно и тоже сообщение шлет ... и полез в дебри. 
П.С. html теги в каждом сообщении были одинаковые (только текстовка менялась). Буду смотреть в сторону кривизны данных в бд. Возможно что то нагребло массивное и не влезло в максимум знаков!
