### ISSUE TITLE
Как сделать кнопки разного размера ?

### ISSUE THREAD

**Issue by Psazy** [TelegramBot/Api#213]
Не пойму как создать такие кнопки - 
![Screenshot_2019-07-04-05-34-37-471_org telegram messenger](https://user-images.githubusercontent.com/32399902/60636038-8985d380-9e1d-11e9-9f28-6ed62dff243b.png)
Кто нибудь поможет ?

**Comment by xynobo** [comment]
У меня так 
    $keyboard_balance = new \TelegramBot\Api\Types\ReplyKeyboardMarkup([
        [
            ["text" => "Кнопка 1"],
            ["text" => "Кнопка 2"],
            ["text" => "Кнопка 3"],
        ],
        [
            ["text" => "Кнопка 4"],
        ],
        [
            ["text" => "Кнопка 5"],
            ["text" => "Кнопка 6"],
            ["text" => "Кнопка 7"],
            ["text" => "Кнопка 8"],
        ],

    ], true, true);

**Comment by Psazy** [comment]
> У меня так
> $keyboard_balance = new \TelegramBot\Api\Types\ReplyKeyboardMarkup([
> [
> ["text" => "Кнопка 1"],
> ["text" => "Кнопка 2"],
> ["text" => "Кнопка 3"],
> ],
> [
> ["text" => "Кнопка 4"],
> ],
> [
> ["text" => "Кнопка 5"],
> ["text" => "Кнопка 6"],
> ["text" => "Кнопка 7"],
> ["text" => "Кнопка 8"],
> ],
> 
> ```
> ], true, true);
> ```
> 
> 1 массив 1 строка кнопок

У вас етсь Телеграмм ? МОжно вам там вопрос задать по поводу этой библиотеки (не про это)

**Comment by xynobo** [comment]
Есть, ник такой же
