### ISSUE TITLE
Photo get FileId's не работают

### ISSUE THREAD

**Issue by jenokizm** [TelegramBot/Api#219]
PHP Fatal error:  Uncaught Error: Call to a member function getBigFileId() on array
PHP Fatal error:  Uncaught Error: Call to a member function getSmallFileId() on array

так что вместе вызова этих методов приходится вручную из массива брать сразу большой так:
`getPhoto()[1]->getFileId();`

**Comment by BoShurik** [comment]
О каком из `getPhoto` идет речь? Он есть в `Chat` и в `Message`.

**Comment by BoShurik** [comment]
Ну вообще все согласно докам: 
https://core.telegram.org/bots/api#message 
> photo - Array of [PhotoSize](https://core.telegram.org/bots/api#photosize)

https://core.telegram.org/bots/api#chat

> photo - [ChatPhoto](https://core.telegram.org/bots/api#chatphoto)

`getBigFileId` и `getSmallFileId` доступны только в `ChatPhoto`, а вы, судя по всему, работаете с `Message`, где используется `PhotoSize`

**Comment by jenokizm** [comment]
Я про message.  Аа ну тогда все верно. Понятненько, спасибо)
