### ISSUE TITLE
Не отправляет сообщения. Ошибка

### ISSUE THREAD

**Issue by bubblegumoff** [TelegramBot/Api#222]
Ошибка при открытии страницы из браузера с кодом:

```
require_once "vendor/autoload.php";
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
$bot = new \TelegramBot\Api\BotApi('token');
$bot->sendMessage(123, "text");
```
Сама ошибка:

> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /var/www/cap/data/www/cap/tlgrm_bot/engine/vendor/telegram-bot/api/src/Types/Message.php on line 26

Не обрабатывает /start:
```
require_once "vendor/autoload.php";
try {
    $bot = new \TelegramBot\Api\Client('token');
    $bot->command('start', function ($message) use ($bot) {
        $bot->sendMessage($message->getChat()->getId(), 'pong!');
    });
    $bot->run();
} catch (\TelegramBot\Api\Exception $e) {
    $e->getMessage();
}
```
Успешно отправляет сообщения:
`file_get_contents("https://api.telegram.org/token/sendMessage?chat_id=123&text=123");`

**Comment by BoShurik** [comment]
У меня код из первой части (который из браузера) работает без проблем.

**Comment by bubblegumoff** [comment]
> У меня код из первой части (который из браузера) работает без проблем.

С этой проблемой разобрался. Поменял версию PHP. 

Не работает /start. А при открытии страницы через браузер выходит следующая ошибка:
`Fatal error: Call to undefined method TelegramBot\Api\BotApi::command() in /var/www/capperxr/data/www/capper-x.ru/tlgrm_bot/engine/bot.php on line 21`

**Comment by BoShurik** [comment]
1. В ошибке же написано, что у `BotApi` нет метода `command` (и его там действительно нет, он есть у `Client`)
2. Через браузер бот работать все равно не будет
