### ISSUE TITLE
Проблема с getText() on null

### ISSUE THREAD

**Issue by SkillKota** [TelegramBot/Api#225]
Uncaught Error: Call to a member function getText() on null in /home/c/ch92900/public_html/btctel/webhookbot.php:508\nStack trace:\n#0 [internal function]: {closure}(Object(TelegramBot\\Api\\Types\\Update))\n#1 /home/c/ch92900/public_html/btctel/vendor/telegram-bot/api/src/Events/Event.php(70): call_user_func(Object(Closure), Object(TelegramBot\\Api\\Types\\Update))\n#2 /home/c/ch92900/public_html/btctel/vendor/telegram-bot/api/src/Events/EventCollection.php(64): TelegramBot\\Api\\Events\\Event->executeAction(Object(TelegramBot\\Api\\Types\\Update))\n#3 /home/c/ch92900/public_html/btctel/vendor/telegram-bot/api/src/Client.php(122): TelegramBot\\Api\\Events\\EventCollection->handle(Object(TelegramBot\\Api\\Types\\Update))\n#4 /home/c/ch92900/public_html/btctel/vendor/telegram-bot/api/src/Client.php(135): TelegramBot\\Api\\Client->handle(Array)\n#5 /home/c/ch92900/public_html/btctel/webhookbot.php(1825): TelegramBot\\Api\\Client->run()\n#6 {main}\n  thrown in /home/c/ch92900/public_html/btctel/webhookbot.php on line 508
508 строка: это $msg_text = $message->getText();
Код:
`    $bot->on(function ($Update) use ($bot) {
        $message = $Update->getMessage();
        $msg_text = $message->getText();`

**Comment by bubblegumoff** [comment]
Проблема всё ещё актуальна. При отправке $Update->getMessage()->getText() пользователю приходит 0

**Comment by bubblegumoff** [comment]
@BoShurik тут приводился такой пример https://github.com/TelegramBot/Api/issues/176#issuecomment-453817651 . Как оказалось, он нерабочий. У меня стоит задача получить текст сообщения после нажатия на inline-keyboard

**Comment by BoShurik** [comment]
Что касается изначальной проблемы, то нужна проверка на message, т.к. его в адпейте может не быть: https://core.telegram.org/bots/api#getting-updates

**Comment by BoShurik** [comment]
@bubblegumoff по ссылке есть список доступных полей у апдейта. Не помню точно, вроде бы вам нужен `callback_query`
