### ISSUE TITLE
Как получить историю сообщений?

### ISSUE THREAD

**Issue by MikhailGennadevic** [TelegramBot/Api#235]
Как мне получить например 5 последних сообщений в чате?

**Comment by xynobo** [comment]
Никак, сохраняйте сообщения

**Comment by MikhailGennadevic** [comment]
https://core.telegram.org/method/messages.getHistory - а вот этим методом никак не воспользоваться?

**Comment by BoShurik** [comment]
Это не Bot API. Теоретически можете, но вам нужна другая [библиотека](https://github.com/danog/MadelineProto)
