### ISSUE TITLE
Connection timed out after 5001 milliseconds

### ISSUE THREAD

**Issue by AlexeyDanilov** [TelegramBot/Api#244]
Приветствую!
При использовании прокси очень часто стала возникать такая ошибка.
`$response = $bot->setProxy('socks5://148.153.11.58:39593')->getUpdates()`

Менял прокси на разные - одно и то же. С чем связано и как исправить? Буквально вчера всё работало. Таймаут тоже увеличил - не помогло.

**Comment by jenokizm** [comment]
У меня такое изредка происходит на сервере и без прокси. Кстати не на всех, такое на хостинге reg.ru но на beget.com не было
