### ISSUE TITLE
Корректное хранение сообщений в бд

### ISSUE THREAD

**Issue by jenokizm** [TelegramBot/Api#249]
Привет, я записываю в mysql бд сообщения от админов бота, которые потом рассылаются пользователям. Дело в том, что в сообщении могут быть иконки (смайлы), я пишу сообщение в поле типа TEXT utf8_general_ci и таким образом сообщения обрезаются в бд до первого смайла. По советам со стаковерфлоу я попробовал заменить кодировку поля на utf8mb4_general_ci это помогло лишь частично. Теперь сообщение не обрезается, даже видны некоторые простые смайлы, но часть смайлов заменяется на ????

Подскажите как быть?

**Comment by xynobo** [comment]
Когда из базы достаешь сообщения, не забудь кодировку также на utf8mb4 поменять, по умолчанию utf-8

**Comment by jenokizm** [comment]
@xynobo спасибо за идею, действительно я забыл про кодировку подключения. Но дело в том, что у меня база большая там много других данных, если я ее заменю все остальное поплывет к хренам. пожалуй лучше я буду хранить сообщения в текстовых файлах на диске)

**Comment by jenokizm** [comment]
блин случайно закрыл, если будут предложения если что пишите)
