### ISSUE TITLE
Как сделать, чтобы бот узнавал о заходе нового пользователя в чат?

### ISSUE THREAD

**Issue by DenisDangerous** [TelegramBot/Api#258]
Как сделать, чтобы бот узнавал о заходе нового пользователя в чат?

**Comment by TTATPuOT** [comment]
https://core.telegram.org/bots/api#setwebhook
Так же, как вы получаете сообщения из чата. Если кто-то вошёл в чат - это будет выглядить как сообщение с флагом `new_chat_members`: https://core.telegram.org/bots/api#message

**Comment by DenisDangerous** [comment]
> https://core.telegram.org/bots/api#setwebhook
> Так же, как вы получаете сообщения из чата. Если кто-то вошёл в чат - это будет выглядить как сообщение с флагом `new_chat_members`: https://core.telegram.org/bots/api#message

я делаю через  $bot->command('command', function ($message) use ($bot)
а как мне обрабатывать нового юзера без команды? On() пробовал - не работает

**Comment by DenisDangerous** [comment]
Как я понял мне тут надо параметры задать?


allowed_updates | Array of String | Optional | A JSON-serialized list of the update types you want your bot to  receive. For example, specify [“message”, “edited_channel_post”,  “callback_query”] to only receive updates of these types. See Update  for a complete list of available update types. Specify an empty list to  receive all updates regardless of type (default). If not specified, the  previous setting will be used.Please note that this parameter  doesn't affect updates created before the call to the setWebhook, so  unwanted updates may be received for a short period of time.
-- | -- | -- | --
 И что мне там указать чтобы из чатов он только события типа пользователь вошел\ушел и непосредственно команды мониторил, а не все сообщения
