### ISSUE TITLE
TelegramBot\Api\HttpException: Continue in 

### ISSUE THREAD

**Issue by DenisDangerous** [TelegramBot/Api#259]
Че за ошибка блин? Результат выглядит как будто он foreach мне 3 раза запускает

2020-05-22 08:57:39 [91.108.6.121][-][ae4faf6bcdd0e740b107cc1ddc6c4389][error][TelegramBot\Api\HttpException] TelegramBot\Api\HttpException: Continue in /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/BotApi.php:281
Stack trace:
#0 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/BotApi.php(258): TelegramBot\Api\BotApi::curlValidate(Resource id #6, false)
#1 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/BotApi.php(227): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/BotApi.php(1672): TelegramBot\Api\BotApi->call('sendMediaGroup', Array)
#3 [internal function]: TelegramBot\Api\BotApi->sendMediaGroup(-1001155620381, Object(TelegramBot\Api\Types\InputMedia\ArrayOfInputMedia))
#4 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array(Array, Array)
#5 /home/admin/web/bot.depneim.ru/public_html/controllers/TelegramController.php(115): TelegramBot\Api\Client->__call('sendMediaGroup', Array)
#6 [internal function]: app\controllers\TelegramController::app\controllers\{closure}(Object(TelegramBot\Api\Types\Message))
#7 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Client.php(172): ReflectionFunction->invokeArgs(Array)
#8 [internal function]: TelegramBot\Api\Client::TelegramBot\Api\{closure}(Object(TelegramBot\Api\Types\Update))
#9 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Events/Event.php(70): call_user_func(Object(Closure), Object(TelegramBot\Api\Types\Update))
#10 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Events/EventCollection.php(64): TelegramBot\Api\Events\Event->executeAction(Object(TelegramBot\Api\Types\Update))
#11 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Client.php(122): TelegramBot\Api\Events\EventCollection->handle(Object(TelegramBot\Api\Types\Update))
#12 /home/admin/web/bot.depneim.ru/public_html/vendor/telegram-bot/api/src/Client.php(135): TelegramBot\Api\Client->handle(Array)
#13 /home/admin/web/bot.depneim.ru/public_html/controllers/TelegramController.php(276): TelegramBot\Api\Client->run()
```

 foreach ($bikes AS $bike){
                    $media = new \TelegramBot\Api\Types\InputMedia\ArrayOfInputMedia();
                    $msg = $bike->id.'. '.$bike->name;
                    if ($bike->comment){
                        $msg.="\n\n".$bike->comment;
                    }
                    if($bike->photo_1){
                        $media->addItem(new \TelegramBot\Api\Types\InputMedia\InputMediaPhoto('https://bot.depneim.ru/web/img/'.$bike->photo_1, $msg));
                    }
                    if($bike->photo_2){
                        $media->addItem(new \TelegramBot\Api\Types\InputMedia\InputMediaPhoto('https://bot.depneim.ru/web/img/'.$bike->photo_2));
                    }
                    if($bike->photo_3){
                        $media->addItem(new \TelegramBot\Api\Types\InputMedia\InputMediaPhoto('https://bot.depneim.ru/web/img/'.$bike->photo_3));
                    }

                    $bot->sendMediaGroup($message->getChat()->getId(), $media);
                }
```

**Comment by hb220** [comment]
Попробуй так перед своими действиями:

$bot->setCurlOption(CURLOPT_HTTPHEADER, array('Expect:'));

Возможно, поможет, мне помогало.
