### ISSUE TITLE
Operation timed out after 5000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by ft525** [TelegramBot/Api#261]
As title, I got an error when I send a message by "sendMessage" method.
How do I solve this problem?

Following is detail.
Operation timed out after 5000 milliseconds with 0 bytes received at
vendor/telegram-bot/api/src/BotApi.php:260 (v2.3.13)

**Comment by spp28rus** [comment]
$api->setCurlOption(CURLOPT_TIMEOUT, 90);

**Comment by ft525** [comment]
> $api->setCurlOption(CURLOPT_TIMEOUT, $seconds);

I tried, but still the same.
I saw the PHP code, it can't overwrite the default value.
Just like following.

```php
// telegram-bot/api/src/BotApi.php (Call method)
$options = ['key' => 'default value'];
$custom_options = ['key' => 'new value'];

$options += $custom_options;
print_r($options);	// ['key' => 'default value'], it can't overwrite default value
```
