### ISSUE TITLE
Connection timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by diazJE** [TelegramBot/Api#262]
Hi, it appers to be throwing that error since saturday. Regarding the seconds i set the timeout it always throws that error..
 Is it possible that it is not allowing that many message per time? I dont think its blocked, because using curl from the command line i have no problems sending messages...

This works:
curl -s -X POST https://api.telegram.org/bot"xxxxxxxxxxxxxxxx"/sendMessage -d chat_id="xxxxxx" -d text="<a href=google.com>Example</a>" -d parse_mode=HTML

**Comment by MyZik** [comment]
https://github.com/TelegramBot/Api/issues/261 ?
