### ISSUE TITLE
Как отобразить InlineKeyboardMarkup в цикле?

### ISSUE THREAD

**Issue by LVM911** [TelegramBot/Api#267]
Ребятки привет, подскажите, как можно отобразить в цикле (['text' => 'link', 'url' => 'https://core.telegram.org'],)

$bot = new \TelegramBot\Api\BotApi('YOUR_BOT_API_TOKEN');

$keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
               1.     ['text' => 'link', 'url' => 'https://core.telegram.org'],
               2.    ['text' => 'link', 'url' => 'https://core.telegram.org'],
               N..    ['text' => 'link', 'url' => 'https://core.telegram.org']

                ]
            ]
        );
        
$bot->sendMessage($chatId, $messageText, null, false, null, $keyboard);

**Comment by codiflow** [comment]
I would initialize the variable outside of $keyboard and use array_push() to insert the values into it:
https://www.php.net/manual/de/function.array-push.php

**Comment by LVM911** [comment]
> I would initialize the variable outside of $keyboard and use array_push() to insert the values into it:

Спасибо, помогло!
вот код
		$array_keyboard = array();
		for ($x = 1; $x <= 7; $x++)
		 {
		    $array_keyboard[] = [["callback_data" => "keyboard_$x", "text" => "Кнопка; $x"]];
		 }
       	$inline_keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup($array_keyboard);
        $bot->sendMessage($message->getChat()->getId(), " Список кнопок от 1 до 7", false, null,null,$inline_keyboard);	  

![bf1f5cacef11e4a5b470714d35400464](https://user-images.githubusercontent.com/6534296/88478757-8511e880-cf53-11ea-94ab-30393aa2b573.png)
