### ISSUE TITLE
Как вместе с InlineKeyboardMarkup отправлять фото, видео, документ, аудио и др.

### ISSUE THREAD

**Issue by LVM911** [TelegramBot/Api#268]
Приветствую коллеги. 
Неполучается реализовать чтоб в одном сообщении можно было загружать так, как на картинке ниже ⬇️⬇️⬇️ 

![a84344929663bde287e72030b6b02af9](https://user-images.githubusercontent.com/6534296/89110403-f28daf80-d452-11ea-9946-69e5296e8d0d.png)

Для отправки текста этот код прекрасно работает

`			$keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
				[
					[

						['callback_data' => "all_message_planed", 'text' => '📆  Все запланированные'],
						['callback_data' => "all_message_sended", 'text' => '📪  Все отправленные'],							
	
					]
				]
			);
$bot->sendMessage($chat_id, "🏷 Текст, который будет над кнопками", false, null,null,$keyboard);	
`
Все работает только методом **sendMessage**
а нужно еще и этими (sendVoice, sendDocument, sendVideoNote, sendVideo, sendAudio, 

Как можно реализовать одновременную отправку фото, видео документа, круглого видео и инлайн клавиатуры внизу?

**Comment by MyZik** [comment]
Ну так у каждого из перечисленного тобой методов имеется параметр `reply_markup`. Вместо sendMessage используй `sendPhoto`, для отправки фотографии и прикрепляй туда свою клавиатуру, к вышеуказанному параметру.

**Comment by codiflow** [comment]
Keep in mind that sometimes the parameters are switched in their position so the reply_markup variable for sendPhoto is at position 5:

```
$chatId
$photo
$caption
$replyToMessageId
$replyMarkup
$disableNotification
$parseMode
```

for sendMessage() its at position 6:

```
$chatId
$text
$parseMode
$disablePreview
$replyToMessageId
$replyMarkup
$disableNotification
```

Just refer to the API documentation which you can generate using PHPDoc. Or just look into the file BotApi.php

**Comment by LVM911** [comment]
Спасибо ребята, помогло!
Для решения моей задачи поставил позицию  **replyMarkup** всегда на 6-е место у всех метдах ( sendVoice, sendDocument, sendVideoNote, sendVideo, sendAudio) в файле  BotApi.php.
Теперь скрипт выводит с БД разные типы файлов и может пркиреплять к нему кнопку

`			    $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup([[['callback_data' => "message_del=$message_id", 'text' => " ❌ Удалить сообщение "]]]); 
			    $bot->$type_messages($chat_id, "$message", false,null,null,$keyboard_del_message);	`	  

![Снимок экрана 2020-08-03 в 23 54 44](https://user-images.githubusercontent.com/6534296/89226609-e6395c00-d5e4-11ea-8629-7cde02ee17cf.png)

**Comment by xynobo** [comment]
Лучше всего, на мой взгляд, ставить на то же место, как описано в офф.документации. Так путаницы будет меньше в итоге

**Comment by codiflow** [comment]
Sure thats true but this means everybody updating to the version where this is "fixed" will have to edit their existing code fixing the positions there too. I think this shouldnt be done without any big notice on this.
