### ISSUE TITLE
Methods for API 2.0

### ISSUE THREAD

**Issue by riartem** [TelegramBot/Api#27]
Hi there! Will you planning to add new methods from bot api 2.0?

**Comment by iGusev** [comment]
Of course! In a few days it will be done

**Comment by wallysalami** [comment]
I'm waiting as well for the new 2.0 methods and types. Any progress?

**Comment by iGusev** [comment]
At the moment in `dev-master` implemented all methods and types, except `InlineQueryResultCached*`

**Comment by wallysalami** [comment]
Oh, I'm sorry! I was paying attention at stable releases, and also completely missed the `src/Types/Inline` folder at `dev-master`. Thanks!

**Comment by POPSuL** [comment]
What about support of InlineKeyboardMarkup and InlineKeyboardButton?

**Comment by m-derevyanko** [comment]
Where is the dev-master branch? I can't see it :( Can u please merge API 2.0 types with master?

**Comment by p30-port** [comment]
Can anyone give an example how to create and set InlineKeyboard?

**Comment by Bogdaan** [comment]
Still actual issue.

**Comment by igormukhingmailcom** [comment]
Still actual. `InlineKeyboardButton` not implemented. We should pass just arrays of arrays and this is a mess a bit... Could you please implement or share dev branch (can't find it on github) to contribute into. Thanks.

**Comment by iGusev** [comment]
Already released
