### ISSUE TITLE
Подскажите

### ISSUE THREAD

**Issue by SaxoBeatMos** [TelegramBot/Api#270]
Как можно перенести текст на кнопке

$keyboard[0][] = array("text" => "Тут длинный текст который не помещается на кнопке и который нужно перенести на новую строку", "callback_data" => "lesson");

**Comment by MyZik** [comment]
Никак, да и бессмысленно такие огромные кнопки делать, ты ломаешь принцип работы мессенджера.

**Comment by SaxoBeatMos** [comment]
спасибо за ответ
