### ISSUE TITLE
Как сделать кнопку sendContact?

### ISSUE THREAD

**Issue by L1keStyle** [TelegramBot/Api#272]
Как сделать кнопку sendContact?
Можно пример?

**Comment by MyZik** [comment]
Как-то так.

```php
$buttons = [
    ['text' => 'Send contact', 'request_contact' => true],
];
        
$replyMarkup = new ReplyKeyboardMarkup($buttons, true, false, true);
```

https://core.telegram.org/bots/api#replykeyboardmarkup

https://core.telegram.org/bots/api#keyboardbutton

**Comment by L1keStyle** [comment]
Не получаеться вот код:
```
$bot->command("getcontact", function ($message) use ($bot) {
            $buttons =
                [
                    ['text' => 'Send contact', 'request_contact' => true]
                ];

    $replyMarkup = new \TelegramBot\Api\Types\ReplyKeyboardMarkup($buttons, true, false, true);

	$bot->sendContact($message->getChat()->getId(), "Отправьте номер",$replyMarkup);
});
```
Выходят ошибки:
Fatal error:  Uncaught TelegramBot\Api\BadMethodCallException: Method getContact not exists in \vendor\telegram-bot\api\src\Client.php:407

**Comment by MyZik** [comment]
`$bot->sendMessage($chatId, "Отправьте номер", null, false, null, $keyboard);`

**Comment by MyZik** [comment]
@L1keStyle проблема решена?

**Comment by L1keStyle** [comment]
Спасибо

**Comment by CvekCoding** [comment]
Не знаю как раньше было, но сейчас Телеграм выдает ошибку:
Bad Request: field "keyboard" of the ReplyKeyboardMarkup must be an Array of Arrays.
Массив
```
            $buttons =
                [
                    ['text' => 'Send contact', 'request_contact' => true]
                ];
```
Преобразуется в массив объектов, а не в массив массивов как требует API

**Comment by Dioved** [comment]
Кнопку запроса телефона юзера у меня так получилось сделать:
```
$bot = new \TelegramBot\Api\Client($token);

// кнопка
$bot->command('phone', function ($message) use ($bot) {	
	$buttons =
		[[
			['text' => 'Отправить номер', 'request_contact' => true]
		]];
    $replyMarkup = new \TelegramBot\Api\Types\ReplyKeyboardMarkup($buttons, true, false, true);
    $bot->sendMessage($message->getChat()->getId(), 'Мы запомнили Ваш номер', null, false, null, $replyMarkup);
});

// получение номера
$bot->on(function (\TelegramBot\Api\Types\Update $update) use ($bot) {
	$message = $update->getMessage();
	$bot->sendMessage($message->getChat()->getId(), 'Your phone: ' . $message->getContact()->getPhoneNumber());	
}, function () {
	return true;
});
```

**Comment by snitko21** [comment]
I fixed your problem, your $replyMarkup stay in position attribute reply message id!
`// кнопка
$bot->command('phone', function ($message) use ($bot) {	
	$buttons =
		[[
			['text' => 'Отправить номер', 'request_contact' => true]
		]];
    $replyMarkup = new \TelegramBot\Api\Types\ReplyKeyboardMarkup($buttons, true, false, true);
    $bot->sendMessage($message->getChat()->getId(), 'Мы запомнили Ваш номер', null, false, null, null, $replyMarkup);
});`
