### ISSUE TITLE
field "input_message_content" must be of type Object

### ISSUE THREAD

**Issue by glavvred** [TelegramBot/Api#275]
am i doing something wrong?
just trying to send inline bot results, but getting this weird error.
input_message_content is in fact object type at least before answerInlineQuery

            $bot->InlineQuery(function ($query) use ($bot){
                //... get user code skipped
                    $photo = new Photo($user->id, $user->avatar, $user->avatar);
                    $imc = new InputMessageContent();
                    $imc->message_text = $user->id;
                    $photo->setInputMessageContent($imc);
                try {
                $bot->answerInlineQuery($query->getId(), $res);
                } catch (\TelegramBot\Api\Exception $exception){
                }
            });

**Comment by MyZik** [comment]
Текст ошибки какой?

**Comment by glavvred** [comment]
Bad Request: field "input_message_content" must be of type Object

> Текст ошибки какой?

**Comment by MyZik** [comment]
Ну так ты создаёщь пустой объект `InputMessageContent`. В документации чётко написано, что использовать нужно.

https://core.telegram.org/bots/api#inputmessagecontent

**Comment by glavvred** [comment]
да, но вроде как я его заполняю обязательным полем message_text?
или нужно сделать что то вроде 

use TelegramBot\Api\Types\Inline\InputMessageContent\Text;
$photo = new Photo($user->id, $user->avatar, $user->avatar);
$imc = new InputMessageContent();
$text = new Text('user.'.$user->id);
$imc->input_message_content = $text; 
или есть какой то метод для установки?

хоть какой то пример был бы очень полезен, тыкаюсь как слепой котенок (

**Comment by glavvred** [comment]
ну и да, в итоговом ответе вот так все выглядит
#inputMessageContent: TelegramBot\Api\Types\Inline\InputMessageContent {#1364
    +"input_message_text": TelegramBot\Api\Types\Inline\InputMessageContent\Text {#1398
      #messageText: TelegramBot\Api\Types\Inline\InputMessageContent\Text {#1398}
      #parseMode: null
      #disableWebPagePreview: true
    }
  }

**Comment by glavvred** [comment]
вроде подебил я эту штуку. 
`$bot->InlineQuery(function ($query) use ($bot){
                $users = app('App\Http\Controllers\UserController')->searchInline($query->getQuery());
                $res = [];
                foreach ($users as $user) {
                    $photo = new Photo($user->id, $user->avatar, $user->avatar);
                    /** @var Text $text */
                    $text = new Text('/rating '.$user->id);
                    $text->setDisableWebPagePreview(true);
                    $photo->setInputMessageContent($text);
                    $photo->setTitle($user->self_name ? $user->self_name : $user->name);

                    $res[] = $photo;
                }
                try {
                $bot->answerInlineQuery($query->getId(), $res);
                } catch (\TelegramBot\Api\Exception $exception){
                    $bot->sendMessage(386011, $exception->getMessage());
                }
            });`

похоже?

**Comment by MyZik** [comment]
<img width="299" alt="Bildschirmfoto 2020-08-28 um 22 57 58" src="https://user-images.githubusercontent.com/12817320/91614479-ed544f80-e981-11ea-8703-31cd5e8193fa.png">
Используй одно из этого, если тебе нужен текст, то `InputTextMessageContent`

**Comment by glavvred** [comment]
да, там импорт просто выше, не попал в пасту. спасибо!
