### ISSUE TITLE
Каким методом проверить, что пользователь отписался от бота?

### ISSUE THREAD

**Issue by LVM911** [TelegramBot/Api#276]
Здравствуйте, имеется база данных пользователей (chat_id), которые взаимодействовали  с
При попытке сделать рассылку (отписанным от бота chat_id) - скрипт зависает.
Скажите, каким методом можно проверить, подписан ди человек на бота имея его chat_id с ботом?

**Comment by MyZik** [comment]
В своём цикле (или где ты проходишь по таблице пользователей) перед отправкой сообщения проверяй, есть ли такой чат `getChat` или например, можешь `sendChatAction` использоватЬ.

**Comment by LVM911** [comment]
решил так
`try
				{
					$bot->$type_messages($chat_id, "$message_send", false,null,null,null);	 				
				}
				catch (\TelegramBot\Api\Exception $e)
				{
                                         // если человек отписан, тогда ловим ошибку.
					$e->getMessage();
				}         	
`

**Comment by MyZik** [comment]
Хорошее решение!
