### ISSUE TITLE
Обработка ответов на опрос

### ISSUE THREAD

**Issue by nikserg** [TelegramBot/Api#279]
Невозможно обработать сообщения вида
`{"update_id":283992816,"poll_answer":{"poll_id":"...","user":{"id":345228072,"is_bot":false,"first_name":"Nikita","username":"glndrwn","language_code":"ru"},"option_ids":[...]}}`

который отправляются Телеграмом, когда пользователь выбирает вариант в опросе.

**Comment by BoShurik** [comment]
Что за ошибка?

**Comment by nikserg** [comment]
@BoShurik  Никакой ошибки, просто эти данные не парсятся в Update.
Отправил pull request на эту тему: https://github.com/TelegramBot/Api/pull/280

**Comment by MyZik** [comment]
https://github.com/TelegramBot/Api/releases/tag/v2.3.17

**Comment by dasayapov** [comment]
Так не понял, как получить данные по результатам опроса? 
`$poll = $update->getMessage()->getPoll();`
Возвращает ошибку "Call to a member function getPoll() on null {"exception":"[object] (Error(code: 0): Call to a member function getPoll() on null at "

**Comment by MyZik** [comment]
@dasayapov что лежит в `$update->getMessage()`? Может быть, что твой объект пустой? :)

**Comment by dasayapov** [comment]
> @dasayapov что лежит в `$update->getMessage()`? Может быть, что твой объект пустой? :)

Может, но как получить результаты опроса? Пока сделал через file_get_contents, там все данные есть

**Comment by BoShurik** [comment]
https://core.telegram.org/bots/api#update
