### ISSUE TITLE
Прикрепление сообщения

### ISSUE THREAD

**Issue by paraddise** [TelegramBot/Api#283]
Здравствуйте, как можно отправить сообщение, чтобы оно было прикрепленно к будущему сообщения юзера, я так понял есть метод ``` Message.setPinnedMessage(Message) ```, если это он, то как его потом отправить?

**Comment by MyZik** [comment]
Не совсем понятно, что ты имеешь ввиду.

Пинить сообщения в канале (или группе) можно те, которые уже были отправлены. Нужно знать только ID сообщения.

**Comment by paraddise** [comment]
Видимо я хотел реализовать то, чего еще нет в телеграме, извините
