### ISSUE TITLE
Как отправить Стикер с помощью answerInlineQuery?

### ISSUE THREAD

**Issue by nikelanjelo** [TelegramBot/Api#285]
Подскажите пожалуйста как добавить стикеры в results функции answerInlineQuery, т.к. документацию я не нашел, а попытки не увенчались успехом даже с обычным текстом.

**Comment by MyZik** [comment]
Нельзя отправлять стикеры с помощью answerInlineQuery.

https://core.telegram.org/bots/api#inlinequeryresult

**Comment by nikelanjelo** [comment]
> Нельзя отправлять стикеры с помощью answerInlineQuery.
> 
> https://core.telegram.org/bots/api#inlinequeryresult

Тогда как объяснить это?
![IMG_5170](https://user-images.githubusercontent.com/71671343/93872142-66706980-fcd8-11ea-99b8-0ed87108b769.gif)

**Comment by MyZik** [comment]
@MyZik спасибо за пример, не заметил.

Это значит, что все типы `InlineQueryResultCached*` должны быть в репозиторий.

**Comment by nikelanjelo** [comment]
> @MyZik спасибо за пример, не заметил.
> 
> Это значит, что все типы `InlineQueryResultCached*` должны быть добавлены в репозиторий.

Да, я уже разобрался в этом и был вынужден изменить библиотеку не смотря на то, что уже так полюбил её в ней нет данных типов
