### ISSUE TITLE
How to send message based on text rather than command?

### ISSUE THREAD

**Issue by TheoKlein** [TelegramBot/Api#29]
Hello
As the title, I have tried your example to get the specific command and reply.
```php
$bot->command('ping', function ($message) use ($bot){
    $bot->sendMessage($message->getChat()->getId(), 'pong!');
});
```
But how can I send the message based on text rather than command?

**Comment by iGusev** [comment]
Via `\TelegramBot\Api\Client::on` you can catch any messages from users and react to them:
```php
/**
 * Use this method to add an event.
 * If second will return true (or if you are passed null instead of closure), first one will be executed.
 *
 * @param \Closure $event
 * @param \Closure|null $checker
 *
 * @return \TelegramBot\Api\Client
 */
public function on(Closure $event, Closure $checker = null)
{
    $this->events->add($event, $checker);

    return $this;
}
```
For example, to process each message, you can do:
```php
$bot->on(function($message) use ($bot){
        file_put_contents("1.txt", print_r($message,true));
}, function($message) use ($name){
 return true;
});
```
For processing command `$name` via `$action` closure you can use `\TelegramBot\Api\Client::command` or own code:
```php
$bot->on(function (Message $message) use ($action) {
    preg_match('/^\/([^\s@]+)(@\S+)?\s?(.*)$/', $message->getText(), $matches);

    if (isset($matches[3]) && !empty($matches[3])) {
        $parameters = str_getcsv($matches[3], chr(32));
    } else {
        $parameters = [];
    }

    array_unshift($parameters, $message);

    $action = new ReflectionFunction($action);

    if (count($parameters) >= $action->getNumberOfRequiredParameters()) {
        $action->invokeArgs($parameters);
    }

    return false;
},
    function (Message $message) use ($name) {
        if (!strlen($message->getText())) {
            return false;
        }

        preg_match('/^\/([^\s@]+)(@\S+)?\s?(.*)$/', $message->getText(), $matches);

        return !empty($matches) && $matches[1] == $name;
    }
);
```

**Comment by TheoKlein** [comment]
Thanks for your detailed answer!

**Comment by kooroshh** [comment]
> `$bot->on(function($message) use ($bot){
>         file_put_contents("1.txt", print_r($message,true));
> }, function($message) use ($name){
>  return true;
> });`
the type of the $message is not the Message , it's Update , if you want to process incoming messages your code should be something like this : 
` $bot->on(function(Update $update) use ($bot){
                $message = $update->getMessage();
                $content = $message->getText();
                file_put_contents('debug.txt',$content);
            }, function($message){
                return true;
            });`
