### ISSUE TITLE
не нашел getUpdates в доках

### ISSUE THREAD

**Issue by bringmetheaugust** [TelegramBot/Api#290]
бротаны, сестры..
решил поучиться *PhP* на ботах **->** остановился на вашей библиотеке **->** не нашел в доках и в экземпляре `TelegramBot\Api\Client` метода аля `getUpdates` для *long polling* (вебкухи пока не надо). 
кому не лень, пжлст, напишите как так случилось.
с Уважением

**Comment by TTATPuOT** [comment]
Client - это враппер класса BotApi, ищите нужные вам методы в нём: https://github.com/TelegramBot/Api/blob/5f40ba177e6d8f8bc832fff3278f2951123604c4/src/BotApi.php#L499
