### ISSUE TITLE
How to retrieve certain parameter in command?

### ISSUE THREAD

**Issue by eizil** [TelegramBot/Api#298]
Hi,

I want to use command with additional paramater.

for example /ping abc

how can I retrieve the abc using your script?

Thanks

**Comment by MyZik** [comment]
You should catch the user request from message with getText() method.

**Comment by MyZik** [comment]
Here is an example:

https://github.com/TelegramBot/Api/issues/278#issuecomment-684263179

**Comment by eizil** [comment]
> Here is an example:
> 
> [#278 (comment)](https://github.com/TelegramBot/Api/issues/278#issuecomment-684263179)

thank you very much
