### ISSUE TITLE
How to combine Media and text, and send as reply to message.

### ISSUE THREAD

**Issue by eizil** [TelegramBot/Api#299]
Hi,

i have problem combining media and text message. 

How can I send a reply to previous user command, and send it as a combination of media and text?

Thanks

**Comment by MyZik** [comment]
Hi, try to use this method:

https://core.telegram.org/bots/api#sendmediagroup

https://github.com/TelegramBot/Api/blob/3d75d0cf6fdf1c83f0f38af954551417e1d53114/src/BotApi.php#L1770

**Comment by eizil** [comment]
> Hi, try to use this method:
> 
> https://core.telegram.org/bots/api#sendmediagroup
> 
> https://github.com/TelegramBot/Api/blob/master/src/BotApi.php#L1770

thanks for the suggestion, but I couldn't get the media group to run if I want to combine it with normal text.

any idea how to achieve this?

**Comment by megaezz** [comment]
join to question

**Comment by MyZik** [comment]
@megaezz sendMediaGroup doesn't support a text...
