### ISSUE TITLE
Send photo with URL.

### ISSUE THREAD

**Issue by marituss** [TelegramBot/Api#30]
Hello sir,

I have images with URL like www.photo.com/image.png. How can I send the images with URL using sendPhoto() function ?

Thanks!

**Comment by iGusev** [comment]
Hello!

You cant send file via url. You can upload file content through POST or specify the ID of an already loaded file.

For example, you can download file via url and send to telegram api:
```php
$filePath = tempnam(sys_get_temp_dir(), 'tg_');
file_put_contents($filePath, file_get_contents('www.photo.com/image.png'));

$bot->sendPhoto($chatId, new CURLFile($filePath,'image/png','myImage.png'));

unlink($filePath);
```

**Comment by marituss** [comment]
Yeah ! That's why I have done already. Was just wondering of is there is any option.
Thanks you for reply. :)
