### ISSUE TITLE
Using is_integer breaks things on 32-bit systems

### ISSUE THREAD

**Issue by SergeAx** [TelegramBot/Api#31]
Today I've created a public channel with chat_id=-1001065544251. Posting to this channel via admin bot produces an exception:

**Type:** TelegramBot\Api\InvalidArgumentException
**File:** /var/www/safetext.me/vendor/telegram-bot/api/src/Types/Chat.php
**Line:** 92

I can confirm that `is_integer(-1001065544251) === false` on my system (Debian @ armv71). Developers on other 32-bit arm systems (like Raspberry Pi) or Windows 7 32-bit as local dev environment will have the same problem.

It is better to use `is_numeric()` in your case. Want me to do a PR?

**Comment by SergeAx** [comment]
Please do regression testing. I've seen something strange when casting these large numbers to strings, like "-1001065544251.0"

**Comment by vip9008** [comment]
there is also another issue regarding chat_id in general
according to the api docs you can also pass a channel name instead of an id like @some_channel
so its better to keep it as string.

**Comment by POPSuL** [comment]
@vip9008 support for channels added in this commit https://github.com/TelegramBot/Api/commit/db0c4c5633b8a11536ae4bdf1cbb7a21b3e0c6a1 (issue #23)
