### ISSUE TITLE
Как ортедактировать надписи кнопок? editMessageReplyMarkup?

### ISSUE THREAD

**Issue by AndreyBaratynskiy** [TelegramBot/Api#315]
Подскажите, пожалуйста, реализована ли возможность редактировать надписи на кнопках для организации пагинации?

**Comment by MyZik** [comment]
Да ты просто создаёшь новый объект `InlineKeyboardMarkup` и передаешь его в метод `editMessageReplyMarkup` третьим аргументом:

```php
$keyboard = new InlineKeyboardMarkup(...); // Заполнишь сам

$bot->editMessageReplyMarkup($chatId, $text, $keyboard);
```

**Comment by AndreyBaratynskiy** [comment]
Спасибо! Просто и понятно
