### ISSUE TITLE
Старт бота по реферальной ссылке

### ISSUE THREAD

**Issue by samnebudu** [TelegramBot/Api#317]
Возможно ли при передать $_GET параметры по ссылке.
Example: https://t.me/mybot?id=1234
И в боте принять $_GET['id']?

**Comment by MyZik** [comment]
Есть много способов, один из них, например:

```php
$text = 'https://t.me/YourBot?start=123456789'; // 
$args = explode('=', $text);

print_r($args[1]);
```

Выведет следующее:

```
123456789
```

**Comment by samnebudu** [comment]
Я имею ввиду когда через сам сайт телеграма ты запускаешь бота, и чтоб непосредсвтенно через команду старт 
$bot->command('start', function ($message) use ($bot) {
принять этот _GET параметр

**Comment by MyZik** [comment]
Я тебе и говорю, что кроме ?start= больше ничего передать нельзя. Открываешь ссылку https://t.me/YourBot?start=123456789, вырезаешь оттуда айди (или что тебе там нужно после ?start=) и работаешь с данными, код дан выше

**Comment by samnebudu** [comment]
понял, спасибо большое что ответил быстро 
сразу не понял, извини :)

**Comment by MyZik** [comment]
Ничего страшного, спрашивай ;)
