### ISSUE TITLE
А у в библиотеке есть встроенные инструменты для работы с бд?

### ISSUE THREAD

**Issue by maksutovnurda** [TelegramBot/Api#319]
А у в библиотеке есть встроенные инструменты для работы с базой данных?

**Comment by MyZik** [comment]
Нет, а зачем? Ты сам выбираешь любую БД (тот же MySQL, например), и работаешь с данными, которые тебе приходят от Telegram как ты хочешь.

**Comment by maksutovnurda** [comment]
Не я просто хотел узнать, есть ли встроенные инструменты, если есть зачем переписывать все. А если нет, то все напишу сам)
