### ISSUE TITLE
Значения sendDice

### ISSUE THREAD

**Issue by Albert2106** [TelegramBot/Api#320]
Можно как-нибудь отправить кость с заданным числом для выпадания?
И как сменить дефолтную кость на баскетбол и т.д.?
Мой пример смены на баскетбол 
`$bot->sendDice(1067885757,"🏀");` и он не работает

**Comment by MyZik** [comment]
> Можно как-нибудь отправить кость с заданным числом для выпадания?
Нет

> И как сменить дефолтную кость на баскетбол и т.д.?
Хм, нужно обновить метод, я займусь этим сегодня
