### ISSUE TITLE
How to use answerInlineQuery? can you give me an example?

### ISSUE THREAD

**Issue by ihorBielovol** [TelegramBot/Api#325]
How to use answerInlineQuery? can you give me an example?

![Screenshot from 2021-03-25 11-52-51](https://user-images.githubusercontent.com/24429242/112453958-de3f4f80-8d60-11eb-80f0-405d934d1938.png)

![Screenshot from 2021-03-25 11-53-43](https://user-images.githubusercontent.com/24429242/112453960-df707c80-8d60-11eb-96e4-a0a9bbdaba6b.png)

**Comment by artprodev** [comment]
$bot->inlineQuery(function($update) use ($bot){
            $content = new Text('artpro.dev', 'html');
            $result = new Article(time(),'Title', 'description',null,null,null, $content);
            $bot->answerInlineQuery($update->getId(), [$result]);

            $bot->sendMessage($update->getId(), $update->getid().$update->getQuery());
        });
