### ISSUE TITLE
Fatal error: Uncaught Error: Class 'TelegramBot\Api\Client' not found in 

### ISSUE THREAD

**Issue by Albert2106** [TelegramBot/Api#345]
`Fatal error: Uncaught TelegramBot\Api\HttpException: Bad Request: bad webhook: Failed to resolve host: Name or service not known in /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/BotApi.php:286 Stack trace: #0 /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/BotApi.php(263): TelegramBot\Api\BotApi::curlValidate() #1 /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/BotApi.php(232): TelegramBot\Api\BotApi->executeCurl() #2 /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/BotApi.php(486): TelegramBot\Api\BotApi->call() #3 [internal function]: TelegramBot\Api\BotApi->setWebhook() #4 /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array() #5 /var/opt/list/public/telegram-bot-albert2106/index.php(44): TelegramBot\Api\Client->__call() #6 {main} thrown in /var/opt/list/public/telegram-bot-albert2106/vendor/telegram-bot/api/src/BotApi.php on line 286`

**Comment by Albert2106** [comment]
php 7.4

**Comment by BoShurik** [comment]
`Bad Request: bad webhook: Failed to resolve host: Name or service not known`

**Comment by Albert2106** [comment]
> `Bad Request: bad webhook: Failed to resolve host: Name or service not known`

Знаю. Так и не нашел ответа. Впервые столкнулся с этим . Не знаешь как зафиксить ?
