### ISSUE TITLE
sending a file as multipart/form-data

### ISSUE THREAD

**Issue by vip9008** [TelegramBot/Api#35]
I ran into this problem
when sending a file as an inputFile instead of string - according to api docs (file_id as String to resend a photo that is already on the Telegram servers)
it wont work and generates an error.

and after a lot of reading and digging I finally found the problem.
simply the option of "multipart/form-data" is not passed to curl_setopt_array() inside the function call()
I think this option should be added to any api call that can send files.

**Comment by POPSuL** [comment]
If you want to send a new file, you are should use an object of `\CURLFile` instead of string (for `file_id`).

I've code like that:
```php
$file = new \CURLFile($pathToImage, 'image/jpeg', 'image.jpg');
$this->sendPhoto($dstChatId, $file, $imageCaption);
```
and this works properly without adding multipart/form-data.

**Comment by vip9008** [comment]
I tried \CURLFile and it didnt work without adding multipart/form-data
But also maybe I did something wrong
Thanks for the hint

**Comment by vip9008** [comment]
I passed only the file path to \CURLFile
Could this be the problem?

**Comment by POPSuL** [comment]
@vip9008 also, I'm use a dev-master version. Maybe in stable version somethings went wrong =)

>> I passed only the file path to \CURLFile\

maybe. Try to add a mime-type and real filename. Maybe telegram on the server-side checks the file mime-type (which curl probably can send as application/octet-stream)

**Comment by achimha** [comment]
Works fine for me:

```
                        $file = new \CURLFile($image);
                        try
                        {
                            $bot->sendPhoto($chat->getId(), $file);
                        }
                        catch (HttpException $e)
                        {
                            botLog("SendPhoto failed!\n");
                            botLog($e->getMessage() . PHP_EOL . $e->getTraceAsString() . PHP_EOL);
                            $bot->sendMessage($chat->getId(), "Could not send the image due to a problem with the Telegram server infrastructure. Sorry.");
                        }
                        catch (Exception $e)
                        {
                            botLog("SendPhoto failed!\n");
                            botLog($e->getMessage() . PHP_EOL . $e->getTraceAsString() . PHP_EOL);

                        }
```

Make sure it's a supported file format.

**Comment by vip9008** [comment]
I will try these things later and make sure
Thanks

**Comment by POPSuL** [comment]
Also, as proof I can show the channel https://telegram.me/SakhalinInfo (in Russian) in which I send the images with code like that I showed above. All works fine!

**Comment by vip9008** [comment]
Ok appearantly it was a problem with the file path it self
Ive tested my code with your suggestions and its working good
Thanks for the help
