### ISSUE TITLE
resize_keyboard don't working

### ISSUE THREAD

**Issue by lairen213** [TelegramBot/Api#354]
Hi! I have some problem, I need the text in the buttons to be fully displayed, for this I use resize_keyboard - but it does not work (regardless of whether it is false or true).

<img width="681" alt="Снимок экрана 2021-11-17 в 01 29 44" src="https://user-images.githubusercontent.com/51814398/142082590-96df88c2-dc66-4191-81bc-efb68021850d.png">

<img width="381" alt="Снимок экрана 2021-11-17 в 01 28 28" src="https://user-images.githubusercontent.com/51814398/142082443-16e2ed7e-7c89-46ec-ad07-875f69c1f13d.png">

**Comment by Ramil001** [comment]
$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(
                                    array(
                                        array("◀️ Повернутись назад"),
                                    )
                                    , true, $resizeKeyboard = true);
                                
                                $bot->sendMessage($id,$mes, null, false, null, $keyboard);
