### ISSUE TITLE
Нет возможности удалить ожидающие обновления при установке/удалении хука

### ISSUE THREAD

**Issue by theAngriestman** [TelegramBot/Api#361]
В методе установки и удаления веб хука есть параметр drop_pending_updates, который очищает очередь обновлений.
Было бы отлично, если бы его добавили в методы setWebhook и deleteWebhook как необязательный параметр
https://core.telegram.org/bots/api#setwebhook

**Comment by psylosss** [comment]
as a temporary 
`$bot->call('setWebhook', ['url' => $webhookUrl, 'allowed_updates' => $allowedUpdates]);`
