### ISSUE TITLE
Зацикливание ответов при долгом выполнении команды

### ISSUE THREAD

**Issue by Dedushkes** [TelegramBot/Api#366]
Для воспроизведение проблемы можно использовать функцию 

```
		$bot->command('test', function ($message) use ($bot) 
		{
			$userid = $message->getChat()->getId();
					
			sleep(300);
					
			$bot->sendMessage($userid, "TEST");
		});
```

В таком случае после отправки команды /test телеграм начинает присылать event с одним и тем же update_id чем вызывает обработку функции снова и снова

**Comment by uristA** [comment]
так и не решили проблему ?

**Comment by thorn2301** [comment]
А это не проблема и её не надо решать.
Таймаут срабатывает не у библиотеки, а у API телеграм.
Можно просто первой командой скрипту передать fastcgi_finish_request();

Например если:
```
$bot->command('test', function ($message) use ($bot) 
		{
			$userid = $message->getChat()->getId();
                        fastcgi_finish_request();
					
			sleep(300);
					
			$bot->sendMessage($userid, "TEST");
		});

```

то все отработает единожды

**Comment by Dedushkes** [comment]
So fastcgi_finish_request is good solution if u have defined fastcgi_finish_request function, but if u not have it (its me) u can use this code to do same wihtout fastcgi_finish_request function:

```
			http_response_code(200);
			ignore_user_abort(true);
			header("Content-Length: 0");
			header("Connection: Close");
			flush();
			session_write_close();
```
