### ISSUE TITLE
ReplyKeyboardMarkup fails with PHP7

### ISSUE THREAD

**Issue by OpenGrid** [TelegramBot/Api#39]
PHP Notice:  Object of class TelegramBot\Api\Types\ReplyKeyboardMarkup could not be converted to int in /telegram-bot/api/src/BotApi.php on line 304

**Comment by YannickFricke** [comment]
@OpenGrid whats your code?

**Comment by atdtn** [comment]
PHP 5.6 the same error

"PHP message: PHP Notice:  Object of class TelegramBot\Api\Types\ReplyKeyboardMarkup could not be converted to int

Code:

    $bot->command('help', function ($message) use ($bot) {
        $text = "Help text";
        $keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(array(array("one", "two", "three")), true); 
        $bot->sendMessage($message->getChat()->getId(), $text, false, null, $keyboard);
    });

**Comment by igormukhingmailcom** [comment]
@atdtn Your `$keyboard` passed as `$replyToMessageId` parameter.
You should pass like this:
```
$bot->sendMessage($message->getChat()->getId(), $text, 'markdown', false, null, $keyboard);
```

PS: New PhpStorm (2017 version) show which parameters you passing. Very useful feature. Just FYI.
