### ISSUE TITLE
how to add InlineKeyboardButton?

### ISSUE THREAD

**Issue by ahmadnazari73** [TelegramBot/Api#391]
i want to create 3 button As below
but inline keyboard create it side by side!

sample: https://paste.pics/d7264e1ac198d8e304272c9791942c34

**Comment by sapeg-in** [comment]
$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup([["button one"], ["button two"]], true);

**Comment by ahmadnazari73** [comment]
thank. 
its working.
