### ISSUE TITLE
Handle non JSON exceptions

### ISSUE THREAD

**Issue by achimha** [TelegramBot/Api#4]
I just had the issue with a non working Telegram server that sent back errors on every sendPhoto call. The HTTP server did not return a JSON structure but just:

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

In this case I had no access to the error data with the API because it would only return JSON fields. I think the easiest fix would be to test if the fields are present and if not, use the whole response as the error string.

**Comment by iGusev** [comment]
Could you show the example code?

**Comment by achimha** [comment]
This is just an example. It happens every now and then when there is a problem with the Telegram server infrastructure. You can google for "502 Bad Gateway Telegram BOT" and will find some hits. In general, you assume that you get a well formed JSON response to every HTTP request to the JSON server. In case you don't an exception is thrown but all information about the error (HTTP code + error message) is lost.

I suggest you test for malformed JSON and then return the complete HTTP body.

**Comment by achimha** [comment]
Here's an example of such a server error:

$ curl -s -X POST https://api.telegram.org/bot<token>/sendPhoto -F chat_id=<chatid> -F photo="@/tmp/image.png"
`<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>`

**Comment by iGusev** [comment]
Done. Thanks!

**Comment by achimha** [comment]
Thank you, that helps.

Note that there is still a hypothetical case that you do not get back well formed JSON. In this case an exception is thrown but the error information is lost.
