### ISSUE TITLE
Fatal error: Uncaught exception 'TelegramBot\Api\InvalidArgumentException'

### ISSUE THREAD

**Issue by YannickFricke** [TelegramBot/Api#41]
Call Stack:
    0.0010     127632   1. {main}() G:\Referenzen\NitradoForumToTelegramBot\index.php:0
    0.0100     528640   2. TelegramBot\Api\BotApi->getUpdates() G:\Referenzen\NitradoForumToTelegramBot\index.php:9 // there i call getUpdates(0)
    1.2441     537432   3. TelegramBot\Api\Types\ArrayOfUpdates::fromResponse() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BotApi.php:408
    1.2451     560272   4. TelegramBot\Api\BaseType::fromResponse() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\Types\ArrayOfUpdates.php:11
    1.2461     560504   5. TelegramBot\Api\BaseType->map() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:82
    1.2461     609440   6. TelegramBot\Api\BaseType::fromResponse() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:53
    1.2461     610528   7. TelegramBot\Api\BaseType->map() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:82
    1.2481     634168   8. TelegramBot\Api\BaseType::fromResponse() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:53
    1.2481     634496   9. TelegramBot\Api\BaseType->map() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:82
    1.2481     634616  10. TelegramBot\Api\Types\Chat->setId() G:\Referenzen\NitradoForumToTelegramBot\vendor\telegram-bot\api\src\BaseType.php:51

JSON:

{
            "update_id": 804548074,
            "message": {
                "message_id": 1,
                "from": {
                    censored
                },
                "chat": {
                    "id": censored,
                    "title": "Nitrado Forum Updates",
                    "type": "supergroup"
                },
                "date": 1471098599,
                "migrate_from_chat_id": censored
            }

array(3) {
      'id' =>
      double(-1001072087709)

Thats why is_int fails

**Comment by YannickFricke** [comment]
@iGusev can you take a look please? :)

**Comment by YaroslavMolchan** [comment]
I think it was fixed, too old issue
