### ISSUE TITLE
http post/get of other server when command is parsed

### ISSUE THREAD

**Issue by journey6** [TelegramBot/Api#43]
I want to execute simple http get or post when a command is parsed from user
the link of get page is on another server on raspberry pi computer with public ip and dns name

sending message works fine 
here is my code

`$bot->command('pi', function ($message) use ($bot) {`
`file_get_contents("http://1.2.3.4/test.php");`

`$bot->run();`

file_get_content does not execute the get command

**Comment by YannickFricke** [comment]
@journey6 maybe your server settings disallow file_get_contents from URL?

Take a look in your php.ini
