### ISSUE TITLE
Allow to use `attach://<file_attach_name>` syntax inside sendMediaGroup

### ISSUE THREAD

**Issue by BoShurik** [TelegramBot/Api#432]
From https://github.com/TelegramBot/Api/issues/430#issuecomment-1562554769 

/cc @galeoner

**Comment by galeoner** [comment]
Don't give me a fish, give me a fishing rod. It is not joke. I'm serious.

**Comment by BoShurik** [comment]
Now it's not possible, I'll try to do it this week

**Comment by galeoner** [comment]
Thanks!
