### ISSUE TITLE
Аналог onReplyToMessage

### ISSUE THREAD

**Issue by L11R** [TelegramBot/Api#44]
В библиотеке для NodeJS [есть замечательный метод](https://github.com/yagop/node-telegram-bot-api#TelegramBot+onReplyToMessage) , позволяющий делать целые цепочки "вопрос-ответ" без использования БД. Можно ли это реализовать и здесь?

**Comment by riartem** [comment]
```
$message = $update->getMessage();
if($message->getReplyToMessage() !== null){
    // 
    return;
}
```
