### ISSUE TITLE
Creating a Channel Invite Link with a Bot

### ISSUE THREAD

**Issue by mehmetsarr** [TelegramBot/Api#447]
Below I am commanding my bot to create an invite link on my channel, but '' Call to undefined method TelegramBot\Api\BotApi::createChatInviteLink() '' gives an error.
How can I solve this problem?

'''
public function createInviteLink()
    {
	$botToken = '6342178492:AAHwotX0jBFDVOqRtwSlr6vnVrmtUPZQgAA';    
	$bot = new \TelegramBot\Api\BotApi($botToken);
	
	 $hyphen = '-';
	 $number = '100';
	 $channel =  '1942493354';
	 
     $chatId = $hyphen.$number.$channel;
	 
        $result = $bot->createChatInviteLink($chatId, [
            'expire_date' => time() + 3600, 
            'member_limit' => 10, 
        ]);
        if ($result) {
            echo "Invite Link: " .  $inviteLink->getInviteLink();
        } else {
            echo "Failed to create invite link.";
        }
	 
     
    }
'''

**Comment by BoShurik** [comment]
Hello! Unfortunately, this method not implemented yet. Can you make a PR with it?

**Comment by mehmetsarr** [comment]
> Hello! Unfortunately, this method not implemented yet. Can you make a PR with it?

Unfortunately I couldn't.

**Comment by mehmetsarr** [comment]
> Hello! Unfortunately, this method not implemented yet. Can you make a PR with it?

Nasıl yapabiliriz.

**Comment by mehmetsarr** [comment]
I found the solution. I downloaded the Telegram API directly without using the library.

**Comment by BoShurik** [comment]
It's implemented in #449 , but you need to use `dev-master` version
