### ISSUE TITLE
Syntax error in BotApi.php on line 271

### ISSUE THREAD

**Issue by fernandoval** [TelegramBot/Api#45]
Parse Error: Syntax error in /var/www/project/system/vendor/telegram-bot/api/src/BotApi.php on line 271

Any idea?

PHP 7.0.8

**Comment by BoShurik** [comment]
What version of php and library you use?

**Comment by fernandoval** [comment]
Forget. Telegram was out for South America.

Error was timeout. Then a JSON_ERROR_SYNTAX was throwed.
