### ISSUE TITLE
Внезапно перестали работать БОТы

### ISSUE THREAD

**Issue by ArtZorrr** [TelegramBot/Api#461]
Доброго дня! Сегодня (16.01.2024 ) утром перестали "отвечать" все БОты. Реакции никакой. Токен на одном из них менял - безуспешно, библиотеку обновил до версии 2.5.0 - безуспешно. Хостер говорит что никаких блокировок с их стороны нет.
Так же хостер ответил что последние post-запросы с ip 91.108.6.125 ( если верить Яше это Телеграм ) поступали в 3:09 утра, и более никаких запросов не было...

Информация: БОТы лежат на одном домене, в разных подпапках ...

Подскажите, что делать?

p/s/ Зарегил нового БОТа - не работает, переношу на другой хостинг - все отлично ... Ушел пинать хостера ...

**Comment by BoShurik** [comment]
Проверьте, работает ли long polling (запросите обновления напрямую, а не через веб-хук)

**Comment by ArtZorrr** [comment]
Все заработало, причем на старой версии библиотеки, видимо был глюк со стороны телеги... Всем спасибо !
