### ISSUE TITLE
Как получить ID отправленного сообщения и ID чата 

### ISSUE THREAD

**Issue by ArtZorrr** [TelegramBot/Api#462]
Как мне получить ID сообщения и ID чата при отправке сообщения, для последующего его удаления?

Отправляю стандартно:

$bot->sendMessage($message->getChat()->getId(), "Текст сообщения", "html", true, null, $keyboard);

, ну или подскажите как правильно удалять сообщения по прошествии некоторого времени.

Спасибо!

**Comment by BoShurik** [comment]
```php
$message = $bot->sendMessage($message->getChat()->getId(), "Текст сообщения", "html", true, null, $keyboard);

$message->getMessageId();
$message->getFrom();
$message->getSenderChat();
```

**Comment by ArtZorrr** [comment]
> ```
> $message = $bot->sendMessage($message->getChat()->getId(), "Текст сообщения", "html", true, null, $keyboard);
> 
> $message->getMessageId();
> $message->getFrom();
> $message->getSenderChat();
> ```

а можно для тех кто " не силен " ... 
как переменной $idchat присвоить значение чата, куда улетело сообщение, а $idmessage значение id сообщения ... Спасибо!!!

**Comment by BoShurik** [comment]
```php
$idmessage = $message->getMessageId();
$idchat = $message->getChat();
```

**Comment by ArtZorrr** [comment]
> ```
> $idmessage = $message->getMessageId();
> $idchat = $message->getChat();
> ```

видимо я не правильно выразился ....

попробую ще раз...

я отправляю в чат некое сообщение, БОТ на него реагирует ответом, вот id ответа БОТа мне и нужно ...

**Comment by BoShurik** [comment]
Это именно то, что вы просили

**Comment by ArtZorrr** [comment]
> Это именно то, что вы просили

хм, тогда не пойму как это использовать ... пытаюсь внести в базу эти данные, ничего не выходит ...

**Comment by BoShurik** [comment]
С этим, увы, помочь не могу

**Comment by ArtZorrr** [comment]
> getFrom()

проверил, таким способом я могу только отправленные мною сообщения в чат "зафиксировать"
