### ISSUE TITLE
Add a Compatibility Table 

### ISSUE THREAD

**Issue by bernard-ng** [TelegramBot/Api#468]
In order to be up to date with the latest telegram API updates and different changes, I propose to add a compatibility table between the version of this library and the telegram API support version.

This will not only make future contributions easier but will also give a clear overview of the features already supported by this client.

I'm willing to invest a little time to bring the library up to date, Tell me what you think @BoShurik  

## Exemple 

| Library version | Bot API version |
|-----------------|-----------------|
| 1.0.0           | 2.1             |
| 2.0.1           | 2.2             |
| 3.0.2           | 2.3             |

**Comment by BoShurik** [comment]
Hello! Sorry for late reply

I'm not sure table worth it, because users can't lower Bot API version, so the latest version is only version they have. But a note about latest supported version in README / CHANGELOG is good to have
