### ISSUE TITLE
Problem sending to business account

### ISSUE THREAD

**Issue by woodholly** [TelegramBot/Api#490]
After receiving a chat_id from a personal account, I can send messages to it. However, after receiving a chat_id from a business account, I can send messages, but messages do not reach it, why?

**Comment by bernard-ng** [comment]
Do you have any error message ?

**Comment by woodholly** [comment]
No, it doesn't trigger any exception.
```
$res = Request::sendMessage($data);
```
How to check $res status ?

**Comment by bernard-ng** [comment]
Can you dump it ? Var_dump or dd

**Comment by woodholly** [comment]
I'v managed to get error message upon sending to business account:
```
Request data: Array (     [chat_id] => 21474xxxxx     [text] => "test message" )
```
```
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
```
But chat_id is correct and stored from from user's /start activation session.
Everything works with ordinal user accounts, code is the same. Why it fails with business accounts ?
Can please other developers test it too?

**Comment by woodholly** [comment]
Ok I think I know why this happens. This is how /start message processed:
```
$message    = $this->getMessage();
$chat_id    = $message->getChat()->getId();
```
var_dump($message):
```
{"Longman\\TelegramBot\\Entities\\Message":{"message_id":x27,"from":{"id":72039xxxxx,"is_bot"
:false,"first_name":"xxxxxxxxxxxxxxxs","last_name":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","username":"xxxxxxxxxxxxxxxxxxx","language_code":"ru"},"chat":{"id":72039xxxx","first_name":"xxxxxxxxxxxxxxxx","last_name":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","username":"xxxxxxxxxxxxxxxxxxx","type":"private"},"date":17314xxxxx,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}
```
And $message->getChat()->getId() returns 214748xxxx (invalid id), but should return 72039xxxx

**Comment by woodholly** [comment]
One more thing:
```
$message    = $this->getMessage();
$from       = $message->getFrom();
$user_id    = $from->getId();
$chat_id    = $message->getChat()->getId();
```
For non-business accounts: $user_id==$chat_id, always!
But for business accounts they differ.

**Comment by woodholly** [comment]
Nevermind, this was mysql int(11) overflow bug. chat_id > int(11).
