### ISSUE TITLE
Give an example of InlineKeyboard

### ISSUE THREAD

**Issue by uSS212** [TelegramBot/Api#50]
Can anyone gives an example of creating InlineKeyboard with this SDK?

**Comment by igormukhingmailcom** [comment]
Looks like this not fully implemented as far as I can't find `callback_query` here in repo (this is key of `Update` payload that receiving by webhook after pressing `InlineKeyboard` button): 
https://github.com/TelegramBot/Api/search?utf8=%E2%9C%93&q=callback_query

**Comment by YaroslavMolchan** [comment]
Something like this:
$bot = new \TelegramBot\Api\BotApi('YOUR_BOT_API_TOKEN');

```
$keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['switch_inline_query_current_chat' => '/answer', 'text' => 'Answer']
                ]
            ]
        );
```

$bot->sendMessage($chatId, $messageText, false, null, $keyboard);

All options you can see here: https://core.telegram.org/bots/api#inlinekeyboardbutton
