### ISSUE TITLE
How to receive messages without a slash?

### ISSUE THREAD

**Issue by bart02** [TelegramBot/Api#53]
I want to make a bot from all posts, even those that do not "/command". How to do it with this library.

**Comment by BoShurik** [comment]
You need to get updates manually and work with them
https://github.com/TelegramBot/Api/blob/master/src/BotApi.php#L447

**Comment by mir-arduino** [comment]
But I use WebHook. And method Client.

**Comment by p30-port** [comment]
See this issue #29
