### ISSUE TITLE
Как обрабатывать callback вызовы? 

### ISSUE THREAD

**Issue by Metavirus** [TelegramBot/Api#60]
Как обрабатывать callback вызовы? 
например у такого кода
```$bot = new \TelegramBot\Api\BotApi('YOUR_BOT_API_TOKEN');

$keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['callback_data' => '/answer', 'text' => 'Answer']
                ]
            ]
        );
        
$bot->sendMessage($chatId, $messageText, false, null, $keyboard);```

**Comment by dddobriak** [comment]
здесь есть решения от автора через 
```
public function on(Closure $event, Closure $checker = null)
    {
        $this->events->add($event, $checker);

        return $this;
    }
```
у меня почему-то так и не удалось принять через этот метод
через php://input можно принять

```
$output = json_decode(file_get_contents('php://input'), TRUE);
file_put_contents('log.txt', print_r($output, true));
```

**Comment by dddobriak** [comment]
автор вы не могли бы залить в репозиторий рабочего бота с примером данного метода? смотрю просто полно вопросов об одном и том же...

**Comment by YaroslavMolchan** [comment]
@dddobriak для `InlineKeyboardMarkup` использую `file_get_contents`, метод `command` не получится использовать для такого случая если динамический ответ может быть.

Свой код сейчас показывать не буду, попробую вечером сделать обработчик, дописать существующий или новый т.к. тот что сейчас я не делал, если не получится выложу уже просто код который сейчас использую на одном из проектов.

**Comment by YaroslavMolchan** [comment]
@dddobriak @Metavirus для обработки вызова используйте код с примера. Код модифицировал под `InlineKeyboardMarkup`: 
 ```
        $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN');
        // or initialize with botan.io tracker api key
        // $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN', 'YOUR_BOTAN_TRACKER_API_KEY');

        $bot->command('answer', function ($message, ...$params) use ($bot) {
            $bot->sendMessage($message->getChat()->getId(), 'answer');
            //в переменной $message мы имеем объект сообщения, можете взять любые данные которые приходят от Telegram
           //$params параметры которые пришли вместе с командой в тексте сообщения
        });

        $bot->run();
```
Теперь на живом примере, к примеру в `InlineKeyboardMarkup` нажали `Answer` и написали текст, в моем случае это будет вот такой:
```
@botName /answer Hello there!
```
В таком случае в переменной `$params` будет массив из 2х элементов: `Hello` и `there!`. Если указать без троеточия, тогда в переменной будет только текст `Hello`. Так что если вам нужен полностью весь текст, просто соберите массив в строку:
```
$answer = implode(' ', $params);
```
В моем случае ещё 1 элементом массива идёт ID сообщения на которое отвечаю, и потом уже текст ответа.

**Comment by hb220** [comment]
@Metavirus @dddobriak 

Я использую вот такую конструкцию.
Да, кстати, данные для callback'а передаются, как текст. /answer или answer - без разницы, передано будет "как есть". Поскольку это не команда боту в чате, то можно не заморачиваться со слэшем, боту всё равно. Если вам удобно/нужно - можно ставить.

$callback_loc, $find_command - это closures, которые выполняют, собственно, callback-команды

`$bot->on(function($update) use ($bot, $callback_loc, $find_command){
  $callback = $update->getCallbackQuery();
  $data = $callback->getData();
  if (preg_match('/^location\@[\-\d\.]+\,[\-\d\.]+$/', $data))
    $callback_loc($callback);
  else
  if (preg_match('/^find \d+ .+$/', $data))
    $find_command($callback);

}, function($update){
    $callback = $update->getCallbackQuery();
    if (is_null($callback) || !strlen($callback->getData()))
      return false;

    return true;
});
`
Мы проверяем данные, переданные в callback, в зависимости от этих данных вызываем обработчик.

Внутри обработчика делаем так:
`$callback_loc = function ($callback) use ($bot) {
  $message = $callback->getMessage();
  $chatid = $message->getChat()->getId();

...
# Получаем данные
  $data = $callback->getData();
# проверяем/обрабатываем
  preg_match('/^location\@([\-\d\.]+)\,([\-\d\.]+)$/', $data, $matches);
...
#Тут что-то делаем

# В конце (или в начале, зависит от логики) обязательно вызываем этот метод, чтобы убрать "часики" к callback-кнопки
  $bot->answerCallbackQuery($callback->getId());
};
`

**Comment by dddobriak** [comment]
@hb220 кстати, а что делает этот метод? `$bot->answerCallbackQuery($callback->getId());` каким образом он удаляет часики? Я не могу пока протестировать ни один из ответов, перекинули на старую версию php, там библиотека не работает, пришлось так бота написать, но часики эти бесят действительно))

**Comment by dddobriak** [comment]
все, я понял что он делает, удаляю вопрос)

**Comment by YaroslavMolchan** [comment]
@hb220 интересно как у вас это работает, если в `Update` нет `CallbackQuery` объекта, какая у вас версия?
