### ISSUE TITLE
editMessageCaption and editMessageReplyMarkup do not work

### ISSUE THREAD

**Issue by hb220** [TelegramBot/Api#61]
editMessageCaption and editMessageReplyMarkup methods do not work with error 'Bad Request' from Telegram server.

May be this is because typo in BotApi.php ?
Both methods use Message::fromResponse($this->call('editMessageText' instead of 'editMessageCaption' and 'editMessageReplyMarkup'.

**Comment by YaroslavMolchan** [comment]
Yes, that's it, fix it now
