### ISSUE TITLE
Оплата в боте

### ISSUE THREAD

**Issue by Fayozjon** [TelegramBot/Api#63]
Салам!
Будет ли методы приема оплаты в боте реализованы?
как скоро?
Чем помочь?

**Comment by YaroslavMolchan** [comment]
@Fayozjon будет, но пока нет времени реализовать её, через неделю буду разгружен больше и думаю начну делать если никто другой не начнет.

**Comment by YaroslavMolchan** [comment]
@Fayozjon платежи доступны в версии 2.3.0, как их реализовывать опишу позже в readme, можно ознакомиться пока [тут](https://blog.molchan.me/11/platezhi-cherez-php-telegram-bot-api)
