### ISSUE TITLE
Как описать реакцию на сообщения?

### ISSUE THREAD

**Issue by cjbars** [TelegramBot/Api#64]
Приветствую!
Коллеги, помогите пожалуйста, я затупил что-то:

Как описать реакцию бота на команды понятно: 
```php
$bot->command('ping', function ($message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'pong!');
});
```
А как реагировать на простые сообщения?
Или как реагировать на картинку?

Заранее спасибо!

**Comment by pwsdotru** [comment]
Вопрос уже задается не первый раз.

https://github.com/TelegramBot/Api/issues/29

**Comment by cjbars** [comment]
Вот я балбееес :-)
Спасибо!
