### ISSUE TITLE
Get callback from InlineKeyboardMarkup

### ISSUE THREAD

**Issue by choldimir** [TelegramBot/Api#65]
Hi all, 
Please how can I get the callback of an InlineKeyboardMarkup button?. I have this piece of code and I would like to treat "myCall"

```
$bot = new \TelegramBot\Api\Client($API_KEY);
    $bot->command('start', function ($message) use ($bot) {
        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['text' => 'link', 'url' => 'https://core.telegram.org'],
                    ['text' => 'Ping', 'callback_data' => "myCall"]
                ]
            ]
        );
        $msg = "Test";
        $bot->sendMessage($message->getChat()->getId(), $msg, null, false, null, $keyboard);
    });
$bot->run();

```

Thanks a lot.

**Comment by YaroslavMolchan** [comment]
Use this code:
```
$bot->on(function($update) use ($bot){
    $callback = $update->getCallbackQuery();
    //Answer to Telegram, you make answer in the end, or in the beginning.
    $bot->answerCallbackQuery($callback->getId());
    //Your data in $callback->getData() wiil be 'myCall'
}, function($update){
    return true;
});
```

**Comment by choldimir** [comment]
Thank you so much @YaroslavMolchan it works fine ;)

**Comment by choldimir** [comment]
Is it possible to create a click counter? Sorry, I'm lost on this :(

**Comment by YaroslavMolchan** [comment]
You can use `BotApi` method [editMessageReplyMarkup](https://github.com/TelegramBot/Api/blob/a1b9db06a68caa0fac4c98322defd63477aeac55/src/BotApi.php#L976) to edit `InlineKeyboardMarkup` and change counter value.

**Comment by choldimir** [comment]
I have problems with $callback->getInlineMessageId() is an empty value :'(
any ideas? I think that it's the same problem as issue #61

**Comment by YaroslavMolchan** [comment]
@choldimir fix editMessageReplyMarkup, try to update and try again

**Comment by choldimir** [comment]
@YaroslavMolchan 
My code is attached and the messageID is correct, but the buttons are not edited. What am I doing wrong?

First
```
    $bot->command('buttons', function ($message) use ($bot) {
        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['text' => 'Ping', 'callback_data' => "myCall"],
                    ['text' => 'link', 'url' => 'https://core.telegram.org']
                ]
            ]
        );
        $msg = "Message ID ".$message->getMessageId();
        $bot->sendMessage($message->getChat()->getId(), $msg, null, false, null, $keyboard);
    });
```


on click button and response..

```
    $bot->on(function($update) use ($bot){
        $callback = $update->getCallbackQuery();
        $messageID = $callback->getMessage()->getMessageId();

        if( $callback->getData() == "myCall" ){
            $bot->answerCallbackQuery($callback->getId(), 'ID "'.$messageID.'"', true);
            $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
                [
                    [
                        ['text' => 'YEAH', 'callback_data' => "myCall"],
                        ['text' => 'link', 'url' => 'https://core.telegram.org']
                    ]
                ]
            );
            $bot->editMessageReplyMarkup(
                $callback->getId(),
                $callback->getMessage()->getMessageId(),
                $keyboard
            );
        }
    }, function($update){
        return true;
    });
```


Thanks a lot ;)

**Comment by YaroslavMolchan** [comment]
Maybe the problem in first parameter in `editMessageReplyMarkup` method, you give query id, but need chat id. I think it will be work for you: `$callback->getMessage()->getChat()->getId()`,

**Comment by choldimir** [comment]
I have tried it but not works :(. I think that the id chat is correct because `$bot->answerCallbackQuery($callback->getId(), 'ID "'.$messageID.'"', true);` is working.

**Comment by KredoRoyals** [comment]
> I have tried it but not works :(. I think that the chat id is correct because $bot->answerCallbackQuery($callback->getId(), 'ID "'.$messageID.'"', true); works fine.

$bot->sendMessage($callback->getFrom()->getId(), $answer); it is work fine!

**Comment by choldimir** [comment]
???

Yes. sendMessage works fine, but editMessageReplyMarkup not works...
