### ISSUE TITLE
Похоже, что getChosenInlineResult не работает

### ISSUE THREAD

**Issue by rizhenkov** [TelegramBot/Api#67]
Всем привет. С inline query разобрался. Осталась часть, где можно получить сигнал о выбранном результате.

Вот пример кода:

```php
$bot->on(function($update) use ($bot){

        // Сюда программа не доходит

    }, function (\TelegramBot\Api\Types\Update $update) {
        if($update->getChosenInlineResult() === null){
            return false;
        }
        return true;
    });
```

У всех так?

**Comment by YaroslavMolchan** [comment]
Проверю вечером, если не забуду

**Comment by YaroslavMolchan** [comment]
@riartem пример `sendMessage` можете показать? Проверять буду на вашем примере

**Comment by Pabloader** [comment]
Тоже с таким сталкивался, похоже что сам телеграм не присылает информации об этом, хоть в документации это есть

**Comment by riartem** [comment]
Я уже плюнул на это, но похоже, что проблему нужно решать через настройку бота в BotFather — параметр "Inline Feedback".

![image](https://user-images.githubusercontent.com/987517/29488069-51aae18e-850c-11e7-9573-bafb6559cd62.png)

У кого дойдут руки проверить — отпишитесь плиз.

**Comment by Cyrills** [comment]
Значит какой-то другой хендлер срабатывает раньше. Возьмите пример запроса от телеги, воткните его в input и прогоните hook через дебагер. Все станет ясно
