### ISSUE TITLE
sendMessage missing parse_mode parameter

### ISSUE THREAD

**Issue by achimha** [TelegramBot/Api#7]
Hi,

Telegram introduced markdown support recently: https://core.telegram.org/bots/api#using-markdown

This introduces a new parse_mode parameter to sendMessage. Please add support for it in the API wrapper.

Thanks!
Achim

**Comment by iGusev** [comment]
Thanks! Implemented in [v.2.1.0](https://github.com/TelegramBot/Api/releases/tag/v2.1.0). Be careful, in the new version is broken backward compatibility in methods `sendAudio`, `sendVideo`, `sendMessage`
