### ISSUE TITLE
Не работает метод ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by popcorn2d** [TelegramBot/Api#71]
` $bot->command('start', function ($message) use ($bot) {
        $bot->sendMessage($message->getChat()->getId(), 'У меня есть команда /statusready /statusnotready');
        $keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(array(array("one", "two", "three")), true); // true for one-time keyboard
		$bot->sendMessage($chatId, $messageText, null, false, null, $keyboard);
    });`
Пример, который не работает

**Comment by YaroslavMolchan** [comment]
Что именно не работает?

**Comment by popcorn2d** [comment]
Это скопировано с примера

**Comment by YaroslavMolchan** [comment]
@popcorn2d может проблема в том что переменной нет у вас `$messageText`?
Что-то же должен сказать сервер или API если ошибка, что в вашем понимании "не работает"?

**Comment by popcorn2d** [comment]
@YaroslavMolchan Тогда можно рабочий пример привести?

**Comment by iGusev** [comment]
@popcorn2d 
Пример, который работает:

```
$bot->command('start', function ($message) use ($bot) {
            $bot->sendMessage($message->getChat()->getId(), 'У меня есть команда /statusready /statusnotready');
            $keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(
                [
                    [
                        "one",
                        "two",
                        "three"
                    ]
                ],
                true
            );
            // true for one-time keyboard
            $bot->sendMessage($message->getChat()->getId(), 'У меня есть команда /statusready /statusnotready', null, false, null, $keyboard);
        });
```
