### ISSUE TITLE
что то вообще не работает на laravel 5.3

### ISSUE THREAD

**Issue by progervlad** [TelegramBot/Api#72]
<?php

namespace App\Modules\Bots\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use \TelegramBot\Api\Client;

class BotsController extends Controller
{
    public function start_bot(){
        try {
            $bot = new Client('token');

            $bot->command('ping', function ($message) use ($bot) {
                $bot->sendMessage($message->getChat()->getId(), 'pong!');
            });
            
            $bot->run();
            echo "Good";

        } catch (\TelegramBot\Api\Exception $e) {
            $e->getMessage();
        }
    }

}

Выводит Good. Но бот ноль эмоций.

**Comment by Zircool** [comment]
Webhook  обращается к этому скрипту?

**Comment by progervlad** [comment]
нет, я без вебхука юзаю

**Comment by progervlad** [comment]
`<?php

namespace App\Modules\Bots\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use \TelegramBot\Api\Client;

class BotsController extends Controller
{
    public function start_bot(){
        try {
            $bot = new Client('token');

            $bot->command('ping', function ($message) use ($bot) {
                $bot->sendMessage($message->getChat()->getId(), 'pong!');
            });
            
            $bot->run();
            echo "Good";

        } catch (\TelegramBot\Api\Exception $e) {
            $e->getMessage();
        }
    }

}
`

**Comment by iGusev** [comment]
тогда нужно убрать обработку команды и просто `$bot->sendMessage($chatId, 'pong!');`, только chatId нужно знать (`123` - если пользователь/чат или `@channelName` - если канал)

**Comment by progervlad** [comment]
как узнать чат в таком случае? или создавать демона и чекать getUpdates?

**Comment by progervlad** [comment]
просто этот код я с примера взял, а он не рабочий оказывается)

**Comment by iGusev** [comment]
Сам телеграм должен дергать вебхук, отдавая в него объект класса `Update`, если же есть желание самостоятельно обрабатывать апдейты - можно использовать метод getUpdates, например, по крону. Есть и третий вариант, когда есть список известных чатов и триггер события не телеграм, например когда делаешь бота-админа канала и добавляешь сообщения через свою веб-админку или когда нужно слать сообщения всем пользователям, которые уже взаимодействовали с ботом ранее. Для таких случаев надо собирать $chatId заранее

Подробнее можно прочитать тут https://core.telegram.org/bots/api#getting-updates

**Comment by iGusev** [comment]
Чтобы разобраться как именно работает этот клиент проще всего начать отсюда https://github.com/TelegramBot/Api/blob/master/src/Client.php#L127 и следовать по вызываемым функциям, там нет магии)

**Comment by progervlad** [comment]
просто для вебхука нужно https которого нет. Думал что $bot->run(); заменит вечный цикл

**Comment by iGusev** [comment]
>нужно https которого нет
https://certbot.eff.org/ - инструкция для получения бесплатного сертификата на 3 месяца (можно обновлять еще на 3 месяца неограниченное количество раз)

**Comment by progervlad** [comment]
спасибо
