### ISSUE TITLE
Реализован ли метод KeyboardButton?  

### ISSUE THREAD

**Issue by Zircool** [TelegramBot/Api#74]
Реализован ли метод KeyboardButton?  По документации через него может отправить данные о своем текущем местоположении https://tlgrm.ru/docs/bots/api#keyboardbutton

**Comment by iGusev** [comment]
Класса не хватает в библиотеке, но можно сделать так:
```
<?
$bot->command('test1', function (Message $message) use ($bot, $eventList) {
    /** @var BotApi $bot */
    $response = $bot->sendMessage(
        $message->getChat()->getId(),
        'abcs',
        null,
        false,
        null
        ,
        new ReplyKeyboardMarkup(
            [
                [
                    [
                        'text' => 'test location button',
                        'request_location' => true
                    ]
                ]
            ],
            true
        )
    );
});
```

P.S. Документация на  https://tlgrm.ru не является актуальной, лучше пользоваться официальной https://core.telegram.org/bots/api

**Comment by EAIvanov** [comment]
Не работает приведённый выше пример (

`
$bot->command('loc', function ($message) use ($bot) {
            $keyboard = new ReplyKeyboardMarkup(
            [
                [
                    [
                        'text' => 'test location button',
                        'request_location' => true
                    ]
                ]
            ],
            true
            );        
            $bot->sendMessage($message->getChat()->getId(), 'location', null, false, null, $keyboard);
        });
`
По пробовал так, тоже без результата. В чём может быть причина?
