### ISSUE TITLE
Возможно ли отловить клик по клавиатуре ReplyKeyboardMarkup? 

### ISSUE THREAD

**Issue by Zircool** [TelegramBot/Api#82]
Возможно ли вызвать callbak при клике по клавиатуре ReplyKeyboardMarkup? Как лучше всего отловить?

**Comment by iGusev** [comment]
Клик на клавиатуру - это просто текст, коллбека нет, работать с этим можно через `$bot->on(...)`, устроено также как и `$bot->command()`. Подробнее о реализации можно почитать тут #29 и по ссылкам из того треда
