### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by rampapampapampapam** [TelegramBot/Api#84]
Вчера безостановочна начала вылетать ошибка вот такая. Начинается она если в сообщении указана команда и при инициализации класса был указан  Botan токен. Отключил нахрен этот Ботан глюк пропал. Вернул появился. Это можно как то исправить?

[2017-08-03 01:51:49] local.ERROR: TelegramBot\Api\InvalidJsonException: Syntax error in /Users/kruteevgrigoryalexandrovich/Git/sascrypto/control-panel/vendor/telegram-bot/api/src/BotApi.php:283
Stack trace:
#0 .../vendor/telegram-bot/api/src/Botan.php(75): TelegramBot\Api\BotApi::jsonValidate('<html>\r\n<head><...', true)
#1 .../vendor/telegram-bot/api/src/Events/EventCollection.php(67): TelegramBot\Api\Botan->track(Object(TelegramBot\Api\Types\Message), 'admin')
#2 .../vendor/telegram-bot/api/src/Client.php(117): TelegramBot\Api\Events\EventCollection->handle(Object(TelegramBot\Api\Types\Update))
#3 .../vendor/telegram-bot/api/src/Client.php(130): TelegramBot\Api\Client->handle(Array)
...

**Comment by iGusev** [comment]
Botan был интегрирован в самом начале, наверное, лучше его выпилить из либы, потому что никто не следит за актуальностью апи к нему

**Comment by riartem** [comment]
Согласен. Кому надо трекинг, могут отдельно подключить [Botan SDK](https://github.com/botanio/sdk#php)
