### ISSUE TITLE
[Вопрос] Как сравнить полученный Emoji?  

### ISSUE THREAD

**Issue by Zircool** [TelegramBot/Api#85]
К примеру у нас кнопка состоит из Emoji.
`$key = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(
					[
						[
							[
								'text' => 'ДТП сегодня '.json_decode('"\uD83C\uDFE7"'),
							],
							
						
						]
					],
					true,
					true

		); `

Как отловить клик по ней?  
Код: 
`$bot->on(function($update) use ($bot){
	$text = trim($update->getMessage()->getText());
	if($text == json_decode('"\uD83C\uDFE7"')){
		// клик по кнопке
	}
	
},function($update){
		return true;
	});`

Не отлавливает такой клик.

**Comment by iGusev** [comment]
>'text' => 'ДТП сегодня '.json_decode('"\uD83C\uDFE7"'),

>if($text == json_decode('"\uD83C\uDFE7"')){

Вы неверно сравниваете строки

P.S. вторая функция как раз и служит для фильтрации критериев срабатывания первой
>If second closure will return true (or if you are passed null instead of closure), first one will be executed.

**Comment by Zircool** [comment]
`P.S. вторая функция как раз и служит для фильтрации критериев срабатывания первой`

А пример можно?

**Comment by iGusev** [comment]
Допустим, есть инлайн-кейборд с кнопками `Какая-нибудь кнопка` и `Помощь`, обработчики нажатия таких кнопок будут выглядеть так:

```php
$bot->on(function (Update $update) use ($bot) {
    $bot->sendMessage(
        $update->getMessage()->getChat()->getId(),
        'Тут текст про помощь или типа того бла-бла бла',
        null,
        false,
        null,
        new ReplyKeyboardMarkup(
            [
                [['text' => 'Какая-нибудь кнопка'], ['text' => 'Помощь']]
            ],
            false,
            true,
            false
        )
    );
}, function (Update $update) {
    return $update->getMessage()->getText() === 'Помощь' ? true : false;
});
```
и

```php
$bot->on(function (Update $update) use ($bot) {
    $bot->sendMessage(
        $update->getMessage()->getChat()->getId(),
        '.
.∧＿∧
( ･ω･｡)つ━☆・*。
⊂. ノ ...・゜+.
しーＪ...°。+ *´¨)
..........· ´¸.·*´¨) ¸.·*¨)
..........(¸.·´ (¸.·\'* ☆ ВЖУХ ☆',
        null,
        false,
        null,
        new ReplyKeyboardMarkup(
            [
                [['text' => 'Какая-нибудь кнопка'], ['text' => 'Помощь']]
            ],
            false,
            true,
            false
        )
    );
}, function (Update $update) {
    return $update->getMessage()->getText() === 'Какая-нибудь кнопка' ? true : false;
});
```
