### ISSUE TITLE
Оформление ссылок в сообщении

### ISSUE THREAD

**Issue by Zircool** [TelegramBot/Api#87]
Добрый день. 
Кто нибудь знает, как можно запретить расшифровку ссылки в сообщении. Бот выдает сообщение с ссылкой на storebot 

Почему у бота альфа банка не высвечивается расшифровка ссылки
http://joxi.ru/D2PgNMOSdBvVYm 

А у меня высвечивается?  
http://joxi.ru/xAeyZx9FYbLkeA

Пробовал тип разметки markdown и html.

**Comment by iGusev** [comment]
Они передают параметр `disable_web_page_preview = true`
>Disables link previews for links in this message

[Подробнее](https://core.telegram.org/bots/api#sendmessage)
