### ISSUE TITLE
Download file [Feature]

### ISSUE THREAD

**Issue by cosecantt** [TelegramBot/Api#9]
Hi Ilya, any idea to add file download feature using curl to the script?
Like downloadFile();

**Comment by iGusev** [comment]
See [Release 2.2.0](https://github.com/TelegramBot/Api/releases/tag/v2.2.0) and [official docs](https://core.telegram.org/bots/api#getfile)

**Comment by iGusev** [comment]
or you want additional method `downloadFile()`?

**Comment by cosecantt** [comment]
Yes additional downloadFile() method. Now I can only get the url by getFile() method. But need somehow integrated efficient way. Then there will be no need to write a separate download script. I saw same additional download feature in python libraries. Thank you for quick reply.

**Comment by iGusev** [comment]
Implemented in [2.2.1](https://github.com/TelegramBot/Api/releases/tag/v2.2.1). Now you can get the file's contents via `downloadFile($fileId)`, but how to store the contents is not a problem of this library. I'm reccomend use [Flysystem](http://flysystem.thephpleague.com/).

**Comment by cosecantt** [comment]
Ilya, I couldn't find downloadFile($fileId) method in the latest commits or am I missing something?
Thank you for Flysystem recommendation. I will definitely check it out.

**Comment by iGusev** [comment]
Just set your composer.json:
```
"require": {
    "telegram-bot/api": ">=2.2.1"
  },
```
or:
```
"require": {
    "telegram-bot/api": "dev-master"
  }
```

**Comment by iGusev** [comment]
Sorry, it's my fail. I forgot to do a push. Fixed

**Comment by cosecantt** [comment]
Ok it works now. Thank you.
