### ISSUE TITLE
Форматирование текста

### ISSUE THREAD

**Issue by Troinik** [TelegramBot/Api#90]
Доброго времени суток) 
Текст форматируется двумя различными стилями - Markdown и HTML.
Если я все правильно понял, то необходимо добавить указанные символы и выбрать тип parse_mode
`        $bot->sendMessage(321321321, "<b>наш текст</b>", 'HTML');
`
Сообщение приходит неформатированное, я что-то делаю не так?

**Comment by BoShurik** [comment]
`$bot->sendMessage(321321321, "<b>наш текст</b>", 'html');`

**Comment by YaroslavMolchan** [comment]
@Troinik если мне память не изменят было что-то похожее, не разбирался в чём проблема, просто сменил на markdown и тогда смог сделать жирный шрифт, не думаю что проблема в библиотеке, возможно есть нюансы составления сообщения  в самом парсере телеграма

**Comment by BoShurik** [comment]
Хм. Странно, у меня пример работает с любым регистром `html`. Может дело в клиенте?

**Comment by Troinik** [comment]
спасибо, буду разбираться )

**Comment by Churakovmike** [comment]
А доступно вложенное форматирование? Например - 

`<b><a> .... </a></b>`

**Comment by Troinik** [comment]
Почему то только разметка Markdown работает, пытаюсь разобраться.

**Comment by dotansky** [comment]
Если бы вы читали API телеграма, то таких вопросов бы не возникло. На данный момент, API телеграма поддерживает лишь несколько простых html тегов. Те, что вы написали включительно, только проблема в том, что API не читает сами символы, такие как "<" и ">" , ну еще и "&" и их нужно заменять. Поэтому и не получается. Откройте, почитайте документацию про html в использовании API. Там все есть.
