### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by andrey-helldar** [TelegramBot/Api#91]
I'm using code:

```
try {
    $chat_id = 'MY-CHAT-ID';
    $text = 'My test message';
    $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN');
    $bot->sendMessage($chat_id, $text);
    $bot->run();

    return 'ok';
} catch(\TelegramBot\Api\Exception $e) {
   return $e->getMessage();
}
```

The bot was added by the administrator in the channel. Messages to the channel are successfully coming.

But the site returns an error: `Syntax error`.

First line in `getTrace()` method:
`#0 C:\\OpenServer\\domains\\mysite.dev\\vendor\\telegram-bot\\api\\src\\Client.php(134): TelegramBot\\Api\\BotApi::jsonValidate('', true)`

**Comment by YaroslavMolchan** [comment]
@andrey-helldar why are you using `$bot->run()` in your code? To only send message you don`t need it

**Comment by YaroslavMolchan** [comment]
@andrey-helldar this example for webhook action, for just send message example above.

**Comment by andrey-helldar** [comment]
Okay, thanks!
