### ISSUE TITLE
update["message"]["contact"] is null why?

### ISSUE THREAD

**Issue by timkimtim** [TelegramBot/Api#93]
After user shares his contact with (works fine):
`$reply = "phone_num";`
`$buttons = [[['text' => 'test contact button','request_contact' => true]]];`
`$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup($buttons, null, true);`
`$telegram->sendMessage($chat_id, $reply, false, null, null, $keyboard);`
number in `$update["message"]["contact"]["phone_number"]` still null. What the issue? How can i get contact from user?
P.S. i use webhook method

**Comment by timkimtim** [comment]
@YaroslavMolchan No, that's doesn't work: PHP Fatal error:  Call to a member function getCallbackQuery() on a non-object in...
P.S. i get update like this:
`$update = file_get_contents('php://input');`
`$update = json_decode($update, true);`

**Comment by YaroslavMolchan** [comment]
@timkimtim that`s why you have an error, try to get updates like this:
```
require_once "vendor/autoload.php";

try {
    $bot = new \TelegramBot\Api\Client('YOUR_BOT_API_TOKEN');

    $bot->on(function($update) {
        $phoneNumber = $update->getCallbackQuery()->getMessage()->getContact()->getPhoneNumber();
     }, function($update){
         return true;
     });

    $bot->run();

} catch (\TelegramBot\Api\Exception $e) {
    $e->getMessage();
}
```

**Comment by timkimtim** [comment]
@YaroslavMolchan sorry, i'm not so experienced(
with your code i get "PHP Fatal error:  Call to a member function getMessage() on a non-object in..."
if i use it like this:
`try {`
`    $telegram_client->on(function($update1) use ($telegram_client) {`
`        $phoneNumber = $update1->getMessage()->getContact()->getPhoneNumber();`
`        }, function($update1){`
`            return true;`
`            });`

`    $telegram_client->run();`
`} catch (\TelegramBot\Api\Exception $e) {`
`    $e->getMessage();`
`}`
i get: "PHP Fatal error:  Call to a member function getPhoneNumber() on a non-object in..."

**Comment by YaroslavMolchan** [comment]
You again type:
`$phoneNumber = $update1->getMessage()->getContact()->getPhoneNumber();`
But need:
`$phoneNumber = $update1->getCallbackQuery()->getMessage()->getContact()->getPhoneNumber();`
But your error said that `$update1` it`s not a object, you can try this but I think error in another thing.
Can you paste all your code?

**Comment by YaroslavMolchan** [comment]
@timkimtim you are don`t using this package in your code, you need to use code from this https://github.com/TelegramBot/Api/issues/93#issuecomment-331887735 , but you again use file_get_contents('php://input');
I can`t help you if you don`t read readme of this packege and don`t use it.
