### ISSUE TITLE
bot was blocked by the user

### ISSUE THREAD

**Issue by dserdiuk** [TelegramBot/Api#94]
При рассылке сообщений возникает ошибка Fatal error: Uncaught exception 'TelegramBot\Api\HttpException' with message 'Forbidden: bot was blocked by the user' . Всё бы ничего, но дальше скрипт перестаёт работать. Можно ли как-нибудь сделать так, чтобы скрипт не приостанавливал работу, а продолжал дальше?

Ну или как можно проверить заблокировал ли юзер или нет?

**Comment by BoShurik** [comment]
try ... catch ...
