### ISSUE TITLE
Bad description. Lost few days to debug and understand.

### ISSUE THREAD

**Issue by Noizefan** [TelegramBot/Api#96]
Hello! Message->caption has a bad description. Not only videos has a description, photos too. And it is not always empty, you can edit it below the photo/video, when sending. Fix it, please. Sorry for this very little and stupid issue, I like your project, but it got me to lost few days to debug and see why I can't get the text of the message with photo and text.

**Comment by YaroslavMolchan** [comment]
I set caption for videos and photos and it works well, can you show your example?
