### ISSUE TITLE
SuccesfulPayment question

### ISSUE THREAD

**Issue by timkimtim** [TelegramBot/Api#97]
Can someone help me with a tip, how should i get SuccesfulPaymant object, with total_amount and provider_payment_charge_id, after bot successfuly answerPreCheckoutQuery, like this:
```
try {
$telegram_client->preCheckoutQuery(function ($query) use ($telegram_client, $telegram) {
$telegram->answerPreCheckoutQuery($query->getId(), true);
});
$telegram_client->run();
 } catch (\TelegramBot\Api\Exception $e) {
 //$e->getMessage();
```
Thank you in advance

**Comment by YaroslavMolchan** [comment]
@timkimtim you need to handle message with field `successful_payment` in Message object and get info from there.
I think you need catch messages and check for this attribute, like this: https://github.com/TelegramBot/Api/issues/29
More info about this read [here](https://core.telegram.org/bots/payments#6-checkout)

**Comment by timkimtim** [comment]
@YaroslavMolchan Thanks a lot.
