### ISSUE TITLE
how create a conversion between user and bot ?

### ISSUE THREAD

**Issue by pooria-jahedi** [TelegramBot/Api#98]
please help me ! 
how create a conversion between user and bot ?
i want give some information from user with my bot

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi just send message message from bot to user and it will be created, but you need to know user chat id.

**Comment by pooria-jahedi** [comment]
@YaroslavMolchan thank you.
how get message id from robot ?

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi can you give example, I don`t understand you

**Comment by pooria-jahedi** [comment]
i want delete a file in call back. but i cant find file's message id

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi which callback? If it something like `inlineQueryAnswer` - you need to store message id in `InlineQuery` `query` attribute and then in answer get it

**Comment by pooria-jahedi** [comment]
how can i store in `InlineQuery `? 
can you give example ?

**Comment by pooria-jahedi** [comment]
`  elseif ($callback->getData() == "back_prev_level1")
            {
                $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
                    [
                        [
                            ['text' => '🔙 بازگشت به مرحله اول', 'callback_data' => "back_first_level"]
                        ],
                        [
                            ['text' => 'بیکارم', 'callback_data' => "unemployed"],
                            ['text' => 'کارمندم', 'callback_data' => "employed"]
                        ],
                        [
                            ['text' => 'کار آفرین و مدیرخودمم', 'callback_data' => "entrepreneur"]
                        ]
                    ]
                );
                $bot->editMessageText($user_id,$message_id, 'لطفا یکی از گزینه های زیر را انتخاب نمایید');

                $bot->deleteMessage($user_id,$message_id+1);
                $bot->editMessageReplyMarkup($user_id,$message_id,$keyboard);
                $bot->answerCallbackQuery($callback->getId(), null, false);

            }`

this is my code i want when click on on this call back , edit last message and delete that file

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi oh, try to get message id like this:
`$callback->getMessage()->getId()`

**Comment by pooria-jahedi** [comment]
i use this code but it call back first message id and don't give me file message id

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi I don't know how to help because I don't know how your code is working. Seems like your callback not for message with file, that's why you get another message id, you need create a callback for message with file. You need to change logic for this feature I think.

**Comment by pooria-jahedi** [comment]
thank you sir

**Comment by pooria-jahedi** [comment]
`$file_id = update->getCallbackQuery()->getMessage()->getAudio()->getFileId();`
is this code true ?

**Comment by YaroslavMolchan** [comment]
@pooria-jahedi yes
