### ISSUE TITLE
InlineKeyboard in vertical? [question]

### ISSUE THREAD

**Issue by filipemansano** [TelegramBot/Api#99]
How to make the inline keyboard 1 button for each line? in print below, the buttons are side by side in horizontal which ends up hiding parts of the words in long texts

![image](https://user-images.githubusercontent.com/6247393/32009013-91cd5b7a-b98c-11e7-8bb6-3e4ccd78e698.png)

**Comment by YaroslavMolchan** [comment]
@filipemansano just wrap each element in one more array

**Comment by filipemansano** [comment]
@YaroslavMolchan not work... 

![image](https://user-images.githubusercontent.com/6247393/32670427-e4a76aac-c62a-11e7-8aa3-dec31311215b.png)


![image](https://user-images.githubusercontent.com/6247393/32670447-f440c184-c62a-11e7-9cb4-dbd90c704fcb.png)

**Comment by YaroslavMolchan** [comment]
@filipemansano as I said earlier, wrap each array into array:
```
$keys = [
	[["text" => "Test 1 looooooong text 1", "callback_data" => "1"]],
	[["text" => "Test 2 looooooong text 2", "callback_data" => "2"]],
	[["text" => "Test 3 looooooong text 3", "callback_data" => "3"]],
	[["text" => "Test 4 looooooong text 4", "callback_data" => "4"]],
];
```

**Comment by filipemansano** [comment]
@YaroslavMolchan  sorry now I understood what you mean, it worked thank you!
